package com.uremont.bluetooth

/**
 * Справочник WMI (первые 3 символа VIN) → отображаемое название производителя/завода.
 * Источник: Wikibooks «World Manufacturer Identifier» (community-maintained),
 * не заменяет официальную платную подписку SAE J1044.
 * Обновление: scripts/generate_vin_wmi_table.py
 */
object VinWmiTable {

    private val ENTRIES: Map<String, String> = mapOf(
        "10B" to "Brenner Tank",
        "10R" to "E-Z-GO",
        "10T" to "Oshkosh Corporation",
        "11H" to "Hendrickson Mobile Equipment, Inc.",
        "12A" to "Avanti",
        "137" to "AM General Hummer & Hummer H1",
        "13N" to "Fontaine",
        "15G" to "Gillig bus",
        "16C" to "Clenet Coachworks",
        "16W" to "West-Mark",
        "16X" to "Vixen 21 motorhome",
        "17N" to "John Deere incomplete vehicle",
        "19U" to "Acura car",
        "19V" to "Acura car",
        "19X" to "Honda car",
        "1AC" to "American Motors Corporation MPV",
        "1AF" to "American LaFrance truck",
        "1AJ" to "Ajax Manufacturing",
        "1AM" to "American Motors Corporation car & Renault Alliance 1983 only",
        "1B3" to "Dodge car 1981–2011",
        "1B4" to "Dodge MPV/SUV 1981–2002",
        "1B6" to "Dodge incomplete vehicle 1981–2002",
        "1B7" to "Dodge truck 1981–2002",
        "1BA" to "Blue Bird Corporation bus",
        "1BB" to "Blue Bird Wanderlodge MPV",
        "1BD" to "Blue Bird Corporation incomplete vehicle",
        "1BL" to "Balko, Inc.",
        "1BN" to "Beall Trailers",
        "1C3" to "Chrysler Group (all brands) car (including Lancia) 2012-",
        "1C4" to "Chrysler Group (all brands) MPV 2012–",
        "1C6" to "Chrysler Group (all brands) truck 2012–",
        "1C8" to "Chrysler brand MPV 2001–2005",
        "1CM" to "Checker Motors Corporation",
        "1CU" to "Cushman Haulster",
        "1CY" to "Battle Motors, Inc.",
        "1D3" to "Dodge truck 2002–2009",
        "1D4" to "Dodge MPV/SUV 2003–2011 only",
        "1D7" to "Dodge truck 2002–2011",
        "1D8" to "Dodge MPV/SUV 2003–2009 only",
        "1DW" to "Stoughton Trailers",
        "1EU" to "Eagle Coach Corporation",
        "1F1" to "Ford SUV - Limousine",
        "1F6" to "Ford stripped chassis",
        "1FA" to "Ford car",
        "1FB" to "Ford\"bus\"",
        "1FC" to "Ford stripped chassis",
        "1FD" to "Ford incomplete vehicle",
        "1FM" to "Ford MPV/SUV",
        "1FT" to "Ford truck",
        "1FU" to "Freightliner truck",
        "1FV" to "Freightliner incomplete vehicle",
        "1G0" to "Opel/Vauxhall car 2007–2017",
        "1G1" to "Chevrolet car",
        "1G2" to "Pontiac car",
        "1G3" to "Oldsmobile car",
        "1G4" to "Buick car",
        "1G5" to "GMC MPV/SUV 1981–1986",
        "1G6" to "Cadillac car",
        "1G7" to "Pontiac car only sold by GM Canada",
        "1G8" to "Saturn car 1991–2010",
        "1GA" to "Chevrolet \"bus\"",
        "1GB" to "Chevrolet incomplete vehicles",
        "1GC" to "Chevrolet truck",
        "1GD" to "GMC incomplete vehicles",
        "1GE" to "Cadillac incomplete vehicle",
        "1GF" to "Flxible bus",
        "1GG" to "Isuzu pickup trucks",
        "1GH" to "Holden Acadia 2019–2020",
        "1GJ" to "GMC \"bus\" (van with more than 3 rows of seats) 1987–",
        "1GK" to "GMC MPV/SUV 1987–",
        "1GM" to "Pontiac MPV",
        "1GN" to "Chevrolet MPV/SUV 1987-",
        "1GR" to "Great Dane Trailers",
        "1GT" to "GMC Truck",
        "1GY" to "Cadillac SUV",
        "1HA" to "Chevrolet incomplete vehicles",
        "1HD" to "Harley-Davidson & LiveWire",
        "1HF" to "Honda motorcycle/ATV/UTV",
        "1HG" to "Honda car",
        "1HS" to "International Trucks & Caterpillar Trucks truck",
        "1HV" to "IC Bus incomplete bus",
        "1J4" to "Jeep SUV 1989–2011",
        "1J7" to "Jeep truck 1989–1992",
        "1J8" to "Jeep SUV 2002–2011",
        "1JC" to "Jeep SUV 1981–1988",
        "1JJ" to "Wabash",
        "1JT" to "Jeep truck 1981–1988",
        "1JU" to "Marmon Motor Company",
        "1L0" to "Lufkin Trailers",
        "1L1" to "Lincoln car – limousine",
        "1LH" to "Landoll",
        "1LJ" to "Lincoln incomplete vehicle",
        "1LN" to "Lincoln car",
        "1LV" to "Lectra Motors",
        "1M0" to "John Deere Gator",
        "1M1" to "Mack Truck USA",
        "1M2" to "Mack Truck USA incomplete vehicle",
        "1M3" to "Mack Truck USA",
        "1M4" to "Mack Truck USA",
        "1M8" to "Motor Coach Industries",
        "1MB" to "Mercedes-Benz Truck Co.",
        "1ME" to "Mercury car",
        "1MR" to "Continental Mark VI & VII 1981–1985 & Continental sedan 1982–1985",
        "1N4" to "Nissan car",
        "1N6" to "Nissan truck",
        "1NK" to "Kenworth incomplete vehicle",
        "1NL" to "Gulf Stream Coach",
        "1NN" to "Monon",
        "1NP" to "Peterbilt incomplete vehicle",
        "1NX" to "Toyota car",
        "1P3" to "Plymouth car",
        "1P4" to "Plymouth MPV/SUV",
        "1P7" to "Plymouth Scamp",
        "1PM" to "Polar Tank Trailer",
        "1PT" to "Trailmobile Trailer Corporation",
        "1PY" to "John Deere USA",
        "1RF" to "Roadmaster, Monaco Coach Corporation",
        "1RN" to "Reitnouer",
        "1S1" to "Strick Trailers",
        "1ST" to "Airstream",
        "1T7" to "Thomas Built Buses",
        "1T8" to "Thomas Built Buses",
        "1TC" to "Coachmen Recreational Vehicle Co., LLC",
        "1TD" to "Transcraft Corporation",
        "1TK" to "Trail King",
        "1TU" to "Transportation Manufacturing Corporation",
        "1UJ" to "Jayco, Inc.",
        "1UT" to "AM General military trucks, Jeep DJ",
        "1UY" to "Utility Trailer",
        "1V1" to "Volkswagen truck",
        "1V2" to "Volkswagen SUV",
        "1VH" to "Orion Bus Industries",
        "1VW" to "Volkswagen car",
        "1W1" to "Wilson Trailer",
        "1W8" to "Witzco",
        "1WT" to "Winnebago Industries",
        "1WU" to "White Motor Company truck",
        "1XA" to "Excalibur Automobile Corporation",
        "1XK" to "Kenworth truck",
        "1XM" to "Renault Alliance/GTA/Encore 1984–1987",
        "1XP" to "Peterbilt truck",
        "1Y1" to "Chevrolet/Geo car",
        "1YJ" to "Rokon International, Inc.",
        "1YV" to "Mazda",
        "1ZV" to "Ford",
        "1ZW" to "Mercury",
        "2A3" to "Imperial",
        "2B1" to "Orion Bus Industries",
        "2B3" to "Dodge car 1981–2011",
        "2B4" to "Dodge MPV 1981–2002",
        "2B5" to "Dodge \"bus\" (van with more than 3 rows of seats) 1981–2002",
        "2B6" to "Dodge incomplete vehicle 1981–2002",
        "2B7" to "Dodge truck 1981–2002",
        "2BC" to "Jeep Wrangler (YJ) 1987–1988",
        "2BP" to "Ski-Doo",
        "2BV" to "Can-Am & Bombardier ATV",
        "2BW" to "Can-Am Commander E LSV",
        "2BX" to "Can-Am Spyder",
        "2BZ" to "Can-Am Freedom Trailer for Can-Am Spyder",
        "2C1" to "Geo/Chevrolet car",
        "2C3" to "Chrysler Group (all brands) car (including Lancia) 2012-",
        "2C4" to "Chrysler brand MPV/SUV 2000–2005",
        "2C7" to "Pontiac car",
        "2C8" to "Chrysler brand MPV/SUV 2001–2005",
        "2CC" to "American Motors Corporation MPV",
        "2CG" to "Asüna/Pontiac SUV",
        "2CK" to "Pontiac Torrent SUV",
        "2CM" to "American Motors Corporation car",
        "2CN" to "Geo/Chevrolet SUV",
        "2CT" to "GMC Terrain SUV",
        "2D4" to "Dodge MPV 2003–2011 only",
        "2D6" to "Dodge incomplete vehicle 2003",
        "2D7" to "Dodge truck 2003",
        "2D8" to "Dodge MPV 2003–2011 only",
        "2DG" to "Ontario Drive & Gear",
        "2DM" to "Di-Mond Trailers",
        "2DN" to "Dynasty Electric Car Corporation",
        "2E3" to "Eagle car 1989–1997",
        "2E4" to "2011 Lancia MPV",
        "2EZ" to "Electra Meccanica Vehicles Corp.",
        "2FA" to "Ford car",
        "2FH" to "Zenn Motor Co., Ltd.",
        "2FM" to "Ford MPV/SUV",
        "2FT" to "Ford truck",
        "2FU" to "Freightliner",
        "2FV" to "Freightliner",
        "2FW" to "Sterling Trucks",
        "2FY" to "New Flyer",
        "2FZ" to "Sterling Trucks",
        "2G0" to "GMC \"bus\" (van with more than 3 rows of seats) 1981–1986",
        "2G1" to "Chevrolet car",
        "2G2" to "Pontiac car",
        "2G3" to "Oldsmobile car",
        "2G4" to "Buick car",
        "2G5" to "Chevrolet BrightDrop / BrightDrop Zevo truck 2023-",
        "2G6" to "Cadillac car",
        "2G7" to "Pontiac car only sold by GM Canada",
        "2G8" to "Chevrolet MPV 1981–1986",
        "2GA" to "Chevrolet \"bus\"",
        "2GB" to "Chevrolet incomplete vehicles",
        "2GC" to "Chevrolet truck",
        "2GD" to "GMC incomplete vehicles",
        "2GE" to "Cadillac incomplete vehicle",
        "2GH" to "GMC GM New Look bus & GM Classic series bus",
        "2GJ" to "GMC \"bus\" (van with more than 3 rows of seats) 1987–",
        "2GK" to "GMC MPV/SUV 1987–",
        "2GN" to "Chevrolet MPV/SUV 1987-",
        "2GT" to "GMC truck",
        "2HG" to "Honda car",
        "2HH" to "Acura car",
        "2HJ" to "Honda truck",
        "2HK" to "Honda MPV/SUV",
        "2HM" to "Hyundai Canada",
        "2HN" to "Acura SUV",
        "2HS" to "International Trucks truck",
        "2HT" to "International Trucks incomplete vehicle",
        "2J4" to "Jeep Wrangler (YJ) 1989–1992",
        "2L1" to "Lincoln incomplete vehicle – limo",
        "2LD" to "Triple E Canada Ltd.",
        "2LJ" to "Lincoln incomplete vehicle – hearse",
        "2LM" to "Lincoln SUV",
        "2LN" to "Lincoln car",
        "2M1" to "Mack Trucks",
        "2M2" to "Mack Trucks",
        "2ME" to "Mercury car",
        "2MG" to "Motor Coach Industries",
        "2MH" to "Mercury incomplete vehicle",
        "2MR" to "Mercury MPV",
        "2NK" to "Kenworth incomplete vehicle",
        "2NP" to "Peterbilt incomplete vehicle",
        "2NV" to "Nova Bus",
        "2P3" to "Plymouth car",
        "2P4" to "Plymouth MPV 1981–2000",
        "2P5" to "Plymouth \"bus\" (van with more than 3 rows of seats) 1981–1983",
        "2PC" to "Prevost 1996-",
        "2S2" to "Suzuki car",
        "2S3" to "Suzuki SUV",
        "2T1" to "Toyota car",
        "2T2" to "Lexus SUV",
        "2T3" to "Toyota SUV",
        "2TU" to "Tri-Star Industries Limited",
        "2V4" to "Volkswagen Routan",
        "2V8" to "Volkswagen Routan",
        "2WK" to "Western Star truck",
        "2WL" to "Western Star incomplete vehicle",
        "2WM" to "Western Star incomplete vehicle",
        "2XK" to "Kenworth truck",
        "2XM" to "Eagle Premier 1988 only",
        "2XP" to "Peterbilt truck",
        "3AK" to "Freightliner Trucks",
        "3AL" to "Freightliner Trucks",
        "3AW" to "Fruehauf de Mexico",
        "3AX" to "Scania Mexico",
        "3B3" to "Dodge car 1981–2011",
        "3B4" to "Dodge SUV 1986–1993",
        "3B6" to "Dodge incomplete vehicle 1981–2002",
        "3B7" to "Dodge truck 1981–2002",
        "3BE" to "Scania Mexico",
        "3BJ" to "Western Star 3700 truck",
        "3BK" to "Kenworth incomplete vehicle",
        "3BM" to "Motor Coach Industries bus",
        "3BP" to "Peterbilt incomplete vehicle",
        "3C3" to "Chrysler Group (all brands) car (including Fiat) 2012-",
        "3C4" to "Chrysler Group (all brands) MPV (including Fiat) 2012-",
        "3C6" to "Chrysler Group (all brands) truck 2012–",
        "3C7" to "Chrysler Group (all brands) incomplete vehicle 2012–",
        "3C8" to "Chrysler brand MPV 2001–2005",
        "3CA" to "Chrysler brand MPV 2001",
        "3CE" to "Volvo Buses de Mexico",
        "3CG" to "KTMMEX S.A. de C.V.",
        "3CZ" to "Honda SUV",
        "3D2" to "Dodge incomplete vehicle 2007–2009",
        "3D3" to "Dodge truck 2006–2009",
        "3D4" to "Dodge SUV 2009–2011",
        "3D6" to "Dodge incomplete vehicle 2003–2011",
        "3D7" to "Dodge truck 2002–2011",
        "3E4" to "2011 Fiat SUV",
        "3EL" to "ATRO",
        "3F6" to "Sterling Bullet",
        "3FA" to "Ford car",
        "3FC" to "Ford stripped chassis",
        "3FE" to "Ford Mexico",
        "3FM" to "Ford MPV/SUV",
        "3FN" to "Ford F-650/F-750",
        "3FR" to "Ford F-650/F-750 & Ford LCF",
        "3FT" to "Ford truck",
        "3G0" to "Holden Equinox 2018–2020",
        "3G1" to "Chevrolet car",
        "3G2" to "Pontiac car",
        "3G4" to "Buick car",
        "3G5" to "Buick SUV",
        "3G7" to "Pontiac SUV",
        "3GA" to "JAC models assembled by Giant Motors in Mexico",
        "3GC" to "Chevrolet truck",
        "3GK" to "GMC SUV",
        "3GM" to "Holden Suburban",
        "3GN" to "Chevrolet SUV",
        "3GP" to "Honda Prologue EV",
        "3GS" to "Saturn SUV",
        "3GT" to "GMC truck",
        "3GY" to "Cadillac SUV",
        "3H1" to "Honda motorcycle/UTV",
        "3H3" to "Hyundai de Mexico, S.A. de C.V. for Hyundai Translead",
        "3HA" to "International Trucks incomplete vehicle",
        "3HC" to "International Trucks truck",
        "3HD" to "Acura SUV",
        "3HG" to "Honda car",
        "3HS" to "International Trucks & Caterpillar Trucks truck",
        "3HT" to "International Trucks & Caterpillar Trucks incomplete vehicle",
        "3HV" to "International incomplete bus",
        "3JB" to "BRP Mexico",
        "3KM" to "Kia/Hyundai MPV/SUV",
        "3KP" to "Kia/Hyundai car",
        "3LN" to "Lincoln car",
        "3MA" to "Mercury car",
        "3MD" to "Mazda de Mexico car",
        "3ME" to "Mercury car",
        "3MF" to "BMW M car",
        "3MG" to "Isuzu Motors de Mexico",
        "3MJ" to "Mazda CX-3",
        "3MV" to "Mazda de Mexico SUV",
        "3MW" to "BMW car",
        "3MY" to "Toyota car",
        "3MZ" to "Mazda de Mexico car",
        "3N1" to "Nissan Mexico car",
        "3N6" to "Nissan Mexico truck & Chevrolet City Express",
        "3N8" to "Nissan Mexico MPV",
        "3NE" to "Polaris Industries UTV",
        "3NS" to "Polaris Industries ATV",
        "3P3" to "Plymouth car",
        "3PC" to "Infiniti SUV",
        "3TM" to "Toyota truck",
        "3TY" to "Toyota truck",
        "3VV" to "Volkswagen Mexico SUV",
        "3VW" to "Volkswagen Mexico car",
        "3WK" to "Kenworth truck",
        "3WP" to "Peterbilt truck",
        "43C" to "Consulier",
        "44K" to "HME Inc. (fire engines - incomplete vehicle",
        "46G" to "Gillig incomplete vehicle",
        "46J" to "Federal Motors Inc",
        "478" to "Honda ATV",
        "480" to "Sterling Trucks",
        "49H" to "Sterling Trucks incomplete vehicle",
        "4A3" to "Mitsubishi Motors car",
        "4A4" to "Mitsubishi Motors SUV",
        "4B3" to "Dodge car",
        "4C3" to "Chrysler car",
        "4C6" to "Reinke Manufacturing Company",
        "4CD" to "Oshkosh Chassis Division incomplete vehicle",
        "4DR" to "IC Bus",
        "4E3" to "Eagle car",
        "4EN" to "E-ONE, Inc.",
        "4F2" to "Mazda SUV",
        "4F4" to "Mazda truck",
        "4G1" to "Chevrolet Cavalier convertible",
        "4G2" to "Pontiac Sunfire convertible",
        "4G3" to "Toyota Cavalier",
        "4G5" to "General Motors EV1",
        "4GD" to "Opel/Vauxhall Sintra",
        "4GL" to "Buick incomplete vehicle",
        "4GT" to "Isuzu incomplete vehicle built by GM",
        "4J8" to "LBT, Inc.",
        "4JG" to "Mercedes-Benz SUV",
        "4KB" to "Chevrolet W-Series incomplete vehicle",
        "4KD" to "GMC W-Series incomplete vehicle",
        "4KE" to "U.S. Electricar Consulier",
        "4KL" to "Isuzu N-Series incomplete vehicle (gas engine only) built by GM",
        "4LM" to "Capacity of Texas",
        "4M2" to "Mercury MPV/SUV",
        "4MB" to "Mitsubishi Motors",
        "4ML" to "Oshkosh Trailer Division",
        "4MZ" to "Buell Motorcycle Company",
        "4N2" to "Nissan Quest",
        "4NU" to "Isuzu Ascender",
        "4P1" to "Pierce Manufacturing Inc. USA",
        "4P3" to "Mitsubishi Motors SUV",
        "4RK" to "Nova Bus & Prevost",
        "4S1" to "Isuzu truck",
        "4S2" to "Isuzu SUV",
        "4S3" to "Subaru car",
        "4S4" to "Subaru SUV/MPV",
        "4S6" to "Honda SUV",
        "4S7" to "Spartan Motors incomplete vehicle",
        "4T1" to "Toyota car",
        "4T3" to "Toyota MPV/SUV",
        "4T4" to "Toyota car",
        "4TA" to "Toyota truck",
        "4UF" to "Arctic Cat Inc.",
        "4US" to "BMW car",
        "4V0" to "Crossroads RV",
        "4V1" to "WhiteGMC truck",
        "4V2" to "WhiteGMC incomplete vehicle",
        "4V3" to "Volvo truck",
        "4V4" to "Volvo Trucks North America truck",
        "4V5" to "Volvo Trucks North America incomplete vehicle",
        "4V6" to "Volvo truck",
        "4VA" to "Volvo Trucks North America truck",
        "4VE" to "Volvo Trucks North America incomplete vehicle",
        "4VG" to "Volvo Trucks North America truck",
        "4VH" to "Volvo Trucks North America incomplete vehicle",
        "4VM" to "Volvo Trucks North America incomplete vehicle",
        "4VZ" to "Spartan Motors/The Shyft Group incomplete vehicle – bare chassis only",
        "4W1" to "'24+ Chevrolet Suburban HD",
        "4W5" to "Acura ZDX EV",
        "4WW" to "Wilson Trailer Sales",
        "4X4" to "Forest River",
        "4XA" to "Polaris Inc.",
        "4YD" to "KeyStone RV Company",
        "4YM" to "Anderson Manufacturing",
        "4Z3" to "American LaFrance truck",
        "50E" to "Lucid Motors passenger car",
        "50G" to "Karma Automotive",
        "516" to "Autocar truck",
        "51R" to "Brammo Motorcycles",
        "522" to "GreenGo Tek",
        "523" to "VPG",
        "52C" to "GEM subsidiary of Polaris Inc.",
        "537" to "Azure Dynamics Transit Connect Electric",
        "538" to "Zero Motorcycles",
        "53G" to "Coda Automotive",
        "53T" to "Think North America in Elkhart, IN",
        "546" to "EBR",
        "54C" to "Winnebago Industries travel trailer",
        "54D" to "Isuzu & Chevrolet commercial trucks built by Spartan Motors/The Shyft Group",
        "54F" to "Rosenbauer",
        "55S" to "Mercedes-Benz car",
        "56K" to "Indian Motorcycle International, LLC",
        "573" to "Grand Design RV",
        "57C" to "Maurer Manufacturing",
        "57R" to "Oreion Motors",
        "57S" to "Lightning Motors Corp.",
        "57W" to "Mobility Ventures",
        "57X" to "Polaris Slingshot",
        "58A" to "Lexus car",
        "5A4" to "Load Rite Trailers Inc.",
        "5AS" to "Global Electric Motorcars (GEM) 1999-2011",
        "5AX" to "Armor Chassis",
        "5B4" to "Workhorse Custom Chassis, LLC incomplete vehicle",
        "5BP" to "Solectria",
        "5BZ" to "Nissan \"bus\"",
        "5CD" to "Indian Motorcycle Company of America",
        "5CX" to "Shelby Series 1",
        "5DF" to "Thomas Dennis Company LLC",
        "5DG" to "Terex Advance Mixer",
        "5EH" to "Excelsior-Henderson Motorcycle",
        "5EO" to "Cottrell",
        "5FC" to "Columbia Vehicle Group (Columbia, Tomberlin",
        "5FN" to "Honda MPV/SUV",
        "5FP" to "Honda truck",
        "5FR" to "Acura SUV",
        "5FT" to "Feeling Trailers",
        "5FY" to "New Flyer",
        "5G8" to "Holden Volt",
        "5GA" to "Buick MPV/SUV",
        "5GD" to "Daewoo G2X",
        "5GN" to "Hummer H3T",
        "5GR" to "Hummer H2",
        "5GT" to "Hummer H3",
        "5GZ" to "Saturn MPV/SUV",
        "5HD" to "Harley-Davidson for export markets",
        "5HT" to "Heil Trailer",
        "5J5" to "Club Car",
        "5J6" to "Honda SUV",
        "5J8" to "Acura SUV",
        "5KB" to "Honda car",
        "5KJ" to "Western Star Trucks truck",
        "5KK" to "Western Star Trucks truck",
        "5KM" to "Vento Motorcycles",
        "5KT" to "Karavan Trailers",
        "5L1" to "Lincoln SUV - Limousine",
        "5L5" to "American IronHorse Motorcycle",
        "5LD" to "Ford & Lincoln incomplete vehicle – limousine",
        "5LM" to "Lincoln SUV",
        "5LT" to "Lincoln truck",
        "5MZ" to "Buell Motorcycle Company for export markets",
        "5N1" to "Nissan & Infiniti SUV",
        "5N3" to "Infiniti SUV",
        "5NH" to "Forest River",
        "5NM" to "Hyundai SUV",
        "5NP" to "Hyundai car",
        "5NT" to "Hyundai truck",
        "5PV" to "Hino incomplete vehicle",
        "5RJ" to "Android Industries LLC",
        "5RX" to "Heartland Recreational Vehicles",
        "5S3" to "Saab 9-7X",
        "5SA" to "Suzuki Manufacturing of America Corp.",
        "5SX" to "American LaFrance incomplete vehicle",
        "5TB" to "Toyota truck",
        "5TD" to "Toyota MPV/SUV & Lexus TX",
        "5TE" to "Toyota truck",
        "5TF" to "Toyota truck",
        "5TU" to "Construction Trailer Specialist",
        "5UM" to "BMW M car",
        "5UX" to "BMW SUV",
        "5V8" to "Vanguard National",
        "5VC" to "Autocar incomplete vehicle",
        "5VF" to "American Electric Vehicle Company",
        "5VP" to "Victory Motorcycles",
        "5WE" to "IC Bus incomplete vehicle",
        "5XX" to "Kia car",
        "5XY" to "Kia/Hyundai SUV",
        "5Y2" to "Pontiac Vibe",
        "5Y4" to "Yamaha Motor Motor Mfg. Corp. of America",
        "5YA" to "Indian Motorcycle Company",
        "5YF" to "Toyota car",
        "5YJ" to "Tesla, Inc. passenger car",
        "5YM" to "BMW M SUV",
        "5YN" to "Cruise Car, Inc.",
        "5Z6" to "Suzuki Equator",
        "5ZT" to "Forest River",
        "5ZU" to "Greenkraft",
        "6AB" to "MAN Australia",
        "6AM" to "Jayco Corp.",
        "6F1" to "Ford",
        "6F2" to "Iveco Trucks Australia Ltd.",
        "6F4" to "Nissan Motor Company Australia",
        "6F5" to "Kenworth Australia",
        "6FM" to "Mack Trucks Australia",
        "6FP" to "Ford Australia",
        "6G1" to "General Motors-Holden (post Nov 2002) & Chevrolet & Vauxhall Monaro & VXR8",
        "6G2" to "Pontiac Australia",
        "6G3" to "General Motors Chevrolet Caprice PPV & SS performance sedan 2014-2017",
        "6H8" to "General Motors-Holden",
        "6KT" to "BCI Bus",
        "6MM" to "Mitsubishi Motors Australia",
        "6MP" to "Mercury Capri 1991-1994",
        "6T1" to "Toyota Motor Corporation Australia",
        "6T9" to "Privately Imported car (VIN issued by Victoria) or Trailer in Australia",
        "6U9" to "Privately Imported car in Australia",
        "6ZZ" to "Privately Imported car in Australia",
        "722" to "Isuzu North America Corp.",
        "7A1" to "Mitsubishi New Zealand",
        "7A3" to "Honda New Zealand",
        "7A4" to "Toyota New Zealand",
        "7A5" to "Ford New Zealand",
        "7A7" to "Nissan New Zealand",
        "7AB" to "MAN New Zealand",
        "7B2" to "Nissan Diesel bus New Zealand",
        "7F7" to "Arcimoto, Inc.",
        "7FA" to "Honda SUV",
        "7FC" to "Rivian truck",
        "7G0" to "Faraday Future",
        "7G2" to "Tesla, Inc. truck",
        "7GZ" to "GMC incomplete vehicles",
        "7H4" to "Hino truck",
        "7H8" to "Cenntro Electric Group Limited low-speed vehicle",
        "7JD" to "Volvo Cars SUV",
        "7JR" to "Volvo Cars passenger car",
        "7JZ" to "Proterra From mid-2019 on",
        "7KG" to "Vanderhall Motor Works",
        "7KY" to "Dorsey",
        "7MM" to "Mazda SUV",
        "7MU" to "Toyota SUV",
        "7MW" to "Cenntro Electric Group Limited truck",
        "7MZ" to "HDK electric vehicles",
        "7NA" to "Navistar Defense",
        "7NY" to "Lordstown Motors",
        "7PD" to "Rivian SUV",
        "7RZ" to "Electric Last Mile Solutions",
        "7SA" to "Tesla, Inc. (US-built MPVs (e.g. Model X, Model Y)",
        "7SU" to "Blue Arc electric trucks",
        "7SV" to "Toyota SUV",
        "7SX" to "Global Electric Motorcars (WAEV) 2022-",
        "7SY" to "Polestar SUV",
        "7TN" to "Canoo",
        "7UU" to "Lucid Motors MPV/SUV",
        "7UZ" to "Kaufman Trailers",
        "7VV" to "Ree Automotive",
        "7WE" to "Bollinger Motors incomplete vehicle",
        "7YA" to "Hyundai MPV/SUV",
        "7Z0" to "Zoox",
        "829" to "Industrias Quantum Motors S.A.",
        "8A1" to "Renault Argentina",
        "8A3" to "Scania Argentina",
        "8AB" to "Mercedes Benz truck & bus",
        "8AC" to "Mercedes Benz vans",
        "8AD" to "Peugeot Argentina",
        "8AE" to "Peugeot van",
        "8AF" to "Ford Argentina",
        "8AG" to "Chevrolet Argentina",
        "8AJ" to "Toyota Argentina",
        "8AK" to "Suzuki Argentina",
        "8AN" to "Nissan Argentina",
        "8AP" to "Fiat Argentina",
        "8AT" to "Iveco Argentina",
        "8AW" to "Volkswagen Argentina",
        "8BB" to "Agrale Argentina S.A.",
        "8BC" to "Citroën Argentina",
        "8BN" to "Mercedes-Benz incomplete vehicle",
        "8BR" to "Mercedes-Benz \"bus\" (van with more than 3 rows of seats",
        "8BT" to "Mercedes-Benz MPV (van with 2 or 3 rows of seats",
        "8BU" to "Mercedes-Benz truck (cargo van with 1 row of seats",
        "8C3" to "Honda car/SUV",
        "8CH" to "Honda motorcycle",
        "8G1" to "Automotores Franco Chilena S.A. Renault",
        "8GD" to "Automotores Franco Chilena S.A. Peugeot",
        "8GG" to "Chevrolet Chile",
        "8L4" to "Great Wall Motors",
        "8LD" to "General Motors OBB - Chevrolet Ecuador",
        "8LF" to "Maresa",
        "8LG" to "Aymesa",
        "8XD" to "Ford Motor Venezuela",
        "8XJ" to "Mack de Venezuela C.A.",
        "8XV" to "Iveco Venezuela C.A.",
        "8Z1" to "General Motors Venezolana C.A.",
        "92H" to "Origem Brazil",
        "932" to "Harley-Davidson Brazil",
        "935" to "Citroën Brazil",
        "936" to "Peugeot Brazil",
        "937" to "Dodge Dakota",
        "93C" to "Chevrolet SUV [Tracker] or pickup [Tornado, Montana, S10]",
        "93H" to "Honda Brazil car/SUV",
        "93K" to "Volvo Trucks",
        "93P" to "Volare",
        "93R" to "Toyota Brazil",
        "93S" to "Navistar International",
        "93U" to "Audi Brazil 1999–2006",
        "93V" to "Navistar International",
        "93W" to "Fiat Ducato",
        "93X" to "Souza Ramos – Mitsubishi Motors / Suzuki Jimny",
        "93Y" to "Renault Brazil",
        "93Z" to "Iveco",
        "94D" to "Nissan Brazil",
        "94N" to "RWM Brazil",
        "94T" to "Troller Veículos Especiais",
        "953" to "VW Truck & Bus / MAN Truck & Bus",
        "95P" to "CAOA Hyundai & CAOA Chery",
        "95V" to "BMW motorcycles assembled by Dafra Motos 2009–2016",
        "95Z" to "Buell Motorcycle Company assembled by Harley-Davidson Brazil",
        "96P" to "Kawasaki",
        "97N" to "Triumph Motorcycles Ltd.",
        "988" to "Jeep, Ram [Rampage], and Fiat [Toro]",
        "98M" to "BMW car/SUV",
        "98P" to "DAF Trucks",
        "98R" to "Chery",
        "99A" to "Audi 2016-",
        "99H" to "Shineray",
        "99J" to "Jaguar Land Rover",
        "99K" to "Haojue & Kymco assembled by JTZ Indústria e Comércio de Motos",
        "99L" to "BYD",
        "99Z" to "BMW Motorrad",
        "9BD" to "Fiat Brazil & Dodge, Ram",
        "9BF" to "Ford Brazil",
        "9BG" to "Chevrolet Brazil",
        "9BH" to "Hyundai Motor Brasil",
        "9BM" to "Mercedes-Benz Brazil car, SUV, commercial truck & bus",
        "9BN" to "Mafersa",
        "9BR" to "Toyota Brazil",
        "9BS" to "Scania Brazil",
        "9BV" to "Volvo Trucks",
        "9BW" to "Volkswagen Brazil",
        "9BY" to "Agrale S.A.",
        "9C2" to "Moto Honda Da Amazonia Ltda.",
        "9C6" to "Yamaha Motor Da Amazonia Ltda.",
        "9CD" to "Suzuki (motorcycles) assembled by J. Toledo Motos do Brasil",
        "9DF" to "Puma",
        "9DW" to "Kenworth & Peterbilt trucks",
        "9EZ" to "homemade or handbuilt vehicles",
        "9FB" to "Renault Colombia",
        "9FC" to "Compañía Colombiana Automotriz S.A.",
        "9GA" to "Chevrolet Colombia",
        "9UJ" to "Chery assembled by Chery Socma S.A.",
        "9UK" to "Lifan",
        "9UT" to "Dongfeng trucks",
        "9UW" to "Kia",
        "9V7" to "Citroen",
        "9V8" to "Peugeot",
        "9VC" to "Fiat",
        "AAA" to "Audi South Africa",
        "AAK" to "FAW Vehicle Manufacturers SA (PTY) Ltd.",
        "AAM" to "MAN Automotive (South Africa) (Pty) Ltd.",
        "AAP" to "VIN restamped by South African Police Service",
        "AAV" to "Volkswagen South Africa",
        "AAW" to "Challenger Trailer Pty Ltd.",
        "ABJ" to "Mitsubishi Fuso",
        "ABM" to "BMW Southern Africa",
        "AC5" to "Hyundai Automotive South Africa",
        "ACV" to "Isuzu Motors South Africa 2018-",
        "ADB" to "Mercedes-Benz South Africa car",
        "ADD" to "UD Trucks Southern Africa (Pty) Ltd.",
        "ADM" to "General Motors South Africa",
        "ADN" to "Nissan South Africa (Pty) Ltd.",
        "ADR" to "Renault Sandero",
        "ADX" to "Tata Automobile Corporation (SA) Ltd.",
        "AFA" to "Ford Motor Company of Southern Africa & Samcor",
        "AFB" to "Mazda BT-50",
        "AFD" to "BAIC Automotive South Africa",
        "AFZ" to "Fiat Auto South Africa",
        "AHH" to "Hino South Africa",
        "AHM" to "Honda Ballade",
        "AHT" to "Toyota South Africa Motors (Pty.) Ltd.",
        "BR1" to "Mercedes-Benz Algeria",
        "BRY" to "FIAT Algeria",
        "BUK" to "Kiira Motors Corporation, Uganda",
        "CA3" to "MCV bus",
        "DDY" to "Geyushi Motors (bus",
        "EAA" to "Aurus Motors",
        "EAN" to "Evolute",
        "EAU" to "Elektromobili Manufacturing Rus - EVM",
        "EBE" to "Sollers-Auto",
        "EBZ" to "Nizhekotrans bus",
        "ECE" to "XCITE",
        "ECW" to "Trans-Alfa bus",
        "H0D" to "Taizhou Qianxin Vehicle Co., Ltd.",
        "H0G" to "Wisdom (Fujian) Motor Co., Ltd.",
        "HA0" to "Wuxi Sundiro Electric Vehicle Co., Ltd.",
        "HA6" to "Niu Technologies",
        "HA7" to "Jinan Qingqi KR Motors Co., Ltd.",
        "HES" to "smart Automobile Co., Ltd.",
        "HGL" to "Farizon Auto van",
        "HGX" to "Wuling Motors commercial vehicle",
        "HHZ" to "Huazi Automobile",
        "HJ4" to "BAW car",
        "HJN" to "Firefly",
        "HJR" to "Chery Commercial Vehicle (Anhui) Co., Ltd. Jetour",
        "HJZ" to "Juzhen Chengshi van",
        "HL4" to "Zhejiang Morini Vehicle Co., Ltd.",
        "HLX" to "Li Auto",
        "HRV" to "Beijing Henrey Automobile Technology Co., Ltd.",
        "HVW" to "Volkswagen Anhui",
        "HWM" to "WM Motor Technology Co., Ltd.",
        "HXM" to "Xiaomi",
        "HZ2" to "Taizhou Zhilong Technology Co., Ltd",
        "J81" to "Chevrolet/Geo car",
        "J87" to "Pontiac/Asüna car",
        "J8B" to "Chevrolet commercial trucks",
        "J8C" to "Chevrolet commercial trucks",
        "J8D" to "GMC commercial trucks",
        "J8T" to "GMC commercial trucks",
        "J8Z" to "Chevrolet LUV pickup truck",
        "JA3" to "Mitsubishi car",
        "JA4" to "Mitsubishi MPV/SUV (for North America) & Nissan Rogue PHEV '26",
        "JA7" to "Mitsubishi truck",
        "JAA" to "Isuzu truck, Holden Rodeo TF, Opel Campo, Bedford/Vauxhall Brava pickup",
        "JAB" to "Isuzu car",
        "JAC" to "Isuzu SUV, Opel/Vauxhall Monterey & Holden Jackaroo/Monterey",
        "JAE" to "Acura SLX",
        "JAL" to "Isuzu commercial trucks & Chevrolet commercial trucks",
        "JAM" to "Isuzu commercial trucks",
        "JB3" to "Dodge car",
        "JB4" to "Dodge MPV/SUV",
        "JB7" to "Dodge truck",
        "JC0" to "Ford brand cars",
        "JC1" to "Fiat 124 Spider",
        "JC2" to "Ford Courier",
        "JD1" to "Daihatsu car",
        "JD2" to "Daihatsu SUV",
        "JD4" to "Daihatsu truck",
        "JDA" to "Daihatsu, Subaru Justy",
        "JE3" to "Eagle car",
        "JE4" to "Mitsubishi Motors",
        "JF1" to "Subaru car",
        "JF2" to "Subaru SUV",
        "JF3" to "Subaru truck",
        "JF4" to "Saab 9-2X",
        "JG1" to "Chevrolet/Geo car",
        "JG2" to "Pontiac car",
        "JG7" to "Pontiac/Asuna car",
        "JGC" to "Chevrolet/Geo SUV",
        "JGT" to "GMC SUV",
        "JH1" to "Honda truck",
        "JH2" to "Honda motorcycle/ATV",
        "JH3" to "Honda ATV",
        "JH4" to "Acura car",
        "JH6" to "Hino incomplete vehicle",
        "JHA" to "Hino truck",
        "JHB" to "Hino incomplete vehicle",
        "JHD" to "Hino",
        "JHF" to "Hino",
        "JHH" to "Hino incomplete vehicle",
        "JHL" to "Honda MPV/SUV",
        "JHM" to "Honda car",
        "JJ3" to "Chrysler brand car",
        "JK8" to "Suzuki QUV620F UTV",
        "JKA" to "Kawasaki",
        "JKB" to "Kawasaki",
        "JKM" to "Mitsuoka",
        "JKS" to "Suzuki Marauder 1600/Boulevard M95 motorcycle",
        "JL5" to "Mitsubishi Fuso Truck & Bus Corp.",
        "JL6" to "Mitsubishi Fuso Truck & Bus Corp.",
        "JL7" to "Mitsubishi Fuso Truck & Bus Corp.",
        "JLB" to "Mitsubishi Fuso Truck & Bus Corp.",
        "JLF" to "Mitsubishi Fuso Truck & Bus Corp.",
        "JLS" to "Sterling Truck 360",
        "JM0" to "Mazda for Oceania export",
        "JM1" to "Mazda car",
        "JM2" to "Mazda truck",
        "JM3" to "Mazda MPV/SUV",
        "JM4" to "Mazda",
        "JM6" to "Mazda",
        "JM7" to "Mazda",
        "JMA" to "Mitsubishi Motors (right-hand drive) for Europe",
        "JMB" to "Mitsubishi Motors (left-hand drive) for Europe",
        "JMF" to "Mitsubishi Motors for Australia (including Mitsubishi Express",
        "JMP" to "Mitsubishi Motors",
        "JMR" to "Mitsubishi Motors",
        "JMY" to "Mitsubishi Motors (left-hand drive) for South America & Middle East",
        "JMZ" to "Mazda for Europe export & Mazda 2",
        "JN1" to "Nissan car & Infiniti car",
        "JN3" to "Nissan incomplete vehicle",
        "JN6" to "Nissan truck/van & Mitsubishi Fuso Canter Van",
        "JN8" to "Nissan MPV/SUV & Infiniti SUV",
        "JNA" to "Nissan Diesel/UD Trucks incomplete vehicle",
        "JNC" to "Nissan Diesel/UD Trucks",
        "JNE" to "Nissan Diesel/UD Trucks truck",
        "JNK" to "Infiniti car",
        "JNR" to "Infiniti SUV",
        "JNX" to "Infiniti incomplete vehicle",
        "JP3" to "Plymouth car",
        "JP4" to "Plymouth MPV/SUV",
        "JP7" to "Plymouth truck",
        "JPC" to "Nissan Diesel/UD Trucks",
        "JR2" to "Isuzu Oasis",
        "JS1" to "Suzuki motorcycle & Kawasaki KLX400S/KLX400SR motorcycle",
        "JS2" to "Suzuki car",
        "JS3" to "Suzuki SUV",
        "JS4" to "Suzuki truck",
        "JSA" to "Suzuki ATV & '03 Kawasaki KFX400 ATV",
        "JSK" to "Kawasaki KLX125/KLX125L motorcycle",
        "JSL" to "'04-'06 Kawasaki KFX400 ATV",
        "JST" to "Suzuki Across SUV",
        "JT1" to "Toyota van",
        "JT2" to "Toyota car",
        "JT3" to "Toyota MPV/SUV",
        "JT4" to "Toyota truck/van",
        "JT5" to "Toyota incomplete vehicle",
        "JT6" to "Lexus SUV",
        "JT7" to "Toyota bus/van",
        "JT8" to "Lexus car",
        "JTB" to "Toyota bus",
        "JTD" to "Toyota car",
        "JTE" to "Toyota MPV/SUV",
        "JTF" to "Toyota van/truck",
        "JTG" to "Toyota MPV/bus",
        "JTH" to "Lexus car",
        "JTJ" to "Lexus SUV",
        "JTK" to "Toyota car",
        "JTL" to "Toyota SUV",
        "JTM" to "Toyota SUV, Subaru Solterra",
        "JTN" to "Toyota car",
        "JTP" to "Toyota SUV",
        "JW6" to "Mitsubishi Fuso division of Mitsubishi Motors",
        "JY3" to "Yamaha 3-wheel ATV",
        "JY4" to "Yamaha 4-wheel ATV",
        "JYA" to "Yamaha motorcycles",
        "JYE" to "Yamaha snowmobile",
        "KF3" to "Merkavim",
        "KF6" to "Automotive Industries, Ltd.",
        "KL1" to "GM Daewoo/GM Korea",
        "KL2" to "Daewoo/GM Daewoo",
        "KL3" to "GM Daewoo/GM Korea",
        "KL4" to "GM Korea",
        "KL5" to "GM Daewoo",
        "KL6" to "GM Daewoo",
        "KL7" to "GM Daewoo/GM Korea (Chevrolet MPV/SUV (Post-2000)",
        "KL8" to "GM Daewoo/GM Korea (Chevrolet car from Changwon plant (Spark)",
        "KLA" to "Daewoo/GM Daewoo/GM Korea (Chevrolet/Alpheon) from Bupyeong & Kunsan plants",
        "KLP" to "CT & T United",
        "KLT" to "Tata Daewoo",
        "KLU" to "Tata Daewoo",
        "KLY" to "Daewoo/GM Daewoo/GM Korea (Chevrolet) from Changwon plant",
        "KM1" to "Hyosung Motors",
        "KM4" to "Hyosung Motors/S & T Motors/KR Motors",
        "KM8" to "Hyundai SUV",
        "KMC" to "Hyundai commercial truck",
        "KME" to "Hyundai commercial truck",
        "KMF" to "Hyundai van & commercial truck & Bering Truck",
        "KMH" to "Hyundai car & Mexican market Dodges",
        "KMJ" to "Hyundai minibus/bus",
        "KMT" to "Genesis Motor car",
        "KMU" to "Genesis Motor SUV",
        "KMX" to "Hyundai Galloper SUV",
        "KMY" to "Daelim Motor Company, Ltd/DNA Motors Co., Ltd.",
        "KN1" to "Asia Motors",
        "KN2" to "Asia Motors",
        "KNA" to "Kia car",
        "KNC" to "Kia truck",
        "KND" to "Kia MPV/SUV & Hyundai Entourage",
        "KNE" to "Kia for Europe export",
        "KNF" to "Kia, special vehicles",
        "KNG" to "Kia minibus/bus",
        "KNJ" to "Ford Festiva & Aspire",
        "KNM" to "Renault Korea Co., Ltd.",
        "KPA" to "SsangYong/KG Mobility (KGM) pickup",
        "KPB" to "SsangYong car",
        "KPD" to "SsangYong TransStar",
        "KPH" to "Mitsubishi Precis",
        "KPT" to "SsangYong/KG Mobility (KGM) SUV/MPV",
        "L10" to "Geely Emgrand",
        "L1K" to "Chongqing Hengtong Bus Co., Ltd.",
        "L1N" to "XPeng Motors",
        "L2B" to "Jiangsu Baodiao Locomotive Co., Ltd.",
        "L2C" to "Chery Jaguar Land Rover",
        "L37" to "Huzhou Daixi Zhenhua Technology Trade Co., Ltd.",
        "L3H" to "Shanxi Victory Automobile Manufacturing Co., Ltd.",
        "L4B" to "Xingyue Group",
        "L4F" to "Suzhou Eagle Electric Vehicle Manufacturing Co., Ltd.",
        "L4H" to "Ningbo Longjia Motorcycle Co., Ltd.",
        "L4S" to "Zhejiang Xingyue Vehicle Co Ltd.",
        "L5C" to "Zhejiang Kangdi Vehicles Co., Ltd.",
        "L5E" to "Zoomlion Heavy Industry Science & Technology Co., Ltd.",
        "L5K" to "Zhejiang Yongkang Easy Vehicle",
        "L5N" to "Zhejiang Taotao",
        "L5Y" to "Taizhou Zhongneng Motorcycle Co. Ltd.",
        "L66" to "Zhuhai Granton Bus and Coach Co. Ltd.",
        "L6F" to "Shandong Liangzi Power Co. Ltd.",
        "L6J" to "Zhejiang Kayo Motor Co. Ltd.",
        "L6K" to "Shanghai Howhit Machinery Manufacture Co. Ltd.",
        "L6T" to "Geely, Lynk & Co, Zeekr",
        "L82" to "Baotian",
        "L85" to "Zhejiang Yongkang Huabao Electric Appliance",
        "L8A" to "Jinhua Youngman Automobile Manufacturing Co., Ltd.",
        "L8X" to "Zhejiang Summit Huawin Motorcycle",
        "L8Y" to "Zhejiang Jonway Motorcycle Manufacturing Co., Ltd.",
        "L9G" to "Zhuhai Guangtong Automobile Co., Ltd.",
        "L9N" to "Zhejiang Taotao Vehicles Co., Ltd.",
        "LA6" to "Xiamen King Long United Automotive Industry Co., Ltd.",
        "LA7" to "Radar Auto",
        "LA8" to "Anhui Ankai",
        "LAA" to "Shanghai Jialing Vehicle Co., Ltd.",
        "LAE" to "Jinan Qingqi Motorcycle",
        "LAL" to "Sundiro Honda Motorcycle",
        "LAN" to "Changzhou Yamasaki Motorcycle",
        "LAP" to "Zhuzhou Nanfang Motorcycle Co., Ltd.",
        "LAT" to "Luoyang Northern Ek Chor Motorcycle Co., Ltd.",
        "LB1" to "Fujian Benz",
        "LB2" to "Geely Motorcycles",
        "LB3" to "Zhejiang Geely Holding Group",
        "LB4" to "Chongqing Yinxiang Motorcycle Group Co., Ltd.",
        "LB5" to "Foshan City Fosti Motorcycle Co., Ltd.",
        "LB7" to "Tibet New Summit Motorcycle Co., Ltd.",
        "LBB" to "Zhejiang Qianjiang Motorcycle",
        "LBE" to "Beijing Hyundai",
        "LBM" to "Zongshen Piaggio",
        "LBP" to "Chongqing Jianshe Yamaha Motor Co. Ltd.",
        "LBV" to "BMW Brilliance",
        "LBX" to "Jiangsu Kinroad Xintian Motorcycle Manufacture Co. Ltd.",
        "LBZ" to "Yantai Shuchi Vehicle Co., Ltd.",
        "LC0" to "BYD Auto",
        "LC2" to "Changzhou Kwang Yang Motor Co., Ltd.",
        "LC6" to "Changzhou Haojue Suzuki Motorcycle Co. Ltd.",
        "LCE" to "Hangzhou Chunfeng Motorcycles",
        "LCR" to "Gonow",
        "LD3" to "Guangdong Tayo Motorcycle Technology Co. (Zontes",
        "LD5" to "Benzhou Vehicle Industry Group Ltd.",
        "LDB" to "Dadi Auto",
        "LDD" to "Dandong Huanghai Automobile",
        "LDF" to "Dezhou Fulu Vehicle Co., Ltd. (motorcycles), BAW Yuanbao electric car",
        "LDK" to "FAW Bus (Dalian) Co., Ltd.",
        "LDN" to "Soueast (South East (Fujian) Motor Co., Ltd.) including Mitsubishi",
        "LDP" to "Dongfeng, Dongfeng Fengshen (Aeolus), Voyah, Renault City K-ZE/Venucia e30",
        "LDY" to "Zhongtong Bus Holding Co. Ltd.",
        "LE8" to "Guangzhou Panyu Hua'Nan Motors Industry Co. Ltd.",
        "LEC" to "Tianjin Qingyuan Electric Vehicle Co., Ltd.",
        "LEF" to "Jiangling Motors Corporation Ltd.",
        "LEH" to "Zhejiang Riya Motorcycle Co. Ltd.",
        "LET" to "Jiangling-Isuzu Motors, China",
        "LEW" to "Dongfeng commercial vehicle",
        "LF3" to "Lifan Motorcycle",
        "LFA" to "Ford Lio Ho Motor Co Ltd. old designation",
        "LFB" to "FAW Group (Bestune, Hongqi) & Mazda made under license by FAW",
        "LFF" to "Zhejiang Taizhou Wangye Power Co., Ltd.",
        "LFG" to "Taizhou Chuanl Motorcycle Manufacturing",
        "LFJ" to "Fujian Motors Group",
        "LFM" to "FAW Toyota Motor",
        "LFN" to "FAW Bus (Wuxi) Co., Ltd.",
        "LFP" to "FAW Car, Bestune, Hongqi (passenger vehicles) & Mazda made under license by FAW",
        "LFT" to "FAW",
        "LFU" to "Lifeng Group Co., Ltd.",
        "LFV" to "FAW-Volkswagen",
        "LFW" to "FAW JieFang",
        "LFX" to "Sany Heavy Industry",
        "LFY" to "Changshu Light Motorcycle Factory",
        "LFZ" to "Leapmotor",
        "LG6" to "Dayun Group",
        "LGA" to "Dongfeng Commercial Vehicle Co., Ltd. trucks",
        "LGB" to "Dongfeng Commercial Vehicle Co., Ltd.",
        "LGC" to "Dongfeng Commercial Vehicle Co., Ltd. bus chassis",
        "LGD" to "Dongfeng Commercial Vehicle Co., Ltd.",
        "LGF" to "Dongfeng Commercial Vehicle Co., Ltd. bus chassis",
        "LGG" to "Dongfeng Liuzhou Motor",
        "LGJ" to "Dongfeng Fengshen",
        "LGL" to "Guilin Daewoo",
        "LGV" to "Heshan Guoji Nanlian Motorcycle Industry Co., Ltd.",
        "LGW" to "Great Wall Motor",
        "LGX" to "BYD Auto",
        "LGZ" to "Guangzhou Denway Bus",
        "LH0" to "WM Motor Technology Co., Ltd.",
        "LH1" to "FAW-Haima, China",
        "LHA" to "Shuanghuan Auto",
        "LHB" to "Beijing Automotive Industry Holding",
        "LHG" to "GAC Honda",
        "LHJ" to "Chongqing Astronautic Bashan Motorcycle Manufacturing Co., Ltd.",
        "LHM" to "Dongfeng Renault Automobile Co.",
        "LHW" to "CRRC Electric Vehicle Co., Ltd.",
        "LJ1" to "Nio, Inc.",
        "LJ4" to "Shanghai Jmstar Motorcycle Co., Ltd.",
        "LJ5" to "Cixi Kingring Motorcycle Co., Ltd.",
        "LJ8" to "Zotye Auto",
        "LJC" to "Jincheng Corporation",
        "LJD" to "Yueda Kia (previously Dongfeng Yueda Kia) (Kia, Horki) & Human Horizons - HiPhi",
        "LJM" to "Sunlong",
        "LJN" to "Zhengzhou Nissan",
        "LJR" to "CIMC Vehicles Group",
        "LJS" to "Yaxing Coach, Asiastar Bus",
        "LJU" to "Lotus Technology",
        "LJV" to "Sinotruk Chengdu Wangpai Commercial Vehicle Co., Ltd.",
        "LJW" to "JMC Landwind",
        "LJX" to "JMC Ford",
        "LK2" to "Anhui JAC Bus",
        "LK6" to "SAIC-GM-Wuling (Wuling, Baojun) microcars and other vehicles",
        "LK8" to "Zhejiang Yule New Energy Automobile Technology Co., Ltd.",
        "LKC" to "BAIC commercial vehicles, previously Changhe",
        "LKG" to "Youngman Lotus Automobile Co., Ltd.",
        "LKH" to "Hafei Motor",
        "LKL" to "Higer Bus",
        "LKT" to "Yunnan Lifan Junma Vehicle Co., Ltd. commercial vehicles",
        "LL0" to "Sanmen County Yongfu Machine Co., Ltd.",
        "LL2" to "WM Motor Technology Co., Ltd.",
        "LL3" to "Xiamen Golden Dragon Bus Co. Ltd.",
        "LL6" to "GAC Mitsubishi Motors Co., Ltd.",
        "LL8" to "Jiangsu Linhai Yamaha Motor Co., Ltd.",
        "LLC" to "Loncin Motor Co., Ltd.",
        "LLJ" to "Jiangsu Xinling Motorcycle Fabricate Co., Ltd.",
        "LLN" to "Qoros",
        "LLP" to "Zhejiang Jiajue Motorcycle Manufacturing Co., Ltd.",
        "LLU" to "Dongfeng Fengxing Jingyi",
        "LLV" to "Lifan, Maple (owned by Geely), Livan Automotive",
        "LLX" to "Yudo Auto",
        "LM0" to "Wangye Holdings Co., Ltd.",
        "LM1" to "Tai Ling Motor Co Ltd. old designation (Suzuki motorcycle",
        "LM4" to "Tai Ling Motor Co Ltd. old designation (Suzuki ATV",
        "LM6" to "SWM",
        "LM8" to "Seres (formerly SF Motors), AITO",
        "LMC" to "Suzuki Hong Kong",
        "LME" to "Skyworth (formerly Skywell), Elaris Beo",
        "LMF" to "Jiangmen Zhongyu Motor Co., Ltd.",
        "LMG" to "GAC Motor, Trumpchi, Dodge Attitude",
        "LMH" to "Jiangsu Guowei Motor Co., Ltd.",
        "LMP" to "Geely Sichuan Commercial Vehicle Co., Ltd.",
        "LMV" to "XPeng Motors G3",
        "LMW" to "GAC Group, Dodge Journey",
        "LMX" to "Forthing",
        "LN1" to "Tai Ling Motor Co Ltd. old designation (Suzuki motorcycle",
        "LNA" to "GAC Aion New Energy Automobile Co., Ltd., Hycan",
        "LNB" to "BAIC Motor (Senova, Weiwang, Huansu) & Arcfox & Xiaomi SU7 built by BAIC",
        "LNE" to "Zhejiang CRRC Electric Vehicle Co., Ltd.",
        "LNN" to "Chery Automobile, Omoda, Jaecoo",
        "LNP" to "NAC MG UK Limited & Nanjing Fiat Automobile",
        "LNV" to "Naveco",
        "LNX" to "Dongfeng Liuzhou Motor",
        "LNY" to "Yuejin",
        "LP6" to "Guangzhou Panyu Haojian Motorcycle Industry Co., Ltd.",
        "LPA" to "Changan PSA",
        "LPE" to "BYD Auto",
        "LPR" to "Yamaha Motor Taiwan Co. Ltd. old designation",
        "LPS" to "Polestar",
        "LR4" to "Yadi Technology Group",
        "LR6" to "Guangzhou Dayun Vehicle Co., Ltd.",
        "LRB" to "SAIC-General Motors",
        "LRD" to "Beijing Foton Daimler Automotive Co., Ltd. Auman trucks",
        "LRE" to "SAIC-General Motors",
        "LRP" to "Chongqing Rato Power Co. Ltd.",
        "LRR" to "Ningbo Longjia Power Technology Co., Ltd.",
        "LRW" to "Tesla, Inc.",
        "LS3" to "Hejia New Energy Vehicle Co., Ltd",
        "LS4" to "Changan Automobile",
        "LS5" to "Changan Automobile (car) & Changan Suzuki",
        "LS6" to "Changan Automobile & Deepal Automobile & Avatr",
        "LS7" to "JMC Heavy Duty Truck Co., Ltd.",
        "LS8" to "Henan Shaolin Auto Co., Ltd.",
        "LSC" to "Changan Automobile",
        "LSF" to "SAIC Maxus & Chevrolet S10 Max & Shanghai Sunwin Bus Corporation",
        "LSG" to "SAIC-General Motors",
        "LSH" to "SAIC Maxus van & Chevrolet Express Max",
        "LSJ" to "SAIC MG & SAIC Roewe & IM Motors & Rising Auto",
        "LSK" to "SAIC Maxus",
        "LSV" to "SAIC-Volkswagen",
        "LSY" to "Brilliance (Jinbei, Zhonghua) & Jinbei GM",
        "LT1" to "Yangzhou Tonghua Semi-Trailer Co., Ltd.",
        "LTA" to "ZX Auto",
        "LTN" to "Soueast-built Chrysler & Dodge vehicles",
        "LTP" to "National Electric Vehicle Sweden AB",
        "LTV" to "FAW Toyota",
        "LTW" to "Zhejiang Dianka Automobile Technology Co. Ltd.",
        "LUC" to "Honda Automobile",
        "LUD" to "Dongfeng Nissan Diesel Motor Co Ltd.",
        "LUG" to "Qiantu Motor",
        "LUJ" to "Zhejiang Shanqi Tianying Vehicle Industry Co., Ltd.",
        "LUR" to "Chery Automobile, iCar",
        "LUX" to "Dongfeng Yulon Motor Co. Ltd.",
        "LUZ" to "Hozon Auto New Energy Automobile Co., Ltd.",
        "LV3" to "Hengchi Automobile",
        "LV7" to "Jinan Qingqi Motorcycle",
        "LVA" to "Foton Motor",
        "LVB" to "Foton Motor truck",
        "LVC" to "Foton Motor bus",
        "LVF" to "Changhe Suzuki",
        "LVG" to "GAC Toyota",
        "LVH" to "Dongfeng Honda",
        "LVM" to "Chery Commercial Vehicle",
        "LVP" to "Dongfeng Sokon Motor Company",
        "LVR" to "Changan Mazda",
        "LVS" to "Changan Ford(Ford, Lincoln) & Changan Ford Mazda & Volvo S40 and S80L",
        "LVT" to "Chery Automobile, Exeed, Jetour, Soueast",
        "LVU" to "Chery Automobile, Jetour",
        "LVV" to "Chery Automobile, Omoda, Jaecoo",
        "LVX" to "Aiways Automobiles Company Ltd",
        "LVY" to "Volvo Cars Daqing factory",
        "LVZ" to "Dongfeng Sokon Motor Company",
        "LW4" to "Li Auto",
        "LWB" to "Wuyang Honda Motorcycle (Guangzhou) Co., Ltd.",
        "LWE" to "Yangtse Motor Group",
        "LWG" to "Chongqing Huansong Industries (Group) Co., Ltd.",
        "LWL" to "Qingling Isuzu",
        "LWM" to "Chongqing Wonjan Motorcycle Co., Ltd.",
        "LWV" to "GAC Fiat Chrysler Automobiles",
        "LWX" to "Shanghai Wanxiang Automobile Manufacturing Co., Ltd.",
        "LX6" to "Jiangmen City Huari Group Co. Ltd.",
        "LX8" to "Chongqing Xgjao (Xinganjue) Motorcycle Co Ltd.",
        "LXA" to "Jiangmen Qipai Motorcycle Co., Ltd.",
        "LXD" to "Ningbo Dongfang Lingyun Vehicle Made Co., Ltd.",
        "LXG" to "Xuzhou Construction Machinery Group Co., Ltd.",
        "LXK" to "Shanghai Meitian Motorcycle Co., Ltd.",
        "LXM" to "Xiamen Xiashing Motorcycle Co., Ltd.",
        "LXN" to "Link Tour",
        "LXV" to "Beijing Borgward Automotive Co., Ltd.",
        "LXW" to "JMC - Ford",
        "LXY" to "Chongqing Shineray Motorcycle Co., Ltd.",
        "LY4" to "Chongqing Yingang Science & Technology Group Co., Ltd.",
        "LYB" to "Weichai (Yangzhou) Yaxing Automobile Co., Ltd.",
        "LYD" to "Taizhou City Kaitong Motorcycle Co., Ltd.",
        "LYJ" to "Beijing ZhongdaYanjing Auto Co., Ltd.",
        "LYM" to "Zhuzhou Jianshe Yamaha Motorcycle Co., Ltd.",
        "LYS" to "Nanjing Vmoto Manufacturing Co. Ltd.",
        "LYU" to "Huansu",
        "LYV" to "Volvo Cars Chengdu factory & Luqiao factory",
        "LZ0" to "Shandong Wuzheng Group Co., Ltd.",
        "LZ4" to "Jiangsu Linzhi Shangyang Group Co Ltd.",
        "LZE" to "Isuzu Guangzhou, China",
        "LZF" to "SAIC Iveco Hongyan (-2021), SAIC Hongyan",
        "LZG" to "Shaanxi Automobile Group",
        "LZK" to "Sinotruk (CNHTC) Huanghe bus",
        "LZL" to "Zengcheng Haili Motorcycle Ltd.",
        "LZM" to "MAN China",
        "LZP" to "Zhongshan Guochi Motorcycle",
        "LZS" to "Zongshen, Electra Meccanica Vehicles Corp.",
        "LZU" to "Guangzhou Isuzu Bus",
        "LZW" to "SAIC-GM-Wuling",
        "LZY" to "Yutong Bus Co., Ltd.",
        "LZZ" to "Sinotruk (CNHTC",
        "M3G" to "Isuzu Motors India",
        "M6F" to "UM Lohia Two Wheelers Private Limited",
        "MA1" to "Mahindra & Mahindra",
        "MA3" to "Maruti Suzuki India",
        "MA6" to "GM India",
        "MA7" to "Hindustan Motors Ltd. & Mitsubishi Motors & Isuzu models",
        "MA8" to "Daewoo Motor India",
        "MAA" to "India Kawasaki Motors Pvt. Ltd.",
        "MAB" to "Mahindra & Mahindra",
        "MAC" to "Mahindra & Mahindra",
        "MAH" to "Fiat India Automobiles Pvt. Ltd",
        "MAJ" to "Ford India",
        "MAK" to "Honda Cars India",
        "MAL" to "Hyundai Motor India",
        "MAN" to "Eicher Polaris Multix",
        "MAT" to "Tata Motors, Rover CityRover",
        "MB1" to "Ashok Leyland",
        "MB2" to "Hyundai Motor India",
        "MB7" to "Reva Electric Car Company/Mahindra Reva Electric Vehicles Pvt. Ltd.",
        "MB8" to "Suzuki Motorcycle India Limited",
        "MBF" to "Royal Enfield",
        "MBH" to "Suzuki (for export) & Nissan Pixo",
        "MBJ" to "Toyota Kirloskar Motor Pvt. Ltd.",
        "MBK" to "MAN Trucks India Pvt. Ltd.",
        "MBL" to "Hero MotoCorp",
        "MBR" to "Mercedes-Benz India",
        "MBU" to "Swaraj Vehicles Limited",
        "MBV" to "Premier Automobiles Ltd.",
        "MBX" to "Piaggio India",
        "MBY" to "Asia Motor Works Ltd.",
        "MC1" to "Force Motors Ltd.",
        "MC2" to "Eicher Motors Ltd./Volvo Eicher Commercial Vehicles Ltd.",
        "MC4" to "Dilip Chhabria Design Pvt Ltd.",
        "MCA" to "FCA India Automobiles Pvt. Ltd.",
        "MCB" to "GM India",
        "MCD" to "Mahindra Two Wheelers",
        "MCG" to "Atul Auto Ltd.",
        "MCL" to "International Cars And Motors Ltd.",
        "MD6" to "TVS Motor Company",
        "MD7" to "LML Ltd including Genuine Scooter Company Stella",
        "MD9" to "Shuttle Cars India",
        "MDE" to "Kinetic Engineering Limited",
        "MDH" to "Nissan Motor India Pvt Ltd.",
        "MDT" to "Kerala Automobiles Limited",
        "ME1" to "India Yamaha Motor Pvt. Ltd.",
        "ME3" to "Royal Enfield",
        "ME4" to "Honda Motorcycle and Scooter India",
        "MEC" to "Daimler India Commercial Vehicles",
        "MEE" to "Renault India Private Limited",
        "MEG" to "Harley-Davidson India",
        "MER" to "Benelli India",
        "MES" to "Mahindra Navistar",
        "MET" to "Piaggio India",
        "MEX" to "Škoda Auto Volkswagen India Pvt. Ltd. 2015 on",
        "MF3" to "PT Hyundai Motor Manufacturing Indonesia",
        "MH1" to "PT Astra Honda Motor",
        "MH3" to "PT Yamaha Indonesia Motor Mfg.",
        "MH4" to "PT Kawasaki Motor Indonesia",
        "MH8" to "PT Suzuki Indomobil Motor",
        "MHD" to "PT Indomobil Suzuki International",
        "MHF" to "PT Toyota Motor Manufacturing Indonesia",
        "MHK" to "PT Astra Daihatsu Motor (includes Toyotas",
        "MHL" to "PT Mercedes-Benz Indonesia",
        "MHR" to "Honda Indonesia (PT Honda Prospect Motor",
        "MHY" to "PT Suzuki Indomobil Motor",
        "MJB" to "GM Indonesia",
        "MK2" to "PT Mitsubishi Motors Krama Yudha Indonesia",
        "MK3" to "PT SGMW Motor Indonesia",
        "MKF" to "PT Sokonindo Automobile",
        "ML0" to "Ducati Motor (Thailand) Co., Ltd.",
        "ML3" to "Mitsubishi Motors, Dodge Colt 100 [Canada], Dodge Attitude [Mexico]",
        "ML5" to "Kawasaki Motors Enterprise Co. Ltd.",
        "MLB" to "Siam Yamaha Co Ltd.",
        "MLC" to "Thai Suzuki Motor Co., Ltd.",
        "MLE" to "Thai Yamaha Motor Co., Ltd.",
        "MLH" to "Thai Honda Manufacturing Co., Ltd.",
        "MLW" to "Sco Motor Co., Ltd.",
        "MLY" to "Harley-Davidson Thailand",
        "MMA" to "Mitsubishi Motors",
        "MMB" to "Mitsubishi Motors",
        "MMC" to "Mitsubishi Motors",
        "MMD" to "Mitsubishi Motors",
        "MME" to "Mitsubishi Motors",
        "MMF" to "BMW Manufacturing (Thailand) Co., Ltd.",
        "MML" to "MG Thailand",
        "MMM" to "Chevrolet Thailand, Holden Colorado RC pickup",
        "MMR" to "Subaru/Tan Chong Subaru Automotive (Thailand) Co. Ltd.",
        "MMS" to "Suzuki Motor (Thailand) Co., Ltd.",
        "MMT" to "Mitsubishi Motors",
        "MMU" to "Holden Thailand",
        "MN3" to "Eagle Vista [Canada]",
        "MNK" to "Hino Motors Manufacturing Thailand Co Ltd.",
        "MNT" to "Nissan Motor (Thailand) Co., Ltd.",
        "MNU" to "Great Wall Motor Manufacturing (Thailand) Co., Ltd.",
        "MP1" to "Isuzu Motors (Thailand) Co., Ltd.",
        "MP2" to "Mazda BT-50 pickup built by Isuzu Motors (Thailand) Co., Ltd.",
        "MP3" to "Plymouth Colt 100 [Canada]",
        "MP5" to "Foton Motor Thailand",
        "MPA" to "Isuzu Motors (Thailand) Co., Ltd. & Holden Rodeo RA pickup",
        "MPB" to "Ford Thailand",
        "MR0" to "Toyota Thailand",
        "MR1" to "Toyota Thailand",
        "MR2" to "Toyota Thailand (Gateway plant",
        "MR3" to "Toyota Thailand",
        "MRH" to "Honda Thailand",
        "MRT" to "Neta",
        "MS0" to "Super Seven Stars Motors Myanmar",
        "MS1" to "Super Seven Stars Automotive Myanmar",
        "MS3" to "Suzuki Myanmar Motor Co., Ltd.",
        "MX3" to "Hyundai Trans Auto",
        "MXB" to "Saryarka AvtoProm bus",
        "MXL" to "Yutong bus",
        "MXV" to "IMZ-Ural Ural Motorcycles",
        "MYH" to "Ather Energy",
        "MZ7" to "MG Motor India Pvt. Ltd.",
        "MZB" to "Kia India Pvt. Ltd.",
        "MZD" to "Classic Legends Private Limited – Jawa",
        "MZZ" to "Citroen India",
        "NAA" to "Iran Khodro",
        "NAC" to "Mammut",
        "NAD" to "Škoda",
        "NAL" to "Maral Sanat Jarvid",
        "NAP" to "Pars Khodro",
        "NAS" to "SAIPA",
        "NC0" to "Oghab Afshan",
        "NFB" to "Honda Atlas Cars Pakistan Ltd.",
        "NG3" to "Lucky Motor Corporation",
        "NL1" to "TOGG",
        "NL2" to "HABAS/HBS",
        "NLA" to "Honda Turkiye A.S. cars",
        "NLC" to "Askam Kamyon Imalat Ve Ticaret A.S.",
        "NLE" to "Mercedes-Benz Türk A.S. Truck",
        "NLF" to "Koluman Otomotiv Endustri A.S.",
        "NLH" to "Hyundai Assan Otomotiv car/SUV",
        "NLJ" to "Hyundai Assan Otomotiv van",
        "NLN" to "Karsan",
        "NLR" to "Otokar",
        "NLT" to "Temsa",
        "NLZ" to "Tezeller",
        "NM0" to "Ford Otosan",
        "NM1" to "Oyak Renault Otomobil Fabrikaları A.Ş.",
        "NM4" to "Tofaş",
        "NMA" to "MAN Türkiye A.Ş.",
        "NMB" to "Mercedes-Benz Türk A.S. Buses",
        "NMC" to "BMC Otomotiv Sanayi ve Ticaret A.Ş.",
        "NMH" to "Honda Anadolu motorcycle",
        "NMS" to "Otoyol San. A.Ş.",
        "NMT" to "Toyota Motor Manufacturing Turkey",
        "NNA" to "Anadolu Isuzu",
        "NNN" to "Gépébus Oréos 4X",
        "NNY" to "Yeksan",
        "NP8" to "ÖZGÜL TREYLER",
        "NPM" to "Seyit Usta Treyler",
        "NPR" to "Oztreyler",
        "NPS" to "Nursan",
        "NRE" to "Bozankaya",
        "NRX" to "Musoshi",
        "NRY" to "Pilotcar Otomotiv",
        "NS2" to "JV MAN Auto - Uzbekistan",
        "NSA" to "SamAvto / SAZ",
        "NVA" to "Khazar",
        "PAB" to "Isuzu Philippines Corporation",
        "PAD" to "Honda Cars Philippines",
        "PE1" to "Ford Motor Company Philippines",
        "PE3" to "Mazda Philippines",
        "PFD" to "Hyundai Motor Group Innovation Center in Singapore",
        "PL1" to "Proton, Malaysia",
        "PL8" to "Inokom-Hyundai",
        "PLP" to "Subaru/Tan Chong Motor Assemblies, Malaysia",
        "PLZ" to "Isuzu Malaysia",
        "PM1" to "BMW & Mini/Inokom",
        "PM2" to "Perodua",
        "PMA" to "MAN Truck & Bus Malaysia",
        "PMH" to "Honda Malaysia",
        "PMK" to "Honda Boon Siew",
        "PML" to "Hicom",
        "PMN" to "Modenas",
        "PMS" to "Suzuki Assemblers Malaysia",
        "PMV" to "Hong Leong Yamaha Motor Sdn. Bhd.",
        "PMY" to "Hong Leong Yamaha Motor Sdn. Bhd.",
        "PN1" to "UMW Toyota Motor",
        "PN2" to "UMW Toyota Motor",
        "PN8" to "Nissan/Tan Chong Motor Assemblies, Malaysia",
        "PNA" to "Stellantis Gurun (Malaysia) Sdn. Bhd.",
        "PNS" to "TMSBUS Malaysia",
        "PNV" to "Volvo Car Manufacturing Malaysia",
        "PP1" to "Mazda/Inokom",
        "PP3" to "Hyundai/Inokom",
        "PPP" to "Suzuki",
        "PPV" to "Volkswagen/HICOM Automotive Manufacturers",
        "PR8" to "Ford",
        "PRA" to "Sinotruk",
        "PRH" to "Chery",
        "PRN" to "GAC Trumpchi",
        "PRX" to "Kia/Inokom",
        "PV3" to "Ford",
        "R10" to "ZAP (HK) Co. Ltd.",
        "R1J" to "Jiayuan Power (Hong Kong) Ltd. (Electric Low-Speed Vehicles",
        "R1N" to "Niu Technologies Group Ltd.",
        "R2P" to "Evoke Electric Motorcycles",
        "R36" to "HK Shansu Technology Co., Ltd.",
        "R3M" to "Mangosteen Technology Co., Ltd.",
        "R4N" to "Elyx Smart Technology Holdings (Hong Kong) Ltd.",
        "R82" to "Hangzhou Lantu Technology Co., Ltd.",
        "RA1" to "Steyr Trucks International FZE, UAE",
        "RF3" to "Aeon Motor Co., Ltd., Taiwan",
        "RF5" to "Yulon Motor Co. Ltd., Taiwan",
        "RF8" to "EVT Technology Co., Ltd",
        "RFB" to "Kwang Yang Motor Co., Ltd. (Kymco), Taiwan",
        "RFC" to "Taiwan Golden Bee",
        "RFD" to "Tai Ling Motor Co Ltd. new designation",
        "RFG" to "Sanyang Motor Co., Ltd. (SYM) Taiwan",
        "RFL" to "Her Chee Industrial Co., Ltd. (Adly), Taiwan",
        "RFT" to "CPI Motor Company, Taiwan",
        "RGS" to "Kawasaki",
        "RHA" to "Ford Lio Ho Motor Co Ltd. new designation",
        "RK3" to "Honda Taiwan",
        "RK7" to "Kawasaki ATV",
        "RKJ" to "Prince Motors Taiwan",
        "RKL" to "Kuozui Motors (Toyota",
        "RKM" to "China Motor Corporation",
        "RKR" to "Yamaha Motor Taiwan Co. Ltd. new designation",
        "RKT" to "Access Motor Co., Ltd.",
        "RL0" to "Ford Vietnam",
        "RL4" to "Toyota Motor Vietnam",
        "RLA" to "Vina Star Motors Corp. – Mitsubishi",
        "RLC" to "Yamaha Motor Vietnam Co. Ltd.",
        "RLE" to "Isuzu Vietnam Co.",
        "RLH" to "Honda Vietnam Co. Ltd.",
        "RLL" to "VinFast SUV",
        "RLM" to "Mercedes-Benz Vietnam",
        "RLN" to "VinFast",
        "RLV" to "Vietnam Precision Industrial CO., Ltd.",
        "RP8" to "Piaggio Vietnam Co. Ltd.",
        "RUN" to "Sollets-Auto ST6",
        "SA3" to "Ginetta Cars",
        "SAA" to "Austin",
        "SAB" to "Optare (1985-2020), Switch Mobility",
        "SAD" to "Jaguar SUV",
        "SAF" to "ERF trucks",
        "SAH" to "Honda",
        "SAJ" to "Jaguar passenger car & Daimler passenger car",
        "SAL" to "Land Rover",
        "SAM" to "Morris",
        "SAR" to "Rover & MG Rover Group",
        "SAT" to "Triumph car",
        "SAX" to "Austin-Rover Group including Sterling Cars",
        "SAY" to "Norton Motorcycles",
        "SAZ" to "Freight Rover",
        "SB1" to "Toyota Motor Manufacturing UK",
        "SBB" to "Leyland Vehicles",
        "SBC" to "Iveco Ford Truck",
        "SBF" to "Nugent",
        "SBJ" to "Leyland Bus",
        "SBL" to "Leyland Motors & Leyland DAF",
        "SBM" to "McLaren",
        "SBS" to "Scammell",
        "SBU" to "United Trailers",
        "SBV" to "Kenworth & Peterbilt trucks",
        "SBW" to "Weightlifter Bodies",
        "SC5" to "Wrightbus",
        "SC6" to "INEOS Automotive SUV",
        "SCA" to "Rolls Royce passenger car",
        "SCB" to "Bentley passenger car",
        "SCC" to "Lotus Cars & Opel Lotus Omega/Vauxhall Lotus Carlton",
        "SCD" to "Reliant Motors",
        "SCE" to "DeLorean Motor Cars N. Ireland",
        "SCF" to "Aston Martin Lagonda Ltd. passenger car & '21 DBX SUV",
        "SCG" to "Triumph Engineering Co. Ltd.",
        "SCK" to "Ifor Williams Trailers",
        "SCM" to "Manitowoc Cranes - Grove",
        "SCV" to "Volvo Truck & Bus Scotland",
        "SD7" to "Aston Martin SUV",
        "SD8" to "Moke International Ltd.",
        "SDB" to "Talbot",
        "SDC" to "SDC Trailers Ltd.",
        "SDF" to "Dodge Trucks – UK 1981–1984",
        "SDG" to "Renault Trucks Industries 1985–1992",
        "SDK" to "Caterham Cars",
        "SDL" to "TVR",
        "SDP" to "NAC MG UK & MG Motor UK Ltd.",
        "SDU" to "Utility",
        "SED" to "IBC Vehicles (General Motors Luton Plant",
        "SEG" to "Dennis Eagle Ltd., including Renault Trucks Access and D Access",
        "SEP" to "Don-Bur",
        "SEY" to "LDV Group Ltd.",
        "SFA" to "Ford UK",
        "SFD" to "Dennis UK / Alexander Dennis",
        "SFE" to "Alexander Dennis UK",
        "SFN" to "Foden Trucks",
        "SFR" to "Fruehauf",
        "SFZ" to "Tesla Roadster",
        "SG4" to "Coachman",
        "SGA" to "Avondale",
        "SGB" to "Bailey",
        "SGD" to "Swift Group Ltd.",
        "SGE" to "Elddis",
        "SGL" to "Lunar Caravans Ltd.",
        "SH7" to "INEOS Automotive truck",
        "SHH" to "Honda UK passenger car",
        "SHS" to "Honda UK SUV",
        "SJ1" to "Ree Automotive",
        "SJA" to "Bentley SUV",
        "SJB" to "Brian James Trailers Ltd",
        "SJK" to "Nissan Motor Manufacturing UK - Infiniti",
        "SJN" to "Nissan Motor Manufacturing UK - Nissan",
        "SKA" to "Vauxhall",
        "SKB" to "Kel-Berg Trailers & Trucks",
        "SKF" to "Bedford Vehicles",
        "SKL" to "Anaig (UK) Technology Ltd",
        "SLA" to "Rolls Royce SUV",
        "SLC" to "Thwaites Dumpers",
        "SLG" to "McMurtry Automotive",
        "SLN" to "Niftylift",
        "SLP" to "JC Bamford Excavators Ltd.",
        "SLV" to "Volvo bus",
        "SMR" to "Montracon",
        "SMT" to "Triumph Motorcycles Ltd.",
        "SMW" to "Cartwright",
        "SMX" to "Gray & Adams",
        "SNE" to "Wartburg",
        "SNT" to "Trabant",
        "SNZ" to "MZ (motorcycle",
        "SPE" to "B-ON GmbH",
        "ST3" to "Calabrese",
        "SUA" to "Autosan",
        "SUB" to "Tramp Trail",
        "SUC" to "Wiola",
        "SUD" to "Wielton",
        "SUF" to "FSM/Fiat Auto Poland",
        "SUG" to "Mega Trailers (truck trailer",
        "SUJ" to "Jelcz",
        "SUL" to "FSC",
        "SUM" to "Novatrail",
        "SUP" to "FSO/Daewoo-FSO",
        "SUU" to "Solaris Bus & Coach",
        "SVH" to "ZASŁAW",
        "SVM" to "Inter Cars",
        "SVS" to "BODEX",
        "SWH" to "Temared",
        "SWR" to "Weekend Trailers",
        "SWV" to "TA-NO",
        "SWZ" to "Zremb",
        "SX7" to "Arthur Bus",
        "SXE" to "Neptun Trailers",
        "SXK" to "Konar",
        "SXM" to "MELEX Sp. z o.o.",
        "SXX" to "Martz",
        "SXY" to "Wecon",
        "SY1" to "Neso Bus",
        "SYB" to "Rydwan",
        "SYG" to "Gniotpol, GT Trailers Sp. z o. o.",
        "SZA" to "Scania Poland",
        "SZC" to "Vectrix",
        "SZL" to "Boro Trailers",
        "SZN" to "Przyczepy Głowacz",
        "SZR" to "Niewiadów",
        "T3C" to "Lohr Backa Topola (truck trailer",
        "T7A" to "Ebusco",
        "TAW" to "NAW Nutzfahrzeuggesellschaft Arbon & Wetzikon AG",
        "TBS" to "Boschung AG",
        "TCC" to "Micro Compact Car AG (smart 1998-1999",
        "TDM" to "QUANTYA Swiss Electric Movement",
        "TEB" to "Bucher Municipal AG",
        "TEM" to "Twike (SwissLEM AG",
        "TFH" to "FHS Frech-Hoch AG (truck trailer",
        "TJ5" to "Vezeko (trailer",
        "TKP" to "Panav a.s. (truck trailer",
        "TKX" to "Agados s.r.o. (trailer",
        "TKY" to "Metaco (truck trailer",
        "TLJ" to "Jawa Moto",
        "TMA" to "Hyundai Motor Manufacturing Czech",
        "TMB" to "Škoda",
        "TMC" to "Hyundai Motor Manufacturing Czech",
        "TMK" to "Karosa",
        "TMP" to "Škoda trolleybuses",
        "TMT" to "Tatra passenger car",
        "TNA" to "Avia/Daewoo Avia",
        "TNE" to "TAZ",
        "TNG" to "LIAZ",
        "TNT" to "Tatra trucks",
        "TNU" to "Tatra trucks",
        "TRA" to "Ikarus Bus",
        "TRC" to "Csepel bus",
        "TRE" to "Rákos bus",
        "TRK" to "Credo bus/Kravtex",
        "TRR" to "Rába Bus",
        "TRU" to "Audi Hungary",
        "TSB" to "Ikarus Bus",
        "TSC" to "VIN assigned by the National Transport Authority of Hungary",
        "TSE" to "Ikarus Egyedi Autobuszgyar (EAG",
        "TSF" to "Alfabusz",
        "TSM" to "Suzuki Hungary (Magyar Suzuki), Fiat Sedici",
        "TSY" to "Keeway Motorcycles",
        "TW0" to "CaetanoBus",
        "TW1" to "Toyota Caetano Portugal, S.A.",
        "TW2" to "Ford Lusitana",
        "TW4" to "UMM",
        "TW6" to "Citroën",
        "TW7" to "Mini Moke",
        "TWG" to "CaetanoBus",
        "TX5" to "Mini Moke",
        "TYA" to "Mitsubishi Fuso Truck and Bus Corp. Portugal",
        "TYB" to "Mitsubishi Fuso Truck and Bus Corp. Portugal",
        "U1A" to "Sanos",
        "U1V" to "VDL Van Hool Macedonia",
        "U5Y" to "Kia Motors Slovakia",
        "U6A" to "Granus (bus",
        "U6Y" to "Kia Motors Slovakia",
        "UA1" to "AUSA Center",
        "UA2" to "Iveco Massif & Campagnola",
        "UA4" to "Irizar e-mobility",
        "UCY" to "Silence Urban Ecomobility",
        "UD3" to "Granalu truck trailers",
        "UH2" to "De Forenede Trailerfabrikke (trailer",
        "UHE" to "Scanvogn (trailer",
        "UHL" to "Camp-let (recreational vehicle",
        "UJG" to "Garia ApS - Club Car",
        "UKR" to "Hero Camper",
        "UMT" to "MTDK a/s (truck trailer",
        "UN1" to "Ford Ireland",
        "UU1" to "Dacia",
        "UU2" to "Oltcit",
        "UU3" to "ARO",
        "UU4" to "Roman/Grivbuz",
        "UU5" to "Rocar",
        "UU6" to "Daewoo Romania",
        "UU7" to "Euro Bus Diamond",
        "UU9" to "Astra Bus",
        "UVW" to "UMM",
        "UWR" to "Robus Reșița",
        "UZT" to "UTB",
        "V1Y" to "FAS Sanos bus",
        "V2X" to "Ikarbus a.d.",
        "V31" to "Tvornica Autobusa Zagreb (TAZ",
        "V34" to "Crobus bus",
        "V61" to "Respo Trailers",
        "V6A" to "Bestnet AS; Tiki trailers",
        "V6B" to "Brentex-Trailer",
        "V6T" to "Verge Motorcycles",
        "VA0" to "ÖAF, Gräf & Stift",
        "VA4" to "KSR Group",
        "VAG" to "Steyr-Daimler-Puch Puch G & Steyr-Puch Pinzgauer",
        "VAH" to "Hangler",
        "VAK" to "Kässbohrer Transport Technik",
        "VAN" to "MAN Austria/Steyr-Daimler-Puch Steyr Trucks",
        "VAV" to "Schwarzmüller",
        "VAX" to "Schwingenschlogel",
        "VBF" to "Fit-Zel",
        "VBK" to "Husqvarna Motorcycles & Gas Gas under KTM ownership",
        "VCF" to "Fisker Inc.",
        "VF1" to "Renault, Mobilize Duo, Eagle Medallion",
        "VF2" to "Renault Trucks",
        "VF3" to "Peugeot",
        "VF4" to "Talbot",
        "VF5" to "Iveco Unic",
        "VF6" to "Renault Trucks including vans",
        "VF7" to "Citroën",
        "VF8" to "Matra Automobiles (Talbot-Matra Murena, Rancho",
        "VFA" to "Alpine, Renault Alpine GTA",
        "VFG" to "Caravelair",
        "VFK" to "Fruehauf",
        "VFN" to "Trailor, General Trailers",
        "VG5" to "MBK (motorcycles) & Yamaha Motor",
        "VG6" to "Renault Trucks & Mack Trucks medium duty trucks",
        "VG7" to "Renault Trucks",
        "VG8" to "Renault Trucks",
        "VGA" to "Peugeot Motocycles",
        "VGT" to "ASCA",
        "VGU" to "Trouillet",
        "VGW" to "BSLT",
        "VGX" to "Coder",
        "VGY" to "Lohr",
        "VH1" to "Benalu SAS",
        "VH8" to "Microcar",
        "VHR" to "Robuste",
        "VHX" to "Manitowoc Cranes - Potain",
        "VJ1" to "Heuliez Bus",
        "VJ2" to "Mia Electric",
        "VJ4" to "Gruau",
        "VJR" to "Ligier",
        "VJY" to "Gruau",
        "VK1" to "SEG",
        "VK2" to "Grandin Automobiles",
        "VK8" to "Venturi Automobiles",
        "VKD" to "Cheval Liberté",
        "VL4" to "Bluecar, Citroen E-Mehari",
        "VLG" to "Aixam-Mega",
        "VLU" to "Scania France",
        "VM3" to "Chereau",
        "VMK" to "Renault Sport Spider",
        "VMS" to "Automobiles Chatenet",
        "VMT" to "SECMA",
        "VMW" to "Gépébus Oréos 55",
        "VN1" to "Renault SOVAB (France), Opel/Vauxhall Movano A made at SOVAB",
        "VN4" to "Voxan",
        "VNE" to "Iveco Bus/Irisbus",
        "VNK" to "Toyota Motor Manufacturing France & '11-'13 Daihatsu Charade",
        "VNV" to "Nissan made in France by Renault",
        "VP3" to "G. Magyar",
        "VPL" to "Nosmoke S.A.S",
        "VR1" to "DS Automobiles",
        "VR3" to "Peugeot",
        "VR7" to "Citroën",
        "VRW" to "Goupil",
        "VS1" to "Pegaso",
        "VS5" to "Renault Spain",
        "VS6" to "Ford Spain",
        "VS7" to "Citroën Spain",
        "VS8" to "Peugeot Spain",
        "VSA" to "Mercedes-Benz Spain",
        "VSC" to "Talbot",
        "VSF" to "Santana Motors",
        "VSR" to "Leciñena",
        "VSS" to "SEAT/Cupra",
        "VSX" to "Opel Spain",
        "VSY" to "Renault V.I. Spain",
        "VTD" to "Montesa Honda",
        "VTH" to "Derbi",
        "VTL" to "Yamaha Spain",
        "VTM" to "Montesa Honda",
        "VTP" to "Rieju S.A.",
        "VTR" to "Gas Gas",
        "VTT" to "Suzuki Spain",
        "VV1" to "Lecitrailer Group",
        "VV5" to "Prim-Ball",
        "VVC" to "SOR Ibérica",
        "VVG" to "Tisvol",
        "VWA" to "Nissan Vehiculos Industriales SA, Nissan Commercial Vehicles",
        "VWF" to "Guillén Group",
        "VWL" to "Indox",
        "VWV" to "Volkswagen Spain",
        "VX1" to "Zastava Automobiles/ Yugo",
        "VXE" to "Opel Automobile Gmbh/Vauxhall van",
        "VXF" to "Fiat van",
        "VXK" to "Opel Automobile Gmbh/Vauxhall car/SUV",
        "VXY" to "Neobus a.d.",
        "VYC" to "Lancia Ypsilon",
        "VYE" to "Jeep Compass",
        "VYF" to "Fiat Doblo '23- & Fiat Topolino '23- & Fiat Grande Panda '25-",
        "VYJ" to "Ram 1200 '25-",
        "VYS" to "Renault & Alpine",
        "VZ2" to "Avtomontaža (bus",
        "W04" to "Buick Regal & Buick Cascada",
        "W06" to "Cadillac Catera",
        "W08" to "Saturn Astra",
        "W0D" to "Obermaier",
        "W0L" to "Holden Zafira & Subaru Traviq",
        "W0V" to "Opel Automobile Gmbh/Vauxhall & Holden",
        "W1A" to "smart",
        "W1H" to "Freightliner Econic",
        "W1K" to "Mercedes-Benz car",
        "W1N" to "Mercedes-Benz SUV",
        "W1T" to "Mercedes-Benz truck",
        "W1V" to "Mercedes-Benz van",
        "W1W" to "Mercedes-Benz MPV (van with 2 or 3 rows of seats",
        "W1X" to "Mercedes-Benz incomplete vehicle",
        "W1Y" to "Mercedes-Benz truck (cargo van with 1 row of seats",
        "W1Z" to "Mercedes-Benz \"bus\" (van with more than 3 rows of seats",
        "W2W" to "Freightliner Sprinter MPV",
        "W2X" to "Freightliner Sprinter incomplete vehicle",
        "W2Y" to "Freightliner Sprinter truck",
        "W2Z" to "Freightliner Sprinter \"bus\"",
        "WA1" to "Audi SUV",
        "WAC" to "Audi/Porsche RS2 Avant",
        "WAF" to "Ackermann",
        "WAG" to "Neoplan",
        "WAP" to "Alpina",
        "WAU" to "Audi car",
        "WB0" to "Böckmann Fahrzeugwerke GmbH",
        "WB1" to "BMW Motorrad",
        "WB2" to "Blyss",
        "WB3" to "BMW Motorrad Motorcycles made in India by TVS",
        "WB4" to "BMW Motorrad Motorscooters made in China by Loncin",
        "WB5" to "BMW i SUV",
        "WBA" to "BMW car",
        "WBC" to "Boom Trikes",
        "WBJ" to "Bitter Cars",
        "WBK" to "Böcker Maschinenwerke GmbH",
        "WBL" to "Blumhardt",
        "WBS" to "BMW M car",
        "WBU" to "Bürstner",
        "WBX" to "BMW SUV",
        "WBY" to "BMW i car",
        "WCD" to "Freightliner Sprinter \"bus\" (van with more than 3 rows of seats) 2008–2019",
        "WCM" to "Wilcox",
        "WD0" to "Dodge Sprinter truck (cargo van with 1 row of seats) 2005–2009",
        "WD2" to "Freightliner Sprinter 2002 & Sprinter (Dodge or Freightliner) 2003–2005 truck",
        "WD3" to "Mercedes-Benz truck (cargo van with 1 row of seats",
        "WD4" to "Mercedes-Benz MPV (van with 2 or 3 rows of seats",
        "WD5" to "Freightliner Sprinter 2002 & Sprinter (Dodge or Freightliner) 2003–2005 MPV",
        "WD6" to "Freightliner Unimog truck",
        "WD7" to "Freightliner Unimog incomplete vehicle",
        "WD8" to "Dodge Sprinter MPV (van with 2 or 3 rows of seats) 2005–2009",
        "WDA" to "Mercedes-Benz incomplete vehicle",
        "WDB" to "Mercedes-Benz & Maybach",
        "WDC" to "Mercedes-Benz SUV",
        "WDD" to "Mercedes-Benz car",
        "WDF" to "Mercedes-Benz van/pickup",
        "WDP" to "Freightliner Sprinter incomplete vehicle 2005–2019",
        "WDR" to "Freightliner Sprinter MPV (van with 2 or 3 rows of seats) 2005–2019",
        "WDT" to "Dethleffs",
        "WDW" to "Dodge Sprinter \"bus\" (van with more than 3 rows of seats) 2008–2009",
        "WDX" to "Dodge Sprinter incomplete vehicle 2005–2009",
        "WDY" to "Freightliner Sprinter truck (cargo van with 1 row of seats) 2005–2019",
        "WDZ" to "Mercedes-Benz \"bus\" (van with more than 3 rows of seats",
        "WEB" to "Evobus GmbH",
        "WEG" to "Ablinger",
        "WEL" to "e.GO Mobile AG",
        "WF0" to "Ford Germany",
        "WF1" to "Merkur",
        "WFB" to "Feldbinder Spezialfahrzeugwerke GmbH",
        "WFC" to "Fendt",
        "WFD" to "Fliegl Trailer",
        "WFN" to "Tadano Faun GmbH",
        "WG0" to "Goldhofer AG",
        "WGB" to "Göppel Bus GmbH",
        "WH7" to "Hüfferman",
        "WHB" to "Hobby",
        "WHD" to "Humbaur GmbH",
        "WHL" to "Hulco",
        "WHW" to "Hako GmbH",
        "WHY" to "Hymer",
        "WJM" to "Iveco/Iveco Magirus",
        "WJR" to "Irmscher",
        "WK0" to "Kögel",
        "WKE" to "Krone",
        "WKK" to "Setra",
        "WKN" to "Knaus, Weinsberg",
        "WKV" to "Kässbohrer Fahrzeugwerke Gmbh",
        "WLA" to "Langendorf semi-trailers",
        "WLF" to "Liebherr",
        "WMA" to "MAN Truck & Bus",
        "WME" to "smart",
        "WMG" to "Demag Cranes",
        "WMM" to "Karl Müller GmbH & Co. KG",
        "WMP" to "M & V GmbH",
        "WMU" to "Hako GmbH",
        "WMW" to "MINI car",
        "WMX" to "Mercedes-AMG used for Mercedes-Benz SLS AMG & Mercedes-AMG GT",
        "WMZ" to "MINI SUV",
        "WNA" to "Next.e.GO Mobile SE",
        "WP0" to "Porsche car",
        "WP1" to "Porsche SUV",
        "WRA" to "Renders",
        "WRJ" to "Riese & Müller",
        "WS5" to "StreetScooter",
        "WS7" to "Sono Motors",
        "WSE" to "STEMA Metalleichtbau GmbH",
        "WSJ" to "STERK Trailers",
        "WSK" to "Schmitz-Cargobull Gotha",
        "WSM" to "Schmitz-Cargobull",
        "WSP" to "Spitzer",
        "WSV" to "Aebi Schmidt Group",
        "WTA" to "Tabbert",
        "WU1" to "Audi Sport GmbH (formerly quattro GmbH) SUV",
        "WUA" to "Audi Sport GmbH (formerly quattro GmbH) car",
        "WV1" to "Volkswagen Commercial Vehicles",
        "WV2" to "Volkswagen Commercial Vehicles",
        "WV3" to "Volkswagen Commercial Vehicles",
        "WV4" to "Volkswagen Commercial Vehicles (2nd gen. Amarok & T7 Transporter",
        "WV5" to "Volkswagen Commercial Vehicles (T7 Caravelle",
        "WVG" to "Volkswagen SUV & Touran",
        "WVM" to "Arbeitsgemeinschaft VW-MAN",
        "WVP" to "Viseon Bus",
        "WVW" to "Volkswagen passenger car, Sharan, Golf Plus, Golf Sportsvan",
        "WWA" to "Wachenhut",
        "WWC" to "WM Meyer",
        "WZ1" to "Toyota Supra",
        "X0T" to "Tonar",
        "X1D" to "RAF",
        "X1E" to "KAvZ",
        "X1F" to "NefAZ",
        "X1M" to "PAZ",
        "X1P" to "Ural",
        "X21" to "Diesel-S (truck trailer",
        "X2L" to "Fox Trailer (truck trailer",
        "X4K" to "Volgabus (Volzhanin",
        "X4T" to "Sommer (truck trailer",
        "X4X" to "Avtotor",
        "X5A" to "UralSpetzTrans (trailer",
        "X6D" to "VIS-AVTO",
        "X6S" to "TZA (truck trailer",
        "X7L" to "Renault AvtoFramos (1998-2014), Renault Russia (2014-2022), Moskvitch (2022-",
        "X7M" to "Hyundai & Vortex",
        "X8J" to "IMZ-Ural Ural Motorcycles",
        "X8U" to "Scania Russia",
        "X90" to "GRAZ",
        "X96" to "GAZ",
        "X9F" to "Ford Motor Company ZAO",
        "X9L" to "GM-AvtoVAZ",
        "X9N" to "Samoltor",
        "X9P" to "Volvo Vostok ZAO Volvo Trucks",
        "X9W" to "Brilliance, Lifan",
        "X9X" to "Great Wall Motors",
        "XD2" to "CTTM Cargoline (truck trailer",
        "XDN" to "Mercedes Sprinter Classic",
        "XE2" to "AMKAR Automaster (truck trailer",
        "XEA" to "AmberAvto (Avtotor",
        "XG3" to "Petros Petropoulos Group - Ecoshift NOOS electric motorscooters",
        "XG4" to "Mpitis (trailer",
        "XG5" to "Stavropoulos trailers",
        "XG6" to "MGK Hellenic Motor motorcycles",
        "XG8" to "Gorgolis SA motorcycles",
        "XJ4" to "PKTS (PK Transportnye Sistemy) bus",
        "XJY" to "Bonum (truck trailer",
        "XKM" to "Volgabus",
        "XL3" to "Ebusco",
        "XL4" to "Lightyear",
        "XLA" to "DAF Bus International",
        "XLB" to "Volvo Car B.V./NedCar B.V.",
        "XLC" to "Ford Netherlands",
        "XLD" to "Pacton Trailers B.V.",
        "XLE" to "Scania Netherlands",
        "XLH" to "Hapert",
        "XLJ" to "Anssems",
        "XLK" to "Burg Trailer Service BV",
        "XLR" to "DAF Trucks & Leyland DAF",
        "XLU" to "Henra",
        "XLV" to "DAF Bus",
        "XLW" to "Terberg Benschop BV",
        "XM4" to "RAVO Holding B.V.",
        "XMC" to "NedCar B.V. Mitsubishi Motors",
        "XMD" to "NedCar B.V. Mitsubishi Motors",
        "XMG" to "VDL Bus International",
        "XMR" to "Nooteboom Trailers",
        "XN1" to "Kraker Trailers Axel B.V.",
        "XNB" to "NedCar B.V. Mitsubishi Motors",
        "XNC" to "NedCar B.V. Mitsubishi Motors",
        "XNJ" to "Broshuis",
        "XNL" to "VDL Bus & Coach",
        "XNT" to "Pacton Trailers B.V.",
        "XP7" to "Tesla Europe (based in the Netherlands",
        "XPN" to "Knapen Trailers",
        "XPP" to "Atec Trailers",
        "XR7" to "Qarry",
        "XRP" to "Proline",
        "XRY" to "D-TEC",
        "XTA" to "Lada / AvtoVAZ",
        "XTB" to "Moskvitch / AZLK",
        "XTC" to "KAMAZ",
        "XTD" to "LuAZ",
        "XTE" to "ZAZ",
        "XTF" to "GolAZ",
        "XTH" to "GAZ",
        "XTJ" to "Lada Oka",
        "XTK" to "IzhAvto",
        "XTM" to "MAZ (Belarus); used until 1997",
        "XTP" to "Ural",
        "XTS" to "ChMZAP",
        "XTT" to "UAZ / Sollers",
        "XTU" to "Trolza, previously ZiU",
        "XTW" to "LAZ",
        "XTY" to "LiAZ",
        "XTZ" to "ZiL",
        "XU6" to "Avtodom (minibus",
        "XUF" to "General Motors Russia",
        "XUS" to "Nizhegorodets (minibus",
        "XUU" to "Avtotor",
        "XUV" to "Avtotor",
        "XUZ" to "InterPipeVAN",
        "XVG" to "MARZ (bus",
        "XVU" to "Start",
        "XW7" to "Toyota Motor Manufacturing Russia",
        "XW8" to "Volkswagen Group Russia",
        "XWB" to "Avtotor",
        "XWE" to "Avtotor",
        "XWF" to "Avtotor",
        "XX3" to "Ujet Manufacturing",
        "XZB" to "SIMAZ (bus",
        "XZE" to "Specpricep",
        "XZG" to "Great Wall Motor",
        "XZP" to "Gut Trailer",
        "XZT" to "FoxBus (minibus",
        "Y3D" to "MTM (truck trailer",
        "Y3F" to "Lida Buses Neman",
        "Y3J" to "Belkommunmash",
        "Y3K" to "Neman Bus",
        "Y3M" to "MAZ",
        "Y3W" to "VFV built by Unison",
        "Y4F" to "Ford Belarus",
        "Y4K" to "Geely / BelGee",
        "Y6B" to "Iveco",
        "Y6D" to "ZAZ / AvtoZAZ",
        "Y6E" to "LAZ",
        "Y6J" to "Bogdan group",
        "Y6L" to "Bogdan group including buses, Hyundai",
        "Y6U" to "Škoda Auto",
        "Y6W" to "PGFM (trailer",
        "Y6Y" to "LEV (trailer",
        "Y7A" to "KrAZ trucks",
        "Y7B" to "Bogdan group",
        "Y7C" to "Great Wall Motors, Geely",
        "Y7D" to "GAZ",
        "Y7F" to "Boryspil Bus Factory (BAZ",
        "Y7S" to "Korida-Tech (trailer",
        "Y7W" to "Geely",
        "Y7X" to "ChRZ - Ruta (minibus",
        "Y8A" to "LAZ",
        "Y8H" to "UNV Leader (trailer",
        "Y8S" to "Alekseevka Ximmash",
        "Y8X" to "GAZ Gazelle",
        "Y9A" to "PAVAM (trailer",
        "Y9H" to "LAZ",
        "Y9M" to "AMS (trailer",
        "Y9T" to "Dnipro (trailer",
        "Y9W" to "Pragmatec (trailer",
        "Y9Z" to "Lada, Renault made in Ukraine",
        "YA2" to "Atlas Copco Group",
        "YA5" to "Renders",
        "YAF" to "Faymonville",
        "YAG" to "Syma aanhangwagenbouw BV",
        "YAM" to "MAX Trailer",
        "YB1" to "Volvo Trucks Belgium",
        "YB2" to "Volvo Trucks Belgium",
        "YB3" to "Volvo Trucks Belgium",
        "YB4" to "LAG Trailers N.V.",
        "YB6" to "Jonckheere",
        "YBC" to "Toyota Supra",
        "YBD" to "Addax Motors",
        "YBW" to "Volkswagen Belgium",
        "YC1" to "Honda Belgium NV",
        "YC3" to "Eduard Trailers",
        "YD3" to "Chateau Caravans",
        "YE1" to "Van Hool (trailers",
        "YE2" to "Van Hool (buses",
        "YE6" to "STAS",
        "YE7" to "Turbo's Hoet",
        "YF1" to "Närko (truck trailer",
        "YF3" to "NTM (truck trailer",
        "YGU" to "JJ-Trailer (trailer",
        "YH1" to "Solifer",
        "YH2" to "BRP Finland",
        "YH4" to "Fisker Automotive (Fisker Karma) built by Valmet Automotive",
        "YK1" to "Saab-Valmet Finland",
        "YS2" to "Scania commercial vehicles",
        "YS3" to "Saab cars",
        "YS4" to "Scania buses and bus chassis until 2002",
        "YS5" to "OmniNova",
        "YS7" to "Solifer",
        "YSC" to "Cadillac BLS",
        "YSM" to "Polestar cars",
        "YSP" to "Volta Trucks AB",
        "YSR" to "Polestar SUV",
        "YT7" to "Kabe",
        "YTN" to "Saab",
        "YU1" to "Fogelsta, Brenderup Group",
        "YU7" to "Husaberg",
        "YV1" to "Volvo cars",
        "YV2" to "Volvo trucks",
        "YV3" to "Volvo buses and bus chassis",
        "YV4" to "Volvo SUV",
        "YV5" to "Volvo Trucks incomplete vehicle",
        "YVV" to "WiMa 442 EV",
        "YYB" to "Tysse (trailer",
        "YYC" to "Think Nordic",
        "Z07" to "Volgabus",
        "Z6F" to "Ford Sollers",
        "Z76" to "SEMAZ",
        "Z7C" to "Luidor (bus",
        "Z7N" to "KAvZ (bus",
        "Z7T" to "RoAZ (bus",
        "Z7X" to "Isuzu Rus",
        "Z8M" to "Marussia",
        "Z8N" to "Nissan Manufacturing Rus",
        "Z8T" to "PCMA Rus (Peugeot, Citroen, Mitsubishi",
        "Z8Y" to "Nasteviya (bus",
        "Z9B" to "KuzbassAvto (Hyundai bus",
        "Z9M" to "Mercedes-Benz Trucks Vostok",
        "Z9N" to "Samotlor-NN (Iveco",
        "ZA0" to "Acerbi",
        "ZA4" to "Omar",
        "ZAA" to "Alfa Romeo Junior 2024-",
        "ZAC" to "Jeep, Dodge Hornet",
        "ZAH" to "Rolfo SpA",
        "ZAJ" to "Trigano SpA; Roller Team recreational vehicles",
        "ZAM" to "Maserati",
        "ZAP" to "Piaggio/Vespa/Gilera",
        "ZAR" to "Alfa Romeo car",
        "ZAS" to "Alfa Romeo SUV 2018-",
        "ZAX" to "Zorzi",
        "ZB3" to "Cardi",
        "ZBA" to "Piacenza",
        "ZBB" to "Bertone",
        "ZBD" to "InBus",
        "ZBN" to "Benelli",
        "ZBW" to "Rayton-Fissore Magnum",
        "ZC1" to "AnsaldoBreda S.p.A.",
        "ZC2" to "Chrysler TC by Maserati",
        "ZCB" to "E. Bartoletti SpA",
        "ZCF" to "Iveco / Irisbus",
        "ZCG" to "Husqvarna Motorcycles Under MV Agusta ownership",
        "ZCM" to "BredaMenarinibus / Menarinibus / IIA",
        "ZCN" to "Astra Veicoli Industriali S.p.A.",
        "ZCV" to "Vibreti",
        "ZCZ" to "BredaBus",
        "ZD0" to "Yamaha Motor Italia SpA & Belgarda SpA",
        "ZD3" to "Beta Motor",
        "ZD4" to "Aprilia",
        "ZD5" to "Casalini",
        "ZDC" to "Honda Italia Industriale SpA",
        "ZDF" to "Ferrari Dino",
        "ZDJ" to "ACM Biagini",
        "ZDM" to "Ducati Motor Holdings SpA",
        "ZDT" to "De Tomaso Modena SpA",
        "ZDY" to "Cacciamali",
        "ZE5" to "Carmosino",
        "ZEB" to "Ellebi",
        "ZEH" to "Trigano SpA (former SEA Group); McLouis & Mobilvetta recreational vehicles",
        "ZES" to "Bimota",
        "ZEX" to "TM Racing",
        "ZF4" to "Qvale",
        "ZFA" to "Fiat",
        "ZFB" to "Fiat MPV/SUV & Ram Promaster City",
        "ZFC" to "Fiat truck",
        "ZFE" to "KL Motorcycle",
        "ZFF" to "Ferrari",
        "ZFJ" to "Carrozzeria Pezzaioli",
        "ZFM" to "Fantic Motor",
        "ZFR" to "Pininfarina",
        "ZG2" to "FAAM",
        "ZGA" to "Iveco Bus",
        "ZGP" to "Merker",
        "ZGU" to "Moto Guzzi",
        "ZH5" to "FB Mondial",
        "ZHU" to "Husqvarna Motorcycles Under Cagiva ownership",
        "ZHW" to "Lamborghini",
        "ZHZ" to "Menci SpA",
        "ZJM" to "Malaguti",
        "ZJN" to "Innocenti",
        "ZJT" to "Italjet",
        "ZKC" to "Ducati Energia Free Duck",
        "ZKH" to "Husqvarna Motorcycles Srl Under BMW ownership",
        "ZLA" to "Lancia",
        "ZLF" to "Tazzari GL SpA",
        "ZLM" to "Moto Morini srl",
        "ZLV" to "Laverda",
        "ZN0" to "SWM Motorcycles S.r.l.",
        "ZN3" to "Iveco Defence",
        "ZN6" to "Maserati SUV",
        "ZNN" to "Energica",
        "ZP6" to "XEV",
        "ZP8" to "Regis Motors",
        "ZPB" to "Lamborghini SUV",
        "ZPY" to "DR Automobiles",
        "ZR1" to "Microlino",
        "ZRG" to "Tazzari GL Imola SpA",
        "ZSG" to "Ferrari SUV",
        "ZX1" to "TAM (Tovarna Avtomobilov Maribor) bus",
        "ZY1" to "Adria (recreational vehicles",
        "ZZ1" to "Tomos motorcycle",
    )

    /** Возвращает подпись по WMI или null, если кода нет в таблице. */
    fun getMake(wmi: String): String? = ENTRIES[wmi.uppercase()]
}