import Foundation

/// Справочник WMI → подпись производителя (Wikibooks, community).
/// Обновление: scripts/generate_vin_wmi_table.py
enum VinWmiTable {
    private static let entries: [String: String] = [
        "10B": "Brenner Tank",
        "10R": "E-Z-GO",
        "10T": "Oshkosh Corporation",
        "11H": "Hendrickson Mobile Equipment, Inc.",
        "12A": "Avanti",
        "137": "AM General Hummer & Hummer H1",
        "13N": "Fontaine",
        "15G": "Gillig bus",
        "16C": "Clenet Coachworks",
        "16W": "West-Mark",
        "16X": "Vixen 21 motorhome",
        "17N": "John Deere incomplete vehicle",
        "19U": "Acura car",
        "19V": "Acura car",
        "19X": "Honda car",
        "1AC": "American Motors Corporation MPV",
        "1AF": "American LaFrance truck",
        "1AJ": "Ajax Manufacturing",
        "1AM": "American Motors Corporation car & Renault Alliance 1983 only",
        "1B3": "Dodge car 1981–2011",
        "1B4": "Dodge MPV/SUV 1981–2002",
        "1B6": "Dodge incomplete vehicle 1981–2002",
        "1B7": "Dodge truck 1981–2002",
        "1BA": "Blue Bird Corporation bus",
        "1BB": "Blue Bird Wanderlodge MPV",
        "1BD": "Blue Bird Corporation incomplete vehicle",
        "1BL": "Balko, Inc.",
        "1BN": "Beall Trailers",
        "1C3": "Chrysler Group (all brands) car (including Lancia) 2012-",
        "1C4": "Chrysler Group (all brands) MPV 2012–",
        "1C6": "Chrysler Group (all brands) truck 2012–",
        "1C8": "Chrysler brand MPV 2001–2005",
        "1CM": "Checker Motors Corporation",
        "1CU": "Cushman Haulster",
        "1CY": "Battle Motors, Inc.",
        "1D3": "Dodge truck 2002–2009",
        "1D4": "Dodge MPV/SUV 2003–2011 only",
        "1D7": "Dodge truck 2002–2011",
        "1D8": "Dodge MPV/SUV 2003–2009 only",
        "1DW": "Stoughton Trailers",
        "1EU": "Eagle Coach Corporation",
        "1F1": "Ford SUV - Limousine",
        "1F6": "Ford stripped chassis",
        "1FA": "Ford car",
        "1FB": "Ford\"bus\"",
        "1FC": "Ford stripped chassis",
        "1FD": "Ford incomplete vehicle",
        "1FM": "Ford MPV/SUV",
        "1FT": "Ford truck",
        "1FU": "Freightliner truck",
        "1FV": "Freightliner incomplete vehicle",
        "1G0": "Opel/Vauxhall car 2007–2017",
        "1G1": "Chevrolet car",
        "1G2": "Pontiac car",
        "1G3": "Oldsmobile car",
        "1G4": "Buick car",
        "1G5": "GMC MPV/SUV 1981–1986",
        "1G6": "Cadillac car",
        "1G7": "Pontiac car only sold by GM Canada",
        "1G8": "Saturn car 1991–2010",
        "1GA": "Chevrolet \"bus\"",
        "1GB": "Chevrolet incomplete vehicles",
        "1GC": "Chevrolet truck",
        "1GD": "GMC incomplete vehicles",
        "1GE": "Cadillac incomplete vehicle",
        "1GF": "Flxible bus",
        "1GG": "Isuzu pickup trucks",
        "1GH": "Holden Acadia 2019–2020",
        "1GJ": "GMC \"bus\" (van with more than 3 rows of seats) 1987–",
        "1GK": "GMC MPV/SUV 1987–",
        "1GM": "Pontiac MPV",
        "1GN": "Chevrolet MPV/SUV 1987-",
        "1GR": "Great Dane Trailers",
        "1GT": "GMC Truck",
        "1GY": "Cadillac SUV",
        "1HA": "Chevrolet incomplete vehicles",
        "1HD": "Harley-Davidson & LiveWire",
        "1HF": "Honda motorcycle/ATV/UTV",
        "1HG": "Honda car",
        "1HS": "International Trucks & Caterpillar Trucks truck",
        "1HV": "IC Bus incomplete bus",
        "1J4": "Jeep SUV 1989–2011",
        "1J7": "Jeep truck 1989–1992",
        "1J8": "Jeep SUV 2002–2011",
        "1JC": "Jeep SUV 1981–1988",
        "1JJ": "Wabash",
        "1JT": "Jeep truck 1981–1988",
        "1JU": "Marmon Motor Company",
        "1L0": "Lufkin Trailers",
        "1L1": "Lincoln car – limousine",
        "1LH": "Landoll",
        "1LJ": "Lincoln incomplete vehicle",
        "1LN": "Lincoln car",
        "1LV": "Lectra Motors",
        "1M0": "John Deere Gator",
        "1M1": "Mack Truck USA",
        "1M2": "Mack Truck USA incomplete vehicle",
        "1M3": "Mack Truck USA",
        "1M4": "Mack Truck USA",
        "1M8": "Motor Coach Industries",
        "1MB": "Mercedes-Benz Truck Co.",
        "1ME": "Mercury car",
        "1MR": "Continental Mark VI & VII 1981–1985 & Continental sedan 1982–1985",
        "1N4": "Nissan car",
        "1N6": "Nissan truck",
        "1NK": "Kenworth incomplete vehicle",
        "1NL": "Gulf Stream Coach",
        "1NN": "Monon",
        "1NP": "Peterbilt incomplete vehicle",
        "1NX": "Toyota car",
        "1P3": "Plymouth car",
        "1P4": "Plymouth MPV/SUV",
        "1P7": "Plymouth Scamp",
        "1PM": "Polar Tank Trailer",
        "1PT": "Trailmobile Trailer Corporation",
        "1PY": "John Deere USA",
        "1RF": "Roadmaster, Monaco Coach Corporation",
        "1RN": "Reitnouer",
        "1S1": "Strick Trailers",
        "1ST": "Airstream",
        "1T7": "Thomas Built Buses",
        "1T8": "Thomas Built Buses",
        "1TC": "Coachmen Recreational Vehicle Co., LLC",
        "1TD": "Transcraft Corporation",
        "1TK": "Trail King",
        "1TU": "Transportation Manufacturing Corporation",
        "1UJ": "Jayco, Inc.",
        "1UT": "AM General military trucks, Jeep DJ",
        "1UY": "Utility Trailer",
        "1V1": "Volkswagen truck",
        "1V2": "Volkswagen SUV",
        "1VH": "Orion Bus Industries",
        "1VW": "Volkswagen car",
        "1W1": "Wilson Trailer",
        "1W8": "Witzco",
        "1WT": "Winnebago Industries",
        "1WU": "White Motor Company truck",
        "1XA": "Excalibur Automobile Corporation",
        "1XK": "Kenworth truck",
        "1XM": "Renault Alliance/GTA/Encore 1984–1987",
        "1XP": "Peterbilt truck",
        "1Y1": "Chevrolet/Geo car",
        "1YJ": "Rokon International, Inc.",
        "1YV": "Mazda",
        "1ZV": "Ford",
        "1ZW": "Mercury",
        "2A3": "Imperial",
        "2B1": "Orion Bus Industries",
        "2B3": "Dodge car 1981–2011",
        "2B4": "Dodge MPV 1981–2002",
        "2B5": "Dodge \"bus\" (van with more than 3 rows of seats) 1981–2002",
        "2B6": "Dodge incomplete vehicle 1981–2002",
        "2B7": "Dodge truck 1981–2002",
        "2BC": "Jeep Wrangler (YJ) 1987–1988",
        "2BP": "Ski-Doo",
        "2BV": "Can-Am & Bombardier ATV",
        "2BW": "Can-Am Commander E LSV",
        "2BX": "Can-Am Spyder",
        "2BZ": "Can-Am Freedom Trailer for Can-Am Spyder",
        "2C1": "Geo/Chevrolet car",
        "2C3": "Chrysler Group (all brands) car (including Lancia) 2012-",
        "2C4": "Chrysler brand MPV/SUV 2000–2005",
        "2C7": "Pontiac car",
        "2C8": "Chrysler brand MPV/SUV 2001–2005",
        "2CC": "American Motors Corporation MPV",
        "2CG": "Asüna/Pontiac SUV",
        "2CK": "Pontiac Torrent SUV",
        "2CM": "American Motors Corporation car",
        "2CN": "Geo/Chevrolet SUV",
        "2CT": "GMC Terrain SUV",
        "2D4": "Dodge MPV 2003–2011 only",
        "2D6": "Dodge incomplete vehicle 2003",
        "2D7": "Dodge truck 2003",
        "2D8": "Dodge MPV 2003–2011 only",
        "2DG": "Ontario Drive & Gear",
        "2DM": "Di-Mond Trailers",
        "2DN": "Dynasty Electric Car Corporation",
        "2E3": "Eagle car 1989–1997",
        "2E4": "2011 Lancia MPV",
        "2EZ": "Electra Meccanica Vehicles Corp.",
        "2FA": "Ford car",
        "2FH": "Zenn Motor Co., Ltd.",
        "2FM": "Ford MPV/SUV",
        "2FT": "Ford truck",
        "2FU": "Freightliner",
        "2FV": "Freightliner",
        "2FW": "Sterling Trucks",
        "2FY": "New Flyer",
        "2FZ": "Sterling Trucks",
        "2G0": "GMC \"bus\" (van with more than 3 rows of seats) 1981–1986",
        "2G1": "Chevrolet car",
        "2G2": "Pontiac car",
        "2G3": "Oldsmobile car",
        "2G4": "Buick car",
        "2G5": "Chevrolet BrightDrop / BrightDrop Zevo truck 2023-",
        "2G6": "Cadillac car",
        "2G7": "Pontiac car only sold by GM Canada",
        "2G8": "Chevrolet MPV 1981–1986",
        "2GA": "Chevrolet \"bus\"",
        "2GB": "Chevrolet incomplete vehicles",
        "2GC": "Chevrolet truck",
        "2GD": "GMC incomplete vehicles",
        "2GE": "Cadillac incomplete vehicle",
        "2GH": "GMC GM New Look bus & GM Classic series bus",
        "2GJ": "GMC \"bus\" (van with more than 3 rows of seats) 1987–",
        "2GK": "GMC MPV/SUV 1987–",
        "2GN": "Chevrolet MPV/SUV 1987-",
        "2GT": "GMC truck",
        "2HG": "Honda car",
        "2HH": "Acura car",
        "2HJ": "Honda truck",
        "2HK": "Honda MPV/SUV",
        "2HM": "Hyundai Canada",
        "2HN": "Acura SUV",
        "2HS": "International Trucks truck",
        "2HT": "International Trucks incomplete vehicle",
        "2J4": "Jeep Wrangler (YJ) 1989–1992",
        "2L1": "Lincoln incomplete vehicle – limo",
        "2LD": "Triple E Canada Ltd.",
        "2LJ": "Lincoln incomplete vehicle – hearse",
        "2LM": "Lincoln SUV",
        "2LN": "Lincoln car",
        "2M1": "Mack Trucks",
        "2M2": "Mack Trucks",
        "2ME": "Mercury car",
        "2MG": "Motor Coach Industries",
        "2MH": "Mercury incomplete vehicle",
        "2MR": "Mercury MPV",
        "2NK": "Kenworth incomplete vehicle",
        "2NP": "Peterbilt incomplete vehicle",
        "2NV": "Nova Bus",
        "2P3": "Plymouth car",
        "2P4": "Plymouth MPV 1981–2000",
        "2P5": "Plymouth \"bus\" (van with more than 3 rows of seats) 1981–1983",
        "2PC": "Prevost 1996-",
        "2S2": "Suzuki car",
        "2S3": "Suzuki SUV",
        "2T1": "Toyota car",
        "2T2": "Lexus SUV",
        "2T3": "Toyota SUV",
        "2TU": "Tri-Star Industries Limited",
        "2V4": "Volkswagen Routan",
        "2V8": "Volkswagen Routan",
        "2WK": "Western Star truck",
        "2WL": "Western Star incomplete vehicle",
        "2WM": "Western Star incomplete vehicle",
        "2XK": "Kenworth truck",
        "2XM": "Eagle Premier 1988 only",
        "2XP": "Peterbilt truck",
        "3AK": "Freightliner Trucks",
        "3AL": "Freightliner Trucks",
        "3AW": "Fruehauf de Mexico",
        "3AX": "Scania Mexico",
        "3B3": "Dodge car 1981–2011",
        "3B4": "Dodge SUV 1986–1993",
        "3B6": "Dodge incomplete vehicle 1981–2002",
        "3B7": "Dodge truck 1981–2002",
        "3BE": "Scania Mexico",
        "3BJ": "Western Star 3700 truck",
        "3BK": "Kenworth incomplete vehicle",
        "3BM": "Motor Coach Industries bus",
        "3BP": "Peterbilt incomplete vehicle",
        "3C3": "Chrysler Group (all brands) car (including Fiat) 2012-",
        "3C4": "Chrysler Group (all brands) MPV (including Fiat) 2012-",
        "3C6": "Chrysler Group (all brands) truck 2012–",
        "3C7": "Chrysler Group (all brands) incomplete vehicle 2012–",
        "3C8": "Chrysler brand MPV 2001–2005",
        "3CA": "Chrysler brand MPV 2001",
        "3CE": "Volvo Buses de Mexico",
        "3CG": "KTMMEX S.A. de C.V.",
        "3CZ": "Honda SUV",
        "3D2": "Dodge incomplete vehicle 2007–2009",
        "3D3": "Dodge truck 2006–2009",
        "3D4": "Dodge SUV 2009–2011",
        "3D6": "Dodge incomplete vehicle 2003–2011",
        "3D7": "Dodge truck 2002–2011",
        "3E4": "2011 Fiat SUV",
        "3EL": "ATRO",
        "3F6": "Sterling Bullet",
        "3FA": "Ford car",
        "3FC": "Ford stripped chassis",
        "3FE": "Ford Mexico",
        "3FM": "Ford MPV/SUV",
        "3FN": "Ford F-650/F-750",
        "3FR": "Ford F-650/F-750 & Ford LCF",
        "3FT": "Ford truck",
        "3G0": "Holden Equinox 2018–2020",
        "3G1": "Chevrolet car",
        "3G2": "Pontiac car",
        "3G4": "Buick car",
        "3G5": "Buick SUV",
        "3G7": "Pontiac SUV",
        "3GA": "JAC models assembled by Giant Motors in Mexico",
        "3GC": "Chevrolet truck",
        "3GK": "GMC SUV",
        "3GM": "Holden Suburban",
        "3GN": "Chevrolet SUV",
        "3GP": "Honda Prologue EV",
        "3GS": "Saturn SUV",
        "3GT": "GMC truck",
        "3GY": "Cadillac SUV",
        "3H1": "Honda motorcycle/UTV",
        "3H3": "Hyundai de Mexico, S.A. de C.V. for Hyundai Translead",
        "3HA": "International Trucks incomplete vehicle",
        "3HC": "International Trucks truck",
        "3HD": "Acura SUV",
        "3HG": "Honda car",
        "3HS": "International Trucks & Caterpillar Trucks truck",
        "3HT": "International Trucks & Caterpillar Trucks incomplete vehicle",
        "3HV": "International incomplete bus",
        "3JB": "BRP Mexico",
        "3KM": "Kia/Hyundai MPV/SUV",
        "3KP": "Kia/Hyundai car",
        "3LN": "Lincoln car",
        "3MA": "Mercury car",
        "3MD": "Mazda de Mexico car",
        "3ME": "Mercury car",
        "3MF": "BMW M car",
        "3MG": "Isuzu Motors de Mexico",
        "3MJ": "Mazda CX-3",
        "3MV": "Mazda de Mexico SUV",
        "3MW": "BMW car",
        "3MY": "Toyota car",
        "3MZ": "Mazda de Mexico car",
        "3N1": "Nissan Mexico car",
        "3N6": "Nissan Mexico truck & Chevrolet City Express",
        "3N8": "Nissan Mexico MPV",
        "3NE": "Polaris Industries UTV",
        "3NS": "Polaris Industries ATV",
        "3P3": "Plymouth car",
        "3PC": "Infiniti SUV",
        "3TM": "Toyota truck",
        "3TY": "Toyota truck",
        "3VV": "Volkswagen Mexico SUV",
        "3VW": "Volkswagen Mexico car",
        "3WK": "Kenworth truck",
        "3WP": "Peterbilt truck",
        "43C": "Consulier",
        "44K": "HME Inc. (fire engines - incomplete vehicle",
        "46G": "Gillig incomplete vehicle",
        "46J": "Federal Motors Inc",
        "478": "Honda ATV",
        "480": "Sterling Trucks",
        "49H": "Sterling Trucks incomplete vehicle",
        "4A3": "Mitsubishi Motors car",
        "4A4": "Mitsubishi Motors SUV",
        "4B3": "Dodge car",
        "4C3": "Chrysler car",
        "4C6": "Reinke Manufacturing Company",
        "4CD": "Oshkosh Chassis Division incomplete vehicle",
        "4DR": "IC Bus",
        "4E3": "Eagle car",
        "4EN": "E-ONE, Inc.",
        "4F2": "Mazda SUV",
        "4F4": "Mazda truck",
        "4G1": "Chevrolet Cavalier convertible",
        "4G2": "Pontiac Sunfire convertible",
        "4G3": "Toyota Cavalier",
        "4G5": "General Motors EV1",
        "4GD": "Opel/Vauxhall Sintra",
        "4GL": "Buick incomplete vehicle",
        "4GT": "Isuzu incomplete vehicle built by GM",
        "4J8": "LBT, Inc.",
        "4JG": "Mercedes-Benz SUV",
        "4KB": "Chevrolet W-Series incomplete vehicle",
        "4KD": "GMC W-Series incomplete vehicle",
        "4KE": "U.S. Electricar Consulier",
        "4KL": "Isuzu N-Series incomplete vehicle (gas engine only) built by GM",
        "4LM": "Capacity of Texas",
        "4M2": "Mercury MPV/SUV",
        "4MB": "Mitsubishi Motors",
        "4ML": "Oshkosh Trailer Division",
        "4MZ": "Buell Motorcycle Company",
        "4N2": "Nissan Quest",
        "4NU": "Isuzu Ascender",
        "4P1": "Pierce Manufacturing Inc. USA",
        "4P3": "Mitsubishi Motors SUV",
        "4RK": "Nova Bus & Prevost",
        "4S1": "Isuzu truck",
        "4S2": "Isuzu SUV",
        "4S3": "Subaru car",
        "4S4": "Subaru SUV/MPV",
        "4S6": "Honda SUV",
        "4S7": "Spartan Motors incomplete vehicle",
        "4T1": "Toyota car",
        "4T3": "Toyota MPV/SUV",
        "4T4": "Toyota car",
        "4TA": "Toyota truck",
        "4UF": "Arctic Cat Inc.",
        "4US": "BMW car",
        "4V0": "Crossroads RV",
        "4V1": "WhiteGMC truck",
        "4V2": "WhiteGMC incomplete vehicle",
        "4V3": "Volvo truck",
        "4V4": "Volvo Trucks North America truck",
        "4V5": "Volvo Trucks North America incomplete vehicle",
        "4V6": "Volvo truck",
        "4VA": "Volvo Trucks North America truck",
        "4VE": "Volvo Trucks North America incomplete vehicle",
        "4VG": "Volvo Trucks North America truck",
        "4VH": "Volvo Trucks North America incomplete vehicle",
        "4VM": "Volvo Trucks North America incomplete vehicle",
        "4VZ": "Spartan Motors/The Shyft Group incomplete vehicle – bare chassis only",
        "4W1": "'24+ Chevrolet Suburban HD",
        "4W5": "Acura ZDX EV",
        "4WW": "Wilson Trailer Sales",
        "4X4": "Forest River",
        "4XA": "Polaris Inc.",
        "4YD": "KeyStone RV Company",
        "4YM": "Anderson Manufacturing",
        "4Z3": "American LaFrance truck",
        "50E": "Lucid Motors passenger car",
        "50G": "Karma Automotive",
        "516": "Autocar truck",
        "51R": "Brammo Motorcycles",
        "522": "GreenGo Tek",
        "523": "VPG",
        "52C": "GEM subsidiary of Polaris Inc.",
        "537": "Azure Dynamics Transit Connect Electric",
        "538": "Zero Motorcycles",
        "53G": "Coda Automotive",
        "53T": "Think North America in Elkhart, IN",
        "546": "EBR",
        "54C": "Winnebago Industries travel trailer",
        "54D": "Isuzu & Chevrolet commercial trucks built by Spartan Motors/The Shyft Group",
        "54F": "Rosenbauer",
        "55S": "Mercedes-Benz car",
        "56K": "Indian Motorcycle International, LLC",
        "573": "Grand Design RV",
        "57C": "Maurer Manufacturing",
        "57R": "Oreion Motors",
        "57S": "Lightning Motors Corp.",
        "57W": "Mobility Ventures",
        "57X": "Polaris Slingshot",
        "58A": "Lexus car",
        "5A4": "Load Rite Trailers Inc.",
        "5AS": "Global Electric Motorcars (GEM) 1999-2011",
        "5AX": "Armor Chassis",
        "5B4": "Workhorse Custom Chassis, LLC incomplete vehicle",
        "5BP": "Solectria",
        "5BZ": "Nissan \"bus\"",
        "5CD": "Indian Motorcycle Company of America",
        "5CX": "Shelby Series 1",
        "5DF": "Thomas Dennis Company LLC",
        "5DG": "Terex Advance Mixer",
        "5EH": "Excelsior-Henderson Motorcycle",
        "5EO": "Cottrell",
        "5FC": "Columbia Vehicle Group (Columbia, Tomberlin",
        "5FN": "Honda MPV/SUV",
        "5FP": "Honda truck",
        "5FR": "Acura SUV",
        "5FT": "Feeling Trailers",
        "5FY": "New Flyer",
        "5G8": "Holden Volt",
        "5GA": "Buick MPV/SUV",
        "5GD": "Daewoo G2X",
        "5GN": "Hummer H3T",
        "5GR": "Hummer H2",
        "5GT": "Hummer H3",
        "5GZ": "Saturn MPV/SUV",
        "5HD": "Harley-Davidson for export markets",
        "5HT": "Heil Trailer",
        "5J5": "Club Car",
        "5J6": "Honda SUV",
        "5J8": "Acura SUV",
        "5KB": "Honda car",
        "5KJ": "Western Star Trucks truck",
        "5KK": "Western Star Trucks truck",
        "5KM": "Vento Motorcycles",
        "5KT": "Karavan Trailers",
        "5L1": "Lincoln SUV - Limousine",
        "5L5": "American IronHorse Motorcycle",
        "5LD": "Ford & Lincoln incomplete vehicle – limousine",
        "5LM": "Lincoln SUV",
        "5LT": "Lincoln truck",
        "5MZ": "Buell Motorcycle Company for export markets",
        "5N1": "Nissan & Infiniti SUV",
        "5N3": "Infiniti SUV",
        "5NH": "Forest River",
        "5NM": "Hyundai SUV",
        "5NP": "Hyundai car",
        "5NT": "Hyundai truck",
        "5PV": "Hino incomplete vehicle",
        "5RJ": "Android Industries LLC",
        "5RX": "Heartland Recreational Vehicles",
        "5S3": "Saab 9-7X",
        "5SA": "Suzuki Manufacturing of America Corp.",
        "5SX": "American LaFrance incomplete vehicle",
        "5TB": "Toyota truck",
        "5TD": "Toyota MPV/SUV & Lexus TX",
        "5TE": "Toyota truck",
        "5TF": "Toyota truck",
        "5TU": "Construction Trailer Specialist",
        "5UM": "BMW M car",
        "5UX": "BMW SUV",
        "5V8": "Vanguard National",
        "5VC": "Autocar incomplete vehicle",
        "5VF": "American Electric Vehicle Company",
        "5VP": "Victory Motorcycles",
        "5WE": "IC Bus incomplete vehicle",
        "5XX": "Kia car",
        "5XY": "Kia/Hyundai SUV",
        "5Y2": "Pontiac Vibe",
        "5Y4": "Yamaha Motor Motor Mfg. Corp. of America",
        "5YA": "Indian Motorcycle Company",
        "5YF": "Toyota car",
        "5YJ": "Tesla, Inc. passenger car",
        "5YM": "BMW M SUV",
        "5YN": "Cruise Car, Inc.",
        "5Z6": "Suzuki Equator",
        "5ZT": "Forest River",
        "5ZU": "Greenkraft",
        "6AB": "MAN Australia",
        "6AM": "Jayco Corp.",
        "6F1": "Ford",
        "6F2": "Iveco Trucks Australia Ltd.",
        "6F4": "Nissan Motor Company Australia",
        "6F5": "Kenworth Australia",
        "6FM": "Mack Trucks Australia",
        "6FP": "Ford Australia",
        "6G1": "General Motors-Holden (post Nov 2002) & Chevrolet & Vauxhall Monaro & VXR8",
        "6G2": "Pontiac Australia",
        "6G3": "General Motors Chevrolet Caprice PPV & SS performance sedan 2014-2017",
        "6H8": "General Motors-Holden",
        "6KT": "BCI Bus",
        "6MM": "Mitsubishi Motors Australia",
        "6MP": "Mercury Capri 1991-1994",
        "6T1": "Toyota Motor Corporation Australia",
        "6T9": "Privately Imported car (VIN issued by Victoria) or Trailer in Australia",
        "6U9": "Privately Imported car in Australia",
        "6ZZ": "Privately Imported car in Australia",
        "722": "Isuzu North America Corp.",
        "7A1": "Mitsubishi New Zealand",
        "7A3": "Honda New Zealand",
        "7A4": "Toyota New Zealand",
        "7A5": "Ford New Zealand",
        "7A7": "Nissan New Zealand",
        "7AB": "MAN New Zealand",
        "7B2": "Nissan Diesel bus New Zealand",
        "7F7": "Arcimoto, Inc.",
        "7FA": "Honda SUV",
        "7FC": "Rivian truck",
        "7G0": "Faraday Future",
        "7G2": "Tesla, Inc. truck",
        "7GZ": "GMC incomplete vehicles",
        "7H4": "Hino truck",
        "7H8": "Cenntro Electric Group Limited low-speed vehicle",
        "7JD": "Volvo Cars SUV",
        "7JR": "Volvo Cars passenger car",
        "7JZ": "Proterra From mid-2019 on",
        "7KG": "Vanderhall Motor Works",
        "7KY": "Dorsey",
        "7MM": "Mazda SUV",
        "7MU": "Toyota SUV",
        "7MW": "Cenntro Electric Group Limited truck",
        "7MZ": "HDK electric vehicles",
        "7NA": "Navistar Defense",
        "7NY": "Lordstown Motors",
        "7PD": "Rivian SUV",
        "7RZ": "Electric Last Mile Solutions",
        "7SA": "Tesla, Inc. (US-built MPVs (e.g. Model X, Model Y)",
        "7SU": "Blue Arc electric trucks",
        "7SV": "Toyota SUV",
        "7SX": "Global Electric Motorcars (WAEV) 2022-",
        "7SY": "Polestar SUV",
        "7TN": "Canoo",
        "7UU": "Lucid Motors MPV/SUV",
        "7UZ": "Kaufman Trailers",
        "7VV": "Ree Automotive",
        "7WE": "Bollinger Motors incomplete vehicle",
        "7YA": "Hyundai MPV/SUV",
        "7Z0": "Zoox",
        "829": "Industrias Quantum Motors S.A.",
        "8A1": "Renault Argentina",
        "8A3": "Scania Argentina",
        "8AB": "Mercedes Benz truck & bus",
        "8AC": "Mercedes Benz vans",
        "8AD": "Peugeot Argentina",
        "8AE": "Peugeot van",
        "8AF": "Ford Argentina",
        "8AG": "Chevrolet Argentina",
        "8AJ": "Toyota Argentina",
        "8AK": "Suzuki Argentina",
        "8AN": "Nissan Argentina",
        "8AP": "Fiat Argentina",
        "8AT": "Iveco Argentina",
        "8AW": "Volkswagen Argentina",
        "8BB": "Agrale Argentina S.A.",
        "8BC": "Citroën Argentina",
        "8BN": "Mercedes-Benz incomplete vehicle",
        "8BR": "Mercedes-Benz \"bus\" (van with more than 3 rows of seats",
        "8BT": "Mercedes-Benz MPV (van with 2 or 3 rows of seats",
        "8BU": "Mercedes-Benz truck (cargo van with 1 row of seats",
        "8C3": "Honda car/SUV",
        "8CH": "Honda motorcycle",
        "8G1": "Automotores Franco Chilena S.A. Renault",
        "8GD": "Automotores Franco Chilena S.A. Peugeot",
        "8GG": "Chevrolet Chile",
        "8L4": "Great Wall Motors",
        "8LD": "General Motors OBB - Chevrolet Ecuador",
        "8LF": "Maresa",
        "8LG": "Aymesa",
        "8XD": "Ford Motor Venezuela",
        "8XJ": "Mack de Venezuela C.A.",
        "8XV": "Iveco Venezuela C.A.",
        "8Z1": "General Motors Venezolana C.A.",
        "92H": "Origem Brazil",
        "932": "Harley-Davidson Brazil",
        "935": "Citroën Brazil",
        "936": "Peugeot Brazil",
        "937": "Dodge Dakota",
        "93C": "Chevrolet SUV [Tracker] or pickup [Tornado, Montana, S10]",
        "93H": "Honda Brazil car/SUV",
        "93K": "Volvo Trucks",
        "93P": "Volare",
        "93R": "Toyota Brazil",
        "93S": "Navistar International",
        "93U": "Audi Brazil 1999–2006",
        "93V": "Navistar International",
        "93W": "Fiat Ducato",
        "93X": "Souza Ramos – Mitsubishi Motors / Suzuki Jimny",
        "93Y": "Renault Brazil",
        "93Z": "Iveco",
        "94D": "Nissan Brazil",
        "94N": "RWM Brazil",
        "94T": "Troller Veículos Especiais",
        "953": "VW Truck & Bus / MAN Truck & Bus",
        "95P": "CAOA Hyundai & CAOA Chery",
        "95V": "BMW motorcycles assembled by Dafra Motos 2009–2016",
        "95Z": "Buell Motorcycle Company assembled by Harley-Davidson Brazil",
        "96P": "Kawasaki",
        "97N": "Triumph Motorcycles Ltd.",
        "988": "Jeep, Ram [Rampage], and Fiat [Toro]",
        "98M": "BMW car/SUV",
        "98P": "DAF Trucks",
        "98R": "Chery",
        "99A": "Audi 2016-",
        "99H": "Shineray",
        "99J": "Jaguar Land Rover",
        "99K": "Haojue & Kymco assembled by JTZ Indústria e Comércio de Motos",
        "99L": "BYD",
        "99Z": "BMW Motorrad",
        "9BD": "Fiat Brazil & Dodge, Ram",
        "9BF": "Ford Brazil",
        "9BG": "Chevrolet Brazil",
        "9BH": "Hyundai Motor Brasil",
        "9BM": "Mercedes-Benz Brazil car, SUV, commercial truck & bus",
        "9BN": "Mafersa",
        "9BR": "Toyota Brazil",
        "9BS": "Scania Brazil",
        "9BV": "Volvo Trucks",
        "9BW": "Volkswagen Brazil",
        "9BY": "Agrale S.A.",
        "9C2": "Moto Honda Da Amazonia Ltda.",
        "9C6": "Yamaha Motor Da Amazonia Ltda.",
        "9CD": "Suzuki (motorcycles) assembled by J. Toledo Motos do Brasil",
        "9DF": "Puma",
        "9DW": "Kenworth & Peterbilt trucks",
        "9EZ": "homemade or handbuilt vehicles",
        "9FB": "Renault Colombia",
        "9FC": "Compañía Colombiana Automotriz S.A.",
        "9GA": "Chevrolet Colombia",
        "9UJ": "Chery assembled by Chery Socma S.A.",
        "9UK": "Lifan",
        "9UT": "Dongfeng trucks",
        "9UW": "Kia",
        "9V7": "Citroen",
        "9V8": "Peugeot",
        "9VC": "Fiat",
        "AAA": "Audi South Africa",
        "AAK": "FAW Vehicle Manufacturers SA (PTY) Ltd.",
        "AAM": "MAN Automotive (South Africa) (Pty) Ltd.",
        "AAP": "VIN restamped by South African Police Service",
        "AAV": "Volkswagen South Africa",
        "AAW": "Challenger Trailer Pty Ltd.",
        "ABJ": "Mitsubishi Fuso",
        "ABM": "BMW Southern Africa",
        "AC5": "Hyundai Automotive South Africa",
        "ACV": "Isuzu Motors South Africa 2018-",
        "ADB": "Mercedes-Benz South Africa car",
        "ADD": "UD Trucks Southern Africa (Pty) Ltd.",
        "ADM": "General Motors South Africa",
        "ADN": "Nissan South Africa (Pty) Ltd.",
        "ADR": "Renault Sandero",
        "ADX": "Tata Automobile Corporation (SA) Ltd.",
        "AFA": "Ford Motor Company of Southern Africa & Samcor",
        "AFB": "Mazda BT-50",
        "AFD": "BAIC Automotive South Africa",
        "AFZ": "Fiat Auto South Africa",
        "AHH": "Hino South Africa",
        "AHM": "Honda Ballade",
        "AHT": "Toyota South Africa Motors (Pty.) Ltd.",
        "BR1": "Mercedes-Benz Algeria",
        "BRY": "FIAT Algeria",
        "BUK": "Kiira Motors Corporation, Uganda",
        "CA3": "MCV bus",
        "DDY": "Geyushi Motors (bus",
        "EAA": "Aurus Motors",
        "EAN": "Evolute",
        "EAU": "Elektromobili Manufacturing Rus - EVM",
        "EBE": "Sollers-Auto",
        "EBZ": "Nizhekotrans bus",
        "ECE": "XCITE",
        "ECW": "Trans-Alfa bus",
        "H0D": "Taizhou Qianxin Vehicle Co., Ltd.",
        "H0G": "Wisdom (Fujian) Motor Co., Ltd.",
        "HA0": "Wuxi Sundiro Electric Vehicle Co., Ltd.",
        "HA6": "Niu Technologies",
        "HA7": "Jinan Qingqi KR Motors Co., Ltd.",
        "HES": "smart Automobile Co., Ltd.",
        "HGL": "Farizon Auto van",
        "HGX": "Wuling Motors commercial vehicle",
        "HHZ": "Huazi Automobile",
        "HJ4": "BAW car",
        "HJN": "Firefly",
        "HJR": "Chery Commercial Vehicle (Anhui) Co., Ltd. Jetour",
        "HJZ": "Juzhen Chengshi van",
        "HL4": "Zhejiang Morini Vehicle Co., Ltd.",
        "HLX": "Li Auto",
        "HRV": "Beijing Henrey Automobile Technology Co., Ltd.",
        "HVW": "Volkswagen Anhui",
        "HWM": "WM Motor Technology Co., Ltd.",
        "HXM": "Xiaomi",
        "HZ2": "Taizhou Zhilong Technology Co., Ltd",
        "J81": "Chevrolet/Geo car",
        "J87": "Pontiac/Asüna car",
        "J8B": "Chevrolet commercial trucks",
        "J8C": "Chevrolet commercial trucks",
        "J8D": "GMC commercial trucks",
        "J8T": "GMC commercial trucks",
        "J8Z": "Chevrolet LUV pickup truck",
        "JA3": "Mitsubishi car",
        "JA4": "Mitsubishi MPV/SUV (for North America) & Nissan Rogue PHEV '26",
        "JA7": "Mitsubishi truck",
        "JAA": "Isuzu truck, Holden Rodeo TF, Opel Campo, Bedford/Vauxhall Brava pickup",
        "JAB": "Isuzu car",
        "JAC": "Isuzu SUV, Opel/Vauxhall Monterey & Holden Jackaroo/Monterey",
        "JAE": "Acura SLX",
        "JAL": "Isuzu commercial trucks & Chevrolet commercial trucks",
        "JAM": "Isuzu commercial trucks",
        "JB3": "Dodge car",
        "JB4": "Dodge MPV/SUV",
        "JB7": "Dodge truck",
        "JC0": "Ford brand cars",
        "JC1": "Fiat 124 Spider",
        "JC2": "Ford Courier",
        "JD1": "Daihatsu car",
        "JD2": "Daihatsu SUV",
        "JD4": "Daihatsu truck",
        "JDA": "Daihatsu, Subaru Justy",
        "JE3": "Eagle car",
        "JE4": "Mitsubishi Motors",
        "JF1": "Subaru car",
        "JF2": "Subaru SUV",
        "JF3": "Subaru truck",
        "JF4": "Saab 9-2X",
        "JG1": "Chevrolet/Geo car",
        "JG2": "Pontiac car",
        "JG7": "Pontiac/Asuna car",
        "JGC": "Chevrolet/Geo SUV",
        "JGT": "GMC SUV",
        "JH1": "Honda truck",
        "JH2": "Honda motorcycle/ATV",
        "JH3": "Honda ATV",
        "JH4": "Acura car",
        "JH6": "Hino incomplete vehicle",
        "JHA": "Hino truck",
        "JHB": "Hino incomplete vehicle",
        "JHD": "Hino",
        "JHF": "Hino",
        "JHH": "Hino incomplete vehicle",
        "JHL": "Honda MPV/SUV",
        "JHM": "Honda car",
        "JJ3": "Chrysler brand car",
        "JK8": "Suzuki QUV620F UTV",
        "JKA": "Kawasaki",
        "JKB": "Kawasaki",
        "JKM": "Mitsuoka",
        "JKS": "Suzuki Marauder 1600/Boulevard M95 motorcycle",
        "JL5": "Mitsubishi Fuso Truck & Bus Corp.",
        "JL6": "Mitsubishi Fuso Truck & Bus Corp.",
        "JL7": "Mitsubishi Fuso Truck & Bus Corp.",
        "JLB": "Mitsubishi Fuso Truck & Bus Corp.",
        "JLF": "Mitsubishi Fuso Truck & Bus Corp.",
        "JLS": "Sterling Truck 360",
        "JM0": "Mazda for Oceania export",
        "JM1": "Mazda car",
        "JM2": "Mazda truck",
        "JM3": "Mazda MPV/SUV",
        "JM4": "Mazda",
        "JM6": "Mazda",
        "JM7": "Mazda",
        "JMA": "Mitsubishi Motors (right-hand drive) for Europe",
        "JMB": "Mitsubishi Motors (left-hand drive) for Europe",
        "JMF": "Mitsubishi Motors for Australia (including Mitsubishi Express",
        "JMP": "Mitsubishi Motors",
        "JMR": "Mitsubishi Motors",
        "JMY": "Mitsubishi Motors (left-hand drive) for South America & Middle East",
        "JMZ": "Mazda for Europe export & Mazda 2",
        "JN1": "Nissan car & Infiniti car",
        "JN3": "Nissan incomplete vehicle",
        "JN6": "Nissan truck/van & Mitsubishi Fuso Canter Van",
        "JN8": "Nissan MPV/SUV & Infiniti SUV",
        "JNA": "Nissan Diesel/UD Trucks incomplete vehicle",
        "JNC": "Nissan Diesel/UD Trucks",
        "JNE": "Nissan Diesel/UD Trucks truck",
        "JNK": "Infiniti car",
        "JNR": "Infiniti SUV",
        "JNX": "Infiniti incomplete vehicle",
        "JP3": "Plymouth car",
        "JP4": "Plymouth MPV/SUV",
        "JP7": "Plymouth truck",
        "JPC": "Nissan Diesel/UD Trucks",
        "JR2": "Isuzu Oasis",
        "JS1": "Suzuki motorcycle & Kawasaki KLX400S/KLX400SR motorcycle",
        "JS2": "Suzuki car",
        "JS3": "Suzuki SUV",
        "JS4": "Suzuki truck",
        "JSA": "Suzuki ATV & '03 Kawasaki KFX400 ATV",
        "JSK": "Kawasaki KLX125/KLX125L motorcycle",
        "JSL": "'04-'06 Kawasaki KFX400 ATV",
        "JST": "Suzuki Across SUV",
        "JT1": "Toyota van",
        "JT2": "Toyota car",
        "JT3": "Toyota MPV/SUV",
        "JT4": "Toyota truck/van",
        "JT5": "Toyota incomplete vehicle",
        "JT6": "Lexus SUV",
        "JT7": "Toyota bus/van",
        "JT8": "Lexus car",
        "JTB": "Toyota bus",
        "JTD": "Toyota car",
        "JTE": "Toyota MPV/SUV",
        "JTF": "Toyota van/truck",
        "JTG": "Toyota MPV/bus",
        "JTH": "Lexus car",
        "JTJ": "Lexus SUV",
        "JTK": "Toyota car",
        "JTL": "Toyota SUV",
        "JTM": "Toyota SUV, Subaru Solterra",
        "JTN": "Toyota car",
        "JTP": "Toyota SUV",
        "JW6": "Mitsubishi Fuso division of Mitsubishi Motors",
        "JY3": "Yamaha 3-wheel ATV",
        "JY4": "Yamaha 4-wheel ATV",
        "JYA": "Yamaha motorcycles",
        "JYE": "Yamaha snowmobile",
        "KF3": "Merkavim",
        "KF6": "Automotive Industries, Ltd.",
        "KL1": "GM Daewoo/GM Korea",
        "KL2": "Daewoo/GM Daewoo",
        "KL3": "GM Daewoo/GM Korea",
        "KL4": "GM Korea",
        "KL5": "GM Daewoo",
        "KL6": "GM Daewoo",
        "KL7": "GM Daewoo/GM Korea (Chevrolet MPV/SUV (Post-2000)",
        "KL8": "GM Daewoo/GM Korea (Chevrolet car from Changwon plant (Spark)",
        "KLA": "Daewoo/GM Daewoo/GM Korea (Chevrolet/Alpheon) from Bupyeong & Kunsan plants",
        "KLP": "CT & T United",
        "KLT": "Tata Daewoo",
        "KLU": "Tata Daewoo",
        "KLY": "Daewoo/GM Daewoo/GM Korea (Chevrolet) from Changwon plant",
        "KM1": "Hyosung Motors",
        "KM4": "Hyosung Motors/S & T Motors/KR Motors",
        "KM8": "Hyundai SUV",
        "KMC": "Hyundai commercial truck",
        "KME": "Hyundai commercial truck",
        "KMF": "Hyundai van & commercial truck & Bering Truck",
        "KMH": "Hyundai car & Mexican market Dodges",
        "KMJ": "Hyundai minibus/bus",
        "KMT": "Genesis Motor car",
        "KMU": "Genesis Motor SUV",
        "KMX": "Hyundai Galloper SUV",
        "KMY": "Daelim Motor Company, Ltd/DNA Motors Co., Ltd.",
        "KN1": "Asia Motors",
        "KN2": "Asia Motors",
        "KNA": "Kia car",
        "KNC": "Kia truck",
        "KND": "Kia MPV/SUV & Hyundai Entourage",
        "KNE": "Kia for Europe export",
        "KNF": "Kia, special vehicles",
        "KNG": "Kia minibus/bus",
        "KNJ": "Ford Festiva & Aspire",
        "KNM": "Renault Korea Co., Ltd.",
        "KPA": "SsangYong/KG Mobility (KGM) pickup",
        "KPB": "SsangYong car",
        "KPD": "SsangYong TransStar",
        "KPH": "Mitsubishi Precis",
        "KPT": "SsangYong/KG Mobility (KGM) SUV/MPV",
        "L10": "Geely Emgrand",
        "L1K": "Chongqing Hengtong Bus Co., Ltd.",
        "L1N": "XPeng Motors",
        "L2B": "Jiangsu Baodiao Locomotive Co., Ltd.",
        "L2C": "Chery Jaguar Land Rover",
        "L37": "Huzhou Daixi Zhenhua Technology Trade Co., Ltd.",
        "L3H": "Shanxi Victory Automobile Manufacturing Co., Ltd.",
        "L4B": "Xingyue Group",
        "L4F": "Suzhou Eagle Electric Vehicle Manufacturing Co., Ltd.",
        "L4H": "Ningbo Longjia Motorcycle Co., Ltd.",
        "L4S": "Zhejiang Xingyue Vehicle Co Ltd.",
        "L5C": "Zhejiang Kangdi Vehicles Co., Ltd.",
        "L5E": "Zoomlion Heavy Industry Science & Technology Co., Ltd.",
        "L5K": "Zhejiang Yongkang Easy Vehicle",
        "L5N": "Zhejiang Taotao",
        "L5Y": "Taizhou Zhongneng Motorcycle Co. Ltd.",
        "L66": "Zhuhai Granton Bus and Coach Co. Ltd.",
        "L6F": "Shandong Liangzi Power Co. Ltd.",
        "L6J": "Zhejiang Kayo Motor Co. Ltd.",
        "L6K": "Shanghai Howhit Machinery Manufacture Co. Ltd.",
        "L6T": "Geely, Lynk & Co, Zeekr",
        "L82": "Baotian",
        "L85": "Zhejiang Yongkang Huabao Electric Appliance",
        "L8A": "Jinhua Youngman Automobile Manufacturing Co., Ltd.",
        "L8X": "Zhejiang Summit Huawin Motorcycle",
        "L8Y": "Zhejiang Jonway Motorcycle Manufacturing Co., Ltd.",
        "L9G": "Zhuhai Guangtong Automobile Co., Ltd.",
        "L9N": "Zhejiang Taotao Vehicles Co., Ltd.",
        "LA6": "Xiamen King Long United Automotive Industry Co., Ltd.",
        "LA7": "Radar Auto",
        "LA8": "Anhui Ankai",
        "LAA": "Shanghai Jialing Vehicle Co., Ltd.",
        "LAE": "Jinan Qingqi Motorcycle",
        "LAL": "Sundiro Honda Motorcycle",
        "LAN": "Changzhou Yamasaki Motorcycle",
        "LAP": "Zhuzhou Nanfang Motorcycle Co., Ltd.",
        "LAT": "Luoyang Northern Ek Chor Motorcycle Co., Ltd.",
        "LB1": "Fujian Benz",
        "LB2": "Geely Motorcycles",
        "LB3": "Zhejiang Geely Holding Group",
        "LB4": "Chongqing Yinxiang Motorcycle Group Co., Ltd.",
        "LB5": "Foshan City Fosti Motorcycle Co., Ltd.",
        "LB7": "Tibet New Summit Motorcycle Co., Ltd.",
        "LBB": "Zhejiang Qianjiang Motorcycle",
        "LBE": "Beijing Hyundai",
        "LBM": "Zongshen Piaggio",
        "LBP": "Chongqing Jianshe Yamaha Motor Co. Ltd.",
        "LBV": "BMW Brilliance",
        "LBX": "Jiangsu Kinroad Xintian Motorcycle Manufacture Co. Ltd.",
        "LBZ": "Yantai Shuchi Vehicle Co., Ltd.",
        "LC0": "BYD Auto",
        "LC2": "Changzhou Kwang Yang Motor Co., Ltd.",
        "LC6": "Changzhou Haojue Suzuki Motorcycle Co. Ltd.",
        "LCE": "Hangzhou Chunfeng Motorcycles",
        "LCR": "Gonow",
        "LD3": "Guangdong Tayo Motorcycle Technology Co. (Zontes",
        "LD5": "Benzhou Vehicle Industry Group Ltd.",
        "LDB": "Dadi Auto",
        "LDD": "Dandong Huanghai Automobile",
        "LDF": "Dezhou Fulu Vehicle Co., Ltd. (motorcycles), BAW Yuanbao electric car",
        "LDK": "FAW Bus (Dalian) Co., Ltd.",
        "LDN": "Soueast (South East (Fujian) Motor Co., Ltd.) including Mitsubishi",
        "LDP": "Dongfeng, Dongfeng Fengshen (Aeolus), Voyah, Renault City K-ZE/Venucia e30",
        "LDY": "Zhongtong Bus Holding Co. Ltd.",
        "LE8": "Guangzhou Panyu Hua'Nan Motors Industry Co. Ltd.",
        "LEC": "Tianjin Qingyuan Electric Vehicle Co., Ltd.",
        "LEF": "Jiangling Motors Corporation Ltd.",
        "LEH": "Zhejiang Riya Motorcycle Co. Ltd.",
        "LET": "Jiangling-Isuzu Motors, China",
        "LEW": "Dongfeng commercial vehicle",
        "LF3": "Lifan Motorcycle",
        "LFA": "Ford Lio Ho Motor Co Ltd. old designation",
        "LFB": "FAW Group (Bestune, Hongqi) & Mazda made under license by FAW",
        "LFF": "Zhejiang Taizhou Wangye Power Co., Ltd.",
        "LFG": "Taizhou Chuanl Motorcycle Manufacturing",
        "LFJ": "Fujian Motors Group",
        "LFM": "FAW Toyota Motor",
        "LFN": "FAW Bus (Wuxi) Co., Ltd.",
        "LFP": "FAW Car, Bestune, Hongqi (passenger vehicles) & Mazda made under license by FAW",
        "LFT": "FAW",
        "LFU": "Lifeng Group Co., Ltd.",
        "LFV": "FAW-Volkswagen",
        "LFW": "FAW JieFang",
        "LFX": "Sany Heavy Industry",
        "LFY": "Changshu Light Motorcycle Factory",
        "LFZ": "Leapmotor",
        "LG6": "Dayun Group",
        "LGA": "Dongfeng Commercial Vehicle Co., Ltd. trucks",
        "LGB": "Dongfeng Commercial Vehicle Co., Ltd.",
        "LGC": "Dongfeng Commercial Vehicle Co., Ltd. bus chassis",
        "LGD": "Dongfeng Commercial Vehicle Co., Ltd.",
        "LGF": "Dongfeng Commercial Vehicle Co., Ltd. bus chassis",
        "LGG": "Dongfeng Liuzhou Motor",
        "LGJ": "Dongfeng Fengshen",
        "LGL": "Guilin Daewoo",
        "LGV": "Heshan Guoji Nanlian Motorcycle Industry Co., Ltd.",
        "LGW": "Great Wall Motor",
        "LGX": "BYD Auto",
        "LGZ": "Guangzhou Denway Bus",
        "LH0": "WM Motor Technology Co., Ltd.",
        "LH1": "FAW-Haima, China",
        "LHA": "Shuanghuan Auto",
        "LHB": "Beijing Automotive Industry Holding",
        "LHG": "GAC Honda",
        "LHJ": "Chongqing Astronautic Bashan Motorcycle Manufacturing Co., Ltd.",
        "LHM": "Dongfeng Renault Automobile Co.",
        "LHW": "CRRC Electric Vehicle Co., Ltd.",
        "LJ1": "Nio, Inc.",
        "LJ4": "Shanghai Jmstar Motorcycle Co., Ltd.",
        "LJ5": "Cixi Kingring Motorcycle Co., Ltd.",
        "LJ8": "Zotye Auto",
        "LJC": "Jincheng Corporation",
        "LJD": "Yueda Kia (previously Dongfeng Yueda Kia) (Kia, Horki) & Human Horizons - HiPhi",
        "LJM": "Sunlong",
        "LJN": "Zhengzhou Nissan",
        "LJR": "CIMC Vehicles Group",
        "LJS": "Yaxing Coach, Asiastar Bus",
        "LJU": "Lotus Technology",
        "LJV": "Sinotruk Chengdu Wangpai Commercial Vehicle Co., Ltd.",
        "LJW": "JMC Landwind",
        "LJX": "JMC Ford",
        "LK2": "Anhui JAC Bus",
        "LK6": "SAIC-GM-Wuling (Wuling, Baojun) microcars and other vehicles",
        "LK8": "Zhejiang Yule New Energy Automobile Technology Co., Ltd.",
        "LKC": "BAIC commercial vehicles, previously Changhe",
        "LKG": "Youngman Lotus Automobile Co., Ltd.",
        "LKH": "Hafei Motor",
        "LKL": "Higer Bus",
        "LKT": "Yunnan Lifan Junma Vehicle Co., Ltd. commercial vehicles",
        "LL0": "Sanmen County Yongfu Machine Co., Ltd.",
        "LL2": "WM Motor Technology Co., Ltd.",
        "LL3": "Xiamen Golden Dragon Bus Co. Ltd.",
        "LL6": "GAC Mitsubishi Motors Co., Ltd.",
        "LL8": "Jiangsu Linhai Yamaha Motor Co., Ltd.",
        "LLC": "Loncin Motor Co., Ltd.",
        "LLJ": "Jiangsu Xinling Motorcycle Fabricate Co., Ltd.",
        "LLN": "Qoros",
        "LLP": "Zhejiang Jiajue Motorcycle Manufacturing Co., Ltd.",
        "LLU": "Dongfeng Fengxing Jingyi",
        "LLV": "Lifan, Maple (owned by Geely), Livan Automotive",
        "LLX": "Yudo Auto",
        "LM0": "Wangye Holdings Co., Ltd.",
        "LM1": "Tai Ling Motor Co Ltd. old designation (Suzuki motorcycle",
        "LM4": "Tai Ling Motor Co Ltd. old designation (Suzuki ATV",
        "LM6": "SWM",
        "LM8": "Seres (formerly SF Motors), AITO",
        "LMC": "Suzuki Hong Kong",
        "LME": "Skyworth (formerly Skywell), Elaris Beo",
        "LMF": "Jiangmen Zhongyu Motor Co., Ltd.",
        "LMG": "GAC Motor, Trumpchi, Dodge Attitude",
        "LMH": "Jiangsu Guowei Motor Co., Ltd.",
        "LMP": "Geely Sichuan Commercial Vehicle Co., Ltd.",
        "LMV": "XPeng Motors G3",
        "LMW": "GAC Group, Dodge Journey",
        "LMX": "Forthing",
        "LN1": "Tai Ling Motor Co Ltd. old designation (Suzuki motorcycle",
        "LNA": "GAC Aion New Energy Automobile Co., Ltd., Hycan",
        "LNB": "BAIC Motor (Senova, Weiwang, Huansu) & Arcfox & Xiaomi SU7 built by BAIC",
        "LNE": "Zhejiang CRRC Electric Vehicle Co., Ltd.",
        "LNN": "Chery Automobile, Omoda, Jaecoo",
        "LNP": "NAC MG UK Limited & Nanjing Fiat Automobile",
        "LNV": "Naveco",
        "LNX": "Dongfeng Liuzhou Motor",
        "LNY": "Yuejin",
        "LP6": "Guangzhou Panyu Haojian Motorcycle Industry Co., Ltd.",
        "LPA": "Changan PSA",
        "LPE": "BYD Auto",
        "LPR": "Yamaha Motor Taiwan Co. Ltd. old designation",
        "LPS": "Polestar",
        "LR4": "Yadi Technology Group",
        "LR6": "Guangzhou Dayun Vehicle Co., Ltd.",
        "LRB": "SAIC-General Motors",
        "LRD": "Beijing Foton Daimler Automotive Co., Ltd. Auman trucks",
        "LRE": "SAIC-General Motors",
        "LRP": "Chongqing Rato Power Co. Ltd.",
        "LRR": "Ningbo Longjia Power Technology Co., Ltd.",
        "LRW": "Tesla, Inc.",
        "LS3": "Hejia New Energy Vehicle Co., Ltd",
        "LS4": "Changan Automobile",
        "LS5": "Changan Automobile (car) & Changan Suzuki",
        "LS6": "Changan Automobile & Deepal Automobile & Avatr",
        "LS7": "JMC Heavy Duty Truck Co., Ltd.",
        "LS8": "Henan Shaolin Auto Co., Ltd.",
        "LSC": "Changan Automobile",
        "LSF": "SAIC Maxus & Chevrolet S10 Max & Shanghai Sunwin Bus Corporation",
        "LSG": "SAIC-General Motors",
        "LSH": "SAIC Maxus van & Chevrolet Express Max",
        "LSJ": "SAIC MG & SAIC Roewe & IM Motors & Rising Auto",
        "LSK": "SAIC Maxus",
        "LSV": "SAIC-Volkswagen",
        "LSY": "Brilliance (Jinbei, Zhonghua) & Jinbei GM",
        "LT1": "Yangzhou Tonghua Semi-Trailer Co., Ltd.",
        "LTA": "ZX Auto",
        "LTN": "Soueast-built Chrysler & Dodge vehicles",
        "LTP": "National Electric Vehicle Sweden AB",
        "LTV": "FAW Toyota",
        "LTW": "Zhejiang Dianka Automobile Technology Co. Ltd.",
        "LUC": "Honda Automobile",
        "LUD": "Dongfeng Nissan Diesel Motor Co Ltd.",
        "LUG": "Qiantu Motor",
        "LUJ": "Zhejiang Shanqi Tianying Vehicle Industry Co., Ltd.",
        "LUR": "Chery Automobile, iCar",
        "LUX": "Dongfeng Yulon Motor Co. Ltd.",
        "LUZ": "Hozon Auto New Energy Automobile Co., Ltd.",
        "LV3": "Hengchi Automobile",
        "LV7": "Jinan Qingqi Motorcycle",
        "LVA": "Foton Motor",
        "LVB": "Foton Motor truck",
        "LVC": "Foton Motor bus",
        "LVF": "Changhe Suzuki",
        "LVG": "GAC Toyota",
        "LVH": "Dongfeng Honda",
        "LVM": "Chery Commercial Vehicle",
        "LVP": "Dongfeng Sokon Motor Company",
        "LVR": "Changan Mazda",
        "LVS": "Changan Ford(Ford, Lincoln) & Changan Ford Mazda & Volvo S40 and S80L",
        "LVT": "Chery Automobile, Exeed, Jetour, Soueast",
        "LVU": "Chery Automobile, Jetour",
        "LVV": "Chery Automobile, Omoda, Jaecoo",
        "LVX": "Aiways Automobiles Company Ltd",
        "LVY": "Volvo Cars Daqing factory",
        "LVZ": "Dongfeng Sokon Motor Company",
        "LW4": "Li Auto",
        "LWB": "Wuyang Honda Motorcycle (Guangzhou) Co., Ltd.",
        "LWE": "Yangtse Motor Group",
        "LWG": "Chongqing Huansong Industries (Group) Co., Ltd.",
        "LWL": "Qingling Isuzu",
        "LWM": "Chongqing Wonjan Motorcycle Co., Ltd.",
        "LWV": "GAC Fiat Chrysler Automobiles",
        "LWX": "Shanghai Wanxiang Automobile Manufacturing Co., Ltd.",
        "LX6": "Jiangmen City Huari Group Co. Ltd.",
        "LX8": "Chongqing Xgjao (Xinganjue) Motorcycle Co Ltd.",
        "LXA": "Jiangmen Qipai Motorcycle Co., Ltd.",
        "LXD": "Ningbo Dongfang Lingyun Vehicle Made Co., Ltd.",
        "LXG": "Xuzhou Construction Machinery Group Co., Ltd.",
        "LXK": "Shanghai Meitian Motorcycle Co., Ltd.",
        "LXM": "Xiamen Xiashing Motorcycle Co., Ltd.",
        "LXN": "Link Tour",
        "LXV": "Beijing Borgward Automotive Co., Ltd.",
        "LXW": "JMC - Ford",
        "LXY": "Chongqing Shineray Motorcycle Co., Ltd.",
        "LY4": "Chongqing Yingang Science & Technology Group Co., Ltd.",
        "LYB": "Weichai (Yangzhou) Yaxing Automobile Co., Ltd.",
        "LYD": "Taizhou City Kaitong Motorcycle Co., Ltd.",
        "LYJ": "Beijing ZhongdaYanjing Auto Co., Ltd.",
        "LYM": "Zhuzhou Jianshe Yamaha Motorcycle Co., Ltd.",
        "LYS": "Nanjing Vmoto Manufacturing Co. Ltd.",
        "LYU": "Huansu",
        "LYV": "Volvo Cars Chengdu factory & Luqiao factory",
        "LZ0": "Shandong Wuzheng Group Co., Ltd.",
        "LZ4": "Jiangsu Linzhi Shangyang Group Co Ltd.",
        "LZE": "Isuzu Guangzhou, China",
        "LZF": "SAIC Iveco Hongyan (-2021), SAIC Hongyan",
        "LZG": "Shaanxi Automobile Group",
        "LZK": "Sinotruk (CNHTC) Huanghe bus",
        "LZL": "Zengcheng Haili Motorcycle Ltd.",
        "LZM": "MAN China",
        "LZP": "Zhongshan Guochi Motorcycle",
        "LZS": "Zongshen, Electra Meccanica Vehicles Corp.",
        "LZU": "Guangzhou Isuzu Bus",
        "LZW": "SAIC-GM-Wuling",
        "LZY": "Yutong Bus Co., Ltd.",
        "LZZ": "Sinotruk (CNHTC",
        "M3G": "Isuzu Motors India",
        "M6F": "UM Lohia Two Wheelers Private Limited",
        "MA1": "Mahindra & Mahindra",
        "MA3": "Maruti Suzuki India",
        "MA6": "GM India",
        "MA7": "Hindustan Motors Ltd. & Mitsubishi Motors & Isuzu models",
        "MA8": "Daewoo Motor India",
        "MAA": "India Kawasaki Motors Pvt. Ltd.",
        "MAB": "Mahindra & Mahindra",
        "MAC": "Mahindra & Mahindra",
        "MAH": "Fiat India Automobiles Pvt. Ltd",
        "MAJ": "Ford India",
        "MAK": "Honda Cars India",
        "MAL": "Hyundai Motor India",
        "MAN": "Eicher Polaris Multix",
        "MAT": "Tata Motors, Rover CityRover",
        "MB1": "Ashok Leyland",
        "MB2": "Hyundai Motor India",
        "MB7": "Reva Electric Car Company/Mahindra Reva Electric Vehicles Pvt. Ltd.",
        "MB8": "Suzuki Motorcycle India Limited",
        "MBF": "Royal Enfield",
        "MBH": "Suzuki (for export) & Nissan Pixo",
        "MBJ": "Toyota Kirloskar Motor Pvt. Ltd.",
        "MBK": "MAN Trucks India Pvt. Ltd.",
        "MBL": "Hero MotoCorp",
        "MBR": "Mercedes-Benz India",
        "MBU": "Swaraj Vehicles Limited",
        "MBV": "Premier Automobiles Ltd.",
        "MBX": "Piaggio India",
        "MBY": "Asia Motor Works Ltd.",
        "MC1": "Force Motors Ltd.",
        "MC2": "Eicher Motors Ltd./Volvo Eicher Commercial Vehicles Ltd.",
        "MC4": "Dilip Chhabria Design Pvt Ltd.",
        "MCA": "FCA India Automobiles Pvt. Ltd.",
        "MCB": "GM India",
        "MCD": "Mahindra Two Wheelers",
        "MCG": "Atul Auto Ltd.",
        "MCL": "International Cars And Motors Ltd.",
        "MD6": "TVS Motor Company",
        "MD7": "LML Ltd including Genuine Scooter Company Stella",
        "MD9": "Shuttle Cars India",
        "MDE": "Kinetic Engineering Limited",
        "MDH": "Nissan Motor India Pvt Ltd.",
        "MDT": "Kerala Automobiles Limited",
        "ME1": "India Yamaha Motor Pvt. Ltd.",
        "ME3": "Royal Enfield",
        "ME4": "Honda Motorcycle and Scooter India",
        "MEC": "Daimler India Commercial Vehicles",
        "MEE": "Renault India Private Limited",
        "MEG": "Harley-Davidson India",
        "MER": "Benelli India",
        "MES": "Mahindra Navistar",
        "MET": "Piaggio India",
        "MEX": "Škoda Auto Volkswagen India Pvt. Ltd. 2015 on",
        "MF3": "PT Hyundai Motor Manufacturing Indonesia",
        "MH1": "PT Astra Honda Motor",
        "MH3": "PT Yamaha Indonesia Motor Mfg.",
        "MH4": "PT Kawasaki Motor Indonesia",
        "MH8": "PT Suzuki Indomobil Motor",
        "MHD": "PT Indomobil Suzuki International",
        "MHF": "PT Toyota Motor Manufacturing Indonesia",
        "MHK": "PT Astra Daihatsu Motor (includes Toyotas",
        "MHL": "PT Mercedes-Benz Indonesia",
        "MHR": "Honda Indonesia (PT Honda Prospect Motor",
        "MHY": "PT Suzuki Indomobil Motor",
        "MJB": "GM Indonesia",
        "MK2": "PT Mitsubishi Motors Krama Yudha Indonesia",
        "MK3": "PT SGMW Motor Indonesia",
        "MKF": "PT Sokonindo Automobile",
        "ML0": "Ducati Motor (Thailand) Co., Ltd.",
        "ML3": "Mitsubishi Motors, Dodge Colt 100 [Canada], Dodge Attitude [Mexico]",
        "ML5": "Kawasaki Motors Enterprise Co. Ltd.",
        "MLB": "Siam Yamaha Co Ltd.",
        "MLC": "Thai Suzuki Motor Co., Ltd.",
        "MLE": "Thai Yamaha Motor Co., Ltd.",
        "MLH": "Thai Honda Manufacturing Co., Ltd.",
        "MLW": "Sco Motor Co., Ltd.",
        "MLY": "Harley-Davidson Thailand",
        "MMA": "Mitsubishi Motors",
        "MMB": "Mitsubishi Motors",
        "MMC": "Mitsubishi Motors",
        "MMD": "Mitsubishi Motors",
        "MME": "Mitsubishi Motors",
        "MMF": "BMW Manufacturing (Thailand) Co., Ltd.",
        "MML": "MG Thailand",
        "MMM": "Chevrolet Thailand, Holden Colorado RC pickup",
        "MMR": "Subaru/Tan Chong Subaru Automotive (Thailand) Co. Ltd.",
        "MMS": "Suzuki Motor (Thailand) Co., Ltd.",
        "MMT": "Mitsubishi Motors",
        "MMU": "Holden Thailand",
        "MN3": "Eagle Vista [Canada]",
        "MNK": "Hino Motors Manufacturing Thailand Co Ltd.",
        "MNT": "Nissan Motor (Thailand) Co., Ltd.",
        "MNU": "Great Wall Motor Manufacturing (Thailand) Co., Ltd.",
        "MP1": "Isuzu Motors (Thailand) Co., Ltd.",
        "MP2": "Mazda BT-50 pickup built by Isuzu Motors (Thailand) Co., Ltd.",
        "MP3": "Plymouth Colt 100 [Canada]",
        "MP5": "Foton Motor Thailand",
        "MPA": "Isuzu Motors (Thailand) Co., Ltd. & Holden Rodeo RA pickup",
        "MPB": "Ford Thailand",
        "MR0": "Toyota Thailand",
        "MR1": "Toyota Thailand",
        "MR2": "Toyota Thailand (Gateway plant",
        "MR3": "Toyota Thailand",
        "MRH": "Honda Thailand",
        "MRT": "Neta",
        "MS0": "Super Seven Stars Motors Myanmar",
        "MS1": "Super Seven Stars Automotive Myanmar",
        "MS3": "Suzuki Myanmar Motor Co., Ltd.",
        "MX3": "Hyundai Trans Auto",
        "MXB": "Saryarka AvtoProm bus",
        "MXL": "Yutong bus",
        "MXV": "IMZ-Ural Ural Motorcycles",
        "MYH": "Ather Energy",
        "MZ7": "MG Motor India Pvt. Ltd.",
        "MZB": "Kia India Pvt. Ltd.",
        "MZD": "Classic Legends Private Limited – Jawa",
        "MZZ": "Citroen India",
        "NAA": "Iran Khodro",
        "NAC": "Mammut",
        "NAD": "Škoda",
        "NAL": "Maral Sanat Jarvid",
        "NAP": "Pars Khodro",
        "NAS": "SAIPA",
        "NC0": "Oghab Afshan",
        "NFB": "Honda Atlas Cars Pakistan Ltd.",
        "NG3": "Lucky Motor Corporation",
        "NL1": "TOGG",
        "NL2": "HABAS/HBS",
        "NLA": "Honda Turkiye A.S. cars",
        "NLC": "Askam Kamyon Imalat Ve Ticaret A.S.",
        "NLE": "Mercedes-Benz Türk A.S. Truck",
        "NLF": "Koluman Otomotiv Endustri A.S.",
        "NLH": "Hyundai Assan Otomotiv car/SUV",
        "NLJ": "Hyundai Assan Otomotiv van",
        "NLN": "Karsan",
        "NLR": "Otokar",
        "NLT": "Temsa",
        "NLZ": "Tezeller",
        "NM0": "Ford Otosan",
        "NM1": "Oyak Renault Otomobil Fabrikaları A.Ş.",
        "NM4": "Tofaş",
        "NMA": "MAN Türkiye A.Ş.",
        "NMB": "Mercedes-Benz Türk A.S. Buses",
        "NMC": "BMC Otomotiv Sanayi ve Ticaret A.Ş.",
        "NMH": "Honda Anadolu motorcycle",
        "NMS": "Otoyol San. A.Ş.",
        "NMT": "Toyota Motor Manufacturing Turkey",
        "NNA": "Anadolu Isuzu",
        "NNN": "Gépébus Oréos 4X",
        "NNY": "Yeksan",
        "NP8": "ÖZGÜL TREYLER",
        "NPM": "Seyit Usta Treyler",
        "NPR": "Oztreyler",
        "NPS": "Nursan",
        "NRE": "Bozankaya",
        "NRX": "Musoshi",
        "NRY": "Pilotcar Otomotiv",
        "NS2": "JV MAN Auto - Uzbekistan",
        "NSA": "SamAvto / SAZ",
        "NVA": "Khazar",
        "PAB": "Isuzu Philippines Corporation",
        "PAD": "Honda Cars Philippines",
        "PE1": "Ford Motor Company Philippines",
        "PE3": "Mazda Philippines",
        "PFD": "Hyundai Motor Group Innovation Center in Singapore",
        "PL1": "Proton, Malaysia",
        "PL8": "Inokom-Hyundai",
        "PLP": "Subaru/Tan Chong Motor Assemblies, Malaysia",
        "PLZ": "Isuzu Malaysia",
        "PM1": "BMW & Mini/Inokom",
        "PM2": "Perodua",
        "PMA": "MAN Truck & Bus Malaysia",
        "PMH": "Honda Malaysia",
        "PMK": "Honda Boon Siew",
        "PML": "Hicom",
        "PMN": "Modenas",
        "PMS": "Suzuki Assemblers Malaysia",
        "PMV": "Hong Leong Yamaha Motor Sdn. Bhd.",
        "PMY": "Hong Leong Yamaha Motor Sdn. Bhd.",
        "PN1": "UMW Toyota Motor",
        "PN2": "UMW Toyota Motor",
        "PN8": "Nissan/Tan Chong Motor Assemblies, Malaysia",
        "PNA": "Stellantis Gurun (Malaysia) Sdn. Bhd.",
        "PNS": "TMSBUS Malaysia",
        "PNV": "Volvo Car Manufacturing Malaysia",
        "PP1": "Mazda/Inokom",
        "PP3": "Hyundai/Inokom",
        "PPP": "Suzuki",
        "PPV": "Volkswagen/HICOM Automotive Manufacturers",
        "PR8": "Ford",
        "PRA": "Sinotruk",
        "PRH": "Chery",
        "PRN": "GAC Trumpchi",
        "PRX": "Kia/Inokom",
        "PV3": "Ford",
        "R10": "ZAP (HK) Co. Ltd.",
        "R1J": "Jiayuan Power (Hong Kong) Ltd. (Electric Low-Speed Vehicles",
        "R1N": "Niu Technologies Group Ltd.",
        "R2P": "Evoke Electric Motorcycles",
        "R36": "HK Shansu Technology Co., Ltd.",
        "R3M": "Mangosteen Technology Co., Ltd.",
        "R4N": "Elyx Smart Technology Holdings (Hong Kong) Ltd.",
        "R82": "Hangzhou Lantu Technology Co., Ltd.",
        "RA1": "Steyr Trucks International FZE, UAE",
        "RF3": "Aeon Motor Co., Ltd., Taiwan",
        "RF5": "Yulon Motor Co. Ltd., Taiwan",
        "RF8": "EVT Technology Co., Ltd",
        "RFB": "Kwang Yang Motor Co., Ltd. (Kymco), Taiwan",
        "RFC": "Taiwan Golden Bee",
        "RFD": "Tai Ling Motor Co Ltd. new designation",
        "RFG": "Sanyang Motor Co., Ltd. (SYM) Taiwan",
        "RFL": "Her Chee Industrial Co., Ltd. (Adly), Taiwan",
        "RFT": "CPI Motor Company, Taiwan",
        "RGS": "Kawasaki",
        "RHA": "Ford Lio Ho Motor Co Ltd. new designation",
        "RK3": "Honda Taiwan",
        "RK7": "Kawasaki ATV",
        "RKJ": "Prince Motors Taiwan",
        "RKL": "Kuozui Motors (Toyota",
        "RKM": "China Motor Corporation",
        "RKR": "Yamaha Motor Taiwan Co. Ltd. new designation",
        "RKT": "Access Motor Co., Ltd.",
        "RL0": "Ford Vietnam",
        "RL4": "Toyota Motor Vietnam",
        "RLA": "Vina Star Motors Corp. – Mitsubishi",
        "RLC": "Yamaha Motor Vietnam Co. Ltd.",
        "RLE": "Isuzu Vietnam Co.",
        "RLH": "Honda Vietnam Co. Ltd.",
        "RLL": "VinFast SUV",
        "RLM": "Mercedes-Benz Vietnam",
        "RLN": "VinFast",
        "RLV": "Vietnam Precision Industrial CO., Ltd.",
        "RP8": "Piaggio Vietnam Co. Ltd.",
        "RUN": "Sollets-Auto ST6",
        "SA3": "Ginetta Cars",
        "SAA": "Austin",
        "SAB": "Optare (1985-2020), Switch Mobility",
        "SAD": "Jaguar SUV",
        "SAF": "ERF trucks",
        "SAH": "Honda",
        "SAJ": "Jaguar passenger car & Daimler passenger car",
        "SAL": "Land Rover",
        "SAM": "Morris",
        "SAR": "Rover & MG Rover Group",
        "SAT": "Triumph car",
        "SAX": "Austin-Rover Group including Sterling Cars",
        "SAY": "Norton Motorcycles",
        "SAZ": "Freight Rover",
        "SB1": "Toyota Motor Manufacturing UK",
        "SBB": "Leyland Vehicles",
        "SBC": "Iveco Ford Truck",
        "SBF": "Nugent",
        "SBJ": "Leyland Bus",
        "SBL": "Leyland Motors & Leyland DAF",
        "SBM": "McLaren",
        "SBS": "Scammell",
        "SBU": "United Trailers",
        "SBV": "Kenworth & Peterbilt trucks",
        "SBW": "Weightlifter Bodies",
        "SC5": "Wrightbus",
        "SC6": "INEOS Automotive SUV",
        "SCA": "Rolls Royce passenger car",
        "SCB": "Bentley passenger car",
        "SCC": "Lotus Cars & Opel Lotus Omega/Vauxhall Lotus Carlton",
        "SCD": "Reliant Motors",
        "SCE": "DeLorean Motor Cars N. Ireland",
        "SCF": "Aston Martin Lagonda Ltd. passenger car & '21 DBX SUV",
        "SCG": "Triumph Engineering Co. Ltd.",
        "SCK": "Ifor Williams Trailers",
        "SCM": "Manitowoc Cranes - Grove",
        "SCV": "Volvo Truck & Bus Scotland",
        "SD7": "Aston Martin SUV",
        "SD8": "Moke International Ltd.",
        "SDB": "Talbot",
        "SDC": "SDC Trailers Ltd.",
        "SDF": "Dodge Trucks – UK 1981–1984",
        "SDG": "Renault Trucks Industries 1985–1992",
        "SDK": "Caterham Cars",
        "SDL": "TVR",
        "SDP": "NAC MG UK & MG Motor UK Ltd.",
        "SDU": "Utility",
        "SED": "IBC Vehicles (General Motors Luton Plant",
        "SEG": "Dennis Eagle Ltd., including Renault Trucks Access and D Access",
        "SEP": "Don-Bur",
        "SEY": "LDV Group Ltd.",
        "SFA": "Ford UK",
        "SFD": "Dennis UK / Alexander Dennis",
        "SFE": "Alexander Dennis UK",
        "SFN": "Foden Trucks",
        "SFR": "Fruehauf",
        "SFZ": "Tesla Roadster",
        "SG4": "Coachman",
        "SGA": "Avondale",
        "SGB": "Bailey",
        "SGD": "Swift Group Ltd.",
        "SGE": "Elddis",
        "SGL": "Lunar Caravans Ltd.",
        "SH7": "INEOS Automotive truck",
        "SHH": "Honda UK passenger car",
        "SHS": "Honda UK SUV",
        "SJ1": "Ree Automotive",
        "SJA": "Bentley SUV",
        "SJB": "Brian James Trailers Ltd",
        "SJK": "Nissan Motor Manufacturing UK - Infiniti",
        "SJN": "Nissan Motor Manufacturing UK - Nissan",
        "SKA": "Vauxhall",
        "SKB": "Kel-Berg Trailers & Trucks",
        "SKF": "Bedford Vehicles",
        "SKL": "Anaig (UK) Technology Ltd",
        "SLA": "Rolls Royce SUV",
        "SLC": "Thwaites Dumpers",
        "SLG": "McMurtry Automotive",
        "SLN": "Niftylift",
        "SLP": "JC Bamford Excavators Ltd.",
        "SLV": "Volvo bus",
        "SMR": "Montracon",
        "SMT": "Triumph Motorcycles Ltd.",
        "SMW": "Cartwright",
        "SMX": "Gray & Adams",
        "SNE": "Wartburg",
        "SNT": "Trabant",
        "SNZ": "MZ (motorcycle",
        "SPE": "B-ON GmbH",
        "ST3": "Calabrese",
        "SUA": "Autosan",
        "SUB": "Tramp Trail",
        "SUC": "Wiola",
        "SUD": "Wielton",
        "SUF": "FSM/Fiat Auto Poland",
        "SUG": "Mega Trailers (truck trailer",
        "SUJ": "Jelcz",
        "SUL": "FSC",
        "SUM": "Novatrail",
        "SUP": "FSO/Daewoo-FSO",
        "SUU": "Solaris Bus & Coach",
        "SVH": "ZASŁAW",
        "SVM": "Inter Cars",
        "SVS": "BODEX",
        "SWH": "Temared",
        "SWR": "Weekend Trailers",
        "SWV": "TA-NO",
        "SWZ": "Zremb",
        "SX7": "Arthur Bus",
        "SXE": "Neptun Trailers",
        "SXK": "Konar",
        "SXM": "MELEX Sp. z o.o.",
        "SXX": "Martz",
        "SXY": "Wecon",
        "SY1": "Neso Bus",
        "SYB": "Rydwan",
        "SYG": "Gniotpol, GT Trailers Sp. z o. o.",
        "SZA": "Scania Poland",
        "SZC": "Vectrix",
        "SZL": "Boro Trailers",
        "SZN": "Przyczepy Głowacz",
        "SZR": "Niewiadów",
        "T3C": "Lohr Backa Topola (truck trailer",
        "T7A": "Ebusco",
        "TAW": "NAW Nutzfahrzeuggesellschaft Arbon & Wetzikon AG",
        "TBS": "Boschung AG",
        "TCC": "Micro Compact Car AG (smart 1998-1999",
        "TDM": "QUANTYA Swiss Electric Movement",
        "TEB": "Bucher Municipal AG",
        "TEM": "Twike (SwissLEM AG",
        "TFH": "FHS Frech-Hoch AG (truck trailer",
        "TJ5": "Vezeko (trailer",
        "TKP": "Panav a.s. (truck trailer",
        "TKX": "Agados s.r.o. (trailer",
        "TKY": "Metaco (truck trailer",
        "TLJ": "Jawa Moto",
        "TMA": "Hyundai Motor Manufacturing Czech",
        "TMB": "Škoda",
        "TMC": "Hyundai Motor Manufacturing Czech",
        "TMK": "Karosa",
        "TMP": "Škoda trolleybuses",
        "TMT": "Tatra passenger car",
        "TNA": "Avia/Daewoo Avia",
        "TNE": "TAZ",
        "TNG": "LIAZ",
        "TNT": "Tatra trucks",
        "TNU": "Tatra trucks",
        "TRA": "Ikarus Bus",
        "TRC": "Csepel bus",
        "TRE": "Rákos bus",
        "TRK": "Credo bus/Kravtex",
        "TRR": "Rába Bus",
        "TRU": "Audi Hungary",
        "TSB": "Ikarus Bus",
        "TSC": "VIN assigned by the National Transport Authority of Hungary",
        "TSE": "Ikarus Egyedi Autobuszgyar (EAG",
        "TSF": "Alfabusz",
        "TSM": "Suzuki Hungary (Magyar Suzuki), Fiat Sedici",
        "TSY": "Keeway Motorcycles",
        "TW0": "CaetanoBus",
        "TW1": "Toyota Caetano Portugal, S.A.",
        "TW2": "Ford Lusitana",
        "TW4": "UMM",
        "TW6": "Citroën",
        "TW7": "Mini Moke",
        "TWG": "CaetanoBus",
        "TX5": "Mini Moke",
        "TYA": "Mitsubishi Fuso Truck and Bus Corp. Portugal",
        "TYB": "Mitsubishi Fuso Truck and Bus Corp. Portugal",
        "U1A": "Sanos",
        "U1V": "VDL Van Hool Macedonia",
        "U5Y": "Kia Motors Slovakia",
        "U6A": "Granus (bus",
        "U6Y": "Kia Motors Slovakia",
        "UA1": "AUSA Center",
        "UA2": "Iveco Massif & Campagnola",
        "UA4": "Irizar e-mobility",
        "UCY": "Silence Urban Ecomobility",
        "UD3": "Granalu truck trailers",
        "UH2": "De Forenede Trailerfabrikke (trailer",
        "UHE": "Scanvogn (trailer",
        "UHL": "Camp-let (recreational vehicle",
        "UJG": "Garia ApS - Club Car",
        "UKR": "Hero Camper",
        "UMT": "MTDK a/s (truck trailer",
        "UN1": "Ford Ireland",
        "UU1": "Dacia",
        "UU2": "Oltcit",
        "UU3": "ARO",
        "UU4": "Roman/Grivbuz",
        "UU5": "Rocar",
        "UU6": "Daewoo Romania",
        "UU7": "Euro Bus Diamond",
        "UU9": "Astra Bus",
        "UVW": "UMM",
        "UWR": "Robus Reșița",
        "UZT": "UTB",
        "V1Y": "FAS Sanos bus",
        "V2X": "Ikarbus a.d.",
        "V31": "Tvornica Autobusa Zagreb (TAZ",
        "V34": "Crobus bus",
        "V61": "Respo Trailers",
        "V6A": "Bestnet AS; Tiki trailers",
        "V6B": "Brentex-Trailer",
        "V6T": "Verge Motorcycles",
        "VA0": "ÖAF, Gräf & Stift",
        "VA4": "KSR Group",
        "VAG": "Steyr-Daimler-Puch Puch G & Steyr-Puch Pinzgauer",
        "VAH": "Hangler",
        "VAK": "Kässbohrer Transport Technik",
        "VAN": "MAN Austria/Steyr-Daimler-Puch Steyr Trucks",
        "VAV": "Schwarzmüller",
        "VAX": "Schwingenschlogel",
        "VBF": "Fit-Zel",
        "VBK": "Husqvarna Motorcycles & Gas Gas under KTM ownership",
        "VCF": "Fisker Inc.",
        "VF1": "Renault, Mobilize Duo, Eagle Medallion",
        "VF2": "Renault Trucks",
        "VF3": "Peugeot",
        "VF4": "Talbot",
        "VF5": "Iveco Unic",
        "VF6": "Renault Trucks including vans",
        "VF7": "Citroën",
        "VF8": "Matra Automobiles (Talbot-Matra Murena, Rancho",
        "VFA": "Alpine, Renault Alpine GTA",
        "VFG": "Caravelair",
        "VFK": "Fruehauf",
        "VFN": "Trailor, General Trailers",
        "VG5": "MBK (motorcycles) & Yamaha Motor",
        "VG6": "Renault Trucks & Mack Trucks medium duty trucks",
        "VG7": "Renault Trucks",
        "VG8": "Renault Trucks",
        "VGA": "Peugeot Motocycles",
        "VGT": "ASCA",
        "VGU": "Trouillet",
        "VGW": "BSLT",
        "VGX": "Coder",
        "VGY": "Lohr",
        "VH1": "Benalu SAS",
        "VH8": "Microcar",
        "VHR": "Robuste",
        "VHX": "Manitowoc Cranes - Potain",
        "VJ1": "Heuliez Bus",
        "VJ2": "Mia Electric",
        "VJ4": "Gruau",
        "VJR": "Ligier",
        "VJY": "Gruau",
        "VK1": "SEG",
        "VK2": "Grandin Automobiles",
        "VK8": "Venturi Automobiles",
        "VKD": "Cheval Liberté",
        "VL4": "Bluecar, Citroen E-Mehari",
        "VLG": "Aixam-Mega",
        "VLU": "Scania France",
        "VM3": "Chereau",
        "VMK": "Renault Sport Spider",
        "VMS": "Automobiles Chatenet",
        "VMT": "SECMA",
        "VMW": "Gépébus Oréos 55",
        "VN1": "Renault SOVAB (France), Opel/Vauxhall Movano A made at SOVAB",
        "VN4": "Voxan",
        "VNE": "Iveco Bus/Irisbus",
        "VNK": "Toyota Motor Manufacturing France & '11-'13 Daihatsu Charade",
        "VNV": "Nissan made in France by Renault",
        "VP3": "G. Magyar",
        "VPL": "Nosmoke S.A.S",
        "VR1": "DS Automobiles",
        "VR3": "Peugeot",
        "VR7": "Citroën",
        "VRW": "Goupil",
        "VS1": "Pegaso",
        "VS5": "Renault Spain",
        "VS6": "Ford Spain",
        "VS7": "Citroën Spain",
        "VS8": "Peugeot Spain",
        "VSA": "Mercedes-Benz Spain",
        "VSC": "Talbot",
        "VSF": "Santana Motors",
        "VSR": "Leciñena",
        "VSS": "SEAT/Cupra",
        "VSX": "Opel Spain",
        "VSY": "Renault V.I. Spain",
        "VTD": "Montesa Honda",
        "VTH": "Derbi",
        "VTL": "Yamaha Spain",
        "VTM": "Montesa Honda",
        "VTP": "Rieju S.A.",
        "VTR": "Gas Gas",
        "VTT": "Suzuki Spain",
        "VV1": "Lecitrailer Group",
        "VV5": "Prim-Ball",
        "VVC": "SOR Ibérica",
        "VVG": "Tisvol",
        "VWA": "Nissan Vehiculos Industriales SA, Nissan Commercial Vehicles",
        "VWF": "Guillén Group",
        "VWL": "Indox",
        "VWV": "Volkswagen Spain",
        "VX1": "Zastava Automobiles/ Yugo",
        "VXE": "Opel Automobile Gmbh/Vauxhall van",
        "VXF": "Fiat van",
        "VXK": "Opel Automobile Gmbh/Vauxhall car/SUV",
        "VXY": "Neobus a.d.",
        "VYC": "Lancia Ypsilon",
        "VYE": "Jeep Compass",
        "VYF": "Fiat Doblo '23- & Fiat Topolino '23- & Fiat Grande Panda '25-",
        "VYJ": "Ram 1200 '25-",
        "VYS": "Renault & Alpine",
        "VZ2": "Avtomontaža (bus",
        "W04": "Buick Regal & Buick Cascada",
        "W06": "Cadillac Catera",
        "W08": "Saturn Astra",
        "W0D": "Obermaier",
        "W0L": "Holden Zafira & Subaru Traviq",
        "W0V": "Opel Automobile Gmbh/Vauxhall & Holden",
        "W1A": "smart",
        "W1H": "Freightliner Econic",
        "W1K": "Mercedes-Benz car",
        "W1N": "Mercedes-Benz SUV",
        "W1T": "Mercedes-Benz truck",
        "W1V": "Mercedes-Benz van",
        "W1W": "Mercedes-Benz MPV (van with 2 or 3 rows of seats",
        "W1X": "Mercedes-Benz incomplete vehicle",
        "W1Y": "Mercedes-Benz truck (cargo van with 1 row of seats",
        "W1Z": "Mercedes-Benz \"bus\" (van with more than 3 rows of seats",
        "W2W": "Freightliner Sprinter MPV",
        "W2X": "Freightliner Sprinter incomplete vehicle",
        "W2Y": "Freightliner Sprinter truck",
        "W2Z": "Freightliner Sprinter \"bus\"",
        "WA1": "Audi SUV",
        "WAC": "Audi/Porsche RS2 Avant",
        "WAF": "Ackermann",
        "WAG": "Neoplan",
        "WAP": "Alpina",
        "WAU": "Audi car",
        "WB0": "Böckmann Fahrzeugwerke GmbH",
        "WB1": "BMW Motorrad",
        "WB2": "Blyss",
        "WB3": "BMW Motorrad Motorcycles made in India by TVS",
        "WB4": "BMW Motorrad Motorscooters made in China by Loncin",
        "WB5": "BMW i SUV",
        "WBA": "BMW car",
        "WBC": "Boom Trikes",
        "WBJ": "Bitter Cars",
        "WBK": "Böcker Maschinenwerke GmbH",
        "WBL": "Blumhardt",
        "WBS": "BMW M car",
        "WBU": "Bürstner",
        "WBX": "BMW SUV",
        "WBY": "BMW i car",
        "WCD": "Freightliner Sprinter \"bus\" (van with more than 3 rows of seats) 2008–2019",
        "WCM": "Wilcox",
        "WD0": "Dodge Sprinter truck (cargo van with 1 row of seats) 2005–2009",
        "WD2": "Freightliner Sprinter 2002 & Sprinter (Dodge or Freightliner) 2003–2005 truck",
        "WD3": "Mercedes-Benz truck (cargo van with 1 row of seats",
        "WD4": "Mercedes-Benz MPV (van with 2 or 3 rows of seats",
        "WD5": "Freightliner Sprinter 2002 & Sprinter (Dodge or Freightliner) 2003–2005 MPV",
        "WD6": "Freightliner Unimog truck",
        "WD7": "Freightliner Unimog incomplete vehicle",
        "WD8": "Dodge Sprinter MPV (van with 2 or 3 rows of seats) 2005–2009",
        "WDA": "Mercedes-Benz incomplete vehicle",
        "WDB": "Mercedes-Benz & Maybach",
        "WDC": "Mercedes-Benz SUV",
        "WDD": "Mercedes-Benz car",
        "WDF": "Mercedes-Benz van/pickup",
        "WDP": "Freightliner Sprinter incomplete vehicle 2005–2019",
        "WDR": "Freightliner Sprinter MPV (van with 2 or 3 rows of seats) 2005–2019",
        "WDT": "Dethleffs",
        "WDW": "Dodge Sprinter \"bus\" (van with more than 3 rows of seats) 2008–2009",
        "WDX": "Dodge Sprinter incomplete vehicle 2005–2009",
        "WDY": "Freightliner Sprinter truck (cargo van with 1 row of seats) 2005–2019",
        "WDZ": "Mercedes-Benz \"bus\" (van with more than 3 rows of seats",
        "WEB": "Evobus GmbH",
        "WEG": "Ablinger",
        "WEL": "e.GO Mobile AG",
        "WF0": "Ford Germany",
        "WF1": "Merkur",
        "WFB": "Feldbinder Spezialfahrzeugwerke GmbH",
        "WFC": "Fendt",
        "WFD": "Fliegl Trailer",
        "WFN": "Tadano Faun GmbH",
        "WG0": "Goldhofer AG",
        "WGB": "Göppel Bus GmbH",
        "WH7": "Hüfferman",
        "WHB": "Hobby",
        "WHD": "Humbaur GmbH",
        "WHL": "Hulco",
        "WHW": "Hako GmbH",
        "WHY": "Hymer",
        "WJM": "Iveco/Iveco Magirus",
        "WJR": "Irmscher",
        "WK0": "Kögel",
        "WKE": "Krone",
        "WKK": "Setra",
        "WKN": "Knaus, Weinsberg",
        "WKV": "Kässbohrer Fahrzeugwerke Gmbh",
        "WLA": "Langendorf semi-trailers",
        "WLF": "Liebherr",
        "WMA": "MAN Truck & Bus",
        "WME": "smart",
        "WMG": "Demag Cranes",
        "WMM": "Karl Müller GmbH & Co. KG",
        "WMP": "M & V GmbH",
        "WMU": "Hako GmbH",
        "WMW": "MINI car",
        "WMX": "Mercedes-AMG used for Mercedes-Benz SLS AMG & Mercedes-AMG GT",
        "WMZ": "MINI SUV",
        "WNA": "Next.e.GO Mobile SE",
        "WP0": "Porsche car",
        "WP1": "Porsche SUV",
        "WRA": "Renders",
        "WRJ": "Riese & Müller",
        "WS5": "StreetScooter",
        "WS7": "Sono Motors",
        "WSE": "STEMA Metalleichtbau GmbH",
        "WSJ": "STERK Trailers",
        "WSK": "Schmitz-Cargobull Gotha",
        "WSM": "Schmitz-Cargobull",
        "WSP": "Spitzer",
        "WSV": "Aebi Schmidt Group",
        "WTA": "Tabbert",
        "WU1": "Audi Sport GmbH (formerly quattro GmbH) SUV",
        "WUA": "Audi Sport GmbH (formerly quattro GmbH) car",
        "WV1": "Volkswagen Commercial Vehicles",
        "WV2": "Volkswagen Commercial Vehicles",
        "WV3": "Volkswagen Commercial Vehicles",
        "WV4": "Volkswagen Commercial Vehicles (2nd gen. Amarok & T7 Transporter",
        "WV5": "Volkswagen Commercial Vehicles (T7 Caravelle",
        "WVG": "Volkswagen SUV & Touran",
        "WVM": "Arbeitsgemeinschaft VW-MAN",
        "WVP": "Viseon Bus",
        "WVW": "Volkswagen passenger car, Sharan, Golf Plus, Golf Sportsvan",
        "WWA": "Wachenhut",
        "WWC": "WM Meyer",
        "WZ1": "Toyota Supra",
        "X0T": "Tonar",
        "X1D": "RAF",
        "X1E": "KAvZ",
        "X1F": "NefAZ",
        "X1M": "PAZ",
        "X1P": "Ural",
        "X21": "Diesel-S (truck trailer",
        "X2L": "Fox Trailer (truck trailer",
        "X4K": "Volgabus (Volzhanin",
        "X4T": "Sommer (truck trailer",
        "X4X": "Avtotor",
        "X5A": "UralSpetzTrans (trailer",
        "X6D": "VIS-AVTO",
        "X6S": "TZA (truck trailer",
        "X7L": "Renault AvtoFramos (1998-2014), Renault Russia (2014-2022), Moskvitch (2022-",
        "X7M": "Hyundai & Vortex",
        "X8J": "IMZ-Ural Ural Motorcycles",
        "X8U": "Scania Russia",
        "X90": "GRAZ",
        "X96": "GAZ",
        "X9F": "Ford Motor Company ZAO",
        "X9L": "GM-AvtoVAZ",
        "X9N": "Samoltor",
        "X9P": "Volvo Vostok ZAO Volvo Trucks",
        "X9W": "Brilliance, Lifan",
        "X9X": "Great Wall Motors",
        "XD2": "CTTM Cargoline (truck trailer",
        "XDN": "Mercedes Sprinter Classic",
        "XE2": "AMKAR Automaster (truck trailer",
        "XEA": "AmberAvto (Avtotor",
        "XG3": "Petros Petropoulos Group - Ecoshift NOOS electric motorscooters",
        "XG4": "Mpitis (trailer",
        "XG5": "Stavropoulos trailers",
        "XG6": "MGK Hellenic Motor motorcycles",
        "XG8": "Gorgolis SA motorcycles",
        "XJ4": "PKTS (PK Transportnye Sistemy) bus",
        "XJY": "Bonum (truck trailer",
        "XKM": "Volgabus",
        "XL3": "Ebusco",
        "XL4": "Lightyear",
        "XLA": "DAF Bus International",
        "XLB": "Volvo Car B.V./NedCar B.V.",
        "XLC": "Ford Netherlands",
        "XLD": "Pacton Trailers B.V.",
        "XLE": "Scania Netherlands",
        "XLH": "Hapert",
        "XLJ": "Anssems",
        "XLK": "Burg Trailer Service BV",
        "XLR": "DAF Trucks & Leyland DAF",
        "XLU": "Henra",
        "XLV": "DAF Bus",
        "XLW": "Terberg Benschop BV",
        "XM4": "RAVO Holding B.V.",
        "XMC": "NedCar B.V. Mitsubishi Motors",
        "XMD": "NedCar B.V. Mitsubishi Motors",
        "XMG": "VDL Bus International",
        "XMR": "Nooteboom Trailers",
        "XN1": "Kraker Trailers Axel B.V.",
        "XNB": "NedCar B.V. Mitsubishi Motors",
        "XNC": "NedCar B.V. Mitsubishi Motors",
        "XNJ": "Broshuis",
        "XNL": "VDL Bus & Coach",
        "XNT": "Pacton Trailers B.V.",
        "XP7": "Tesla Europe (based in the Netherlands",
        "XPN": "Knapen Trailers",
        "XPP": "Atec Trailers",
        "XR7": "Qarry",
        "XRP": "Proline",
        "XRY": "D-TEC",
        "XTA": "Lada / AvtoVAZ",
        "XTB": "Moskvitch / AZLK",
        "XTC": "KAMAZ",
        "XTD": "LuAZ",
        "XTE": "ZAZ",
        "XTF": "GolAZ",
        "XTH": "GAZ",
        "XTJ": "Lada Oka",
        "XTK": "IzhAvto",
        "XTM": "MAZ (Belarus); used until 1997",
        "XTP": "Ural",
        "XTS": "ChMZAP",
        "XTT": "UAZ / Sollers",
        "XTU": "Trolza, previously ZiU",
        "XTW": "LAZ",
        "XTY": "LiAZ",
        "XTZ": "ZiL",
        "XU6": "Avtodom (minibus",
        "XUF": "General Motors Russia",
        "XUS": "Nizhegorodets (minibus",
        "XUU": "Avtotor",
        "XUV": "Avtotor",
        "XUZ": "InterPipeVAN",
        "XVG": "MARZ (bus",
        "XVU": "Start",
        "XW7": "Toyota Motor Manufacturing Russia",
        "XW8": "Volkswagen Group Russia",
        "XWB": "Avtotor",
        "XWE": "Avtotor",
        "XWF": "Avtotor",
        "XX3": "Ujet Manufacturing",
        "XZB": "SIMAZ (bus",
        "XZE": "Specpricep",
        "XZG": "Great Wall Motor",
        "XZP": "Gut Trailer",
        "XZT": "FoxBus (minibus",
        "Y3D": "MTM (truck trailer",
        "Y3F": "Lida Buses Neman",
        "Y3J": "Belkommunmash",
        "Y3K": "Neman Bus",
        "Y3M": "MAZ",
        "Y3W": "VFV built by Unison",
        "Y4F": "Ford Belarus",
        "Y4K": "Geely / BelGee",
        "Y6B": "Iveco",
        "Y6D": "ZAZ / AvtoZAZ",
        "Y6E": "LAZ",
        "Y6J": "Bogdan group",
        "Y6L": "Bogdan group including buses, Hyundai",
        "Y6U": "Škoda Auto",
        "Y6W": "PGFM (trailer",
        "Y6Y": "LEV (trailer",
        "Y7A": "KrAZ trucks",
        "Y7B": "Bogdan group",
        "Y7C": "Great Wall Motors, Geely",
        "Y7D": "GAZ",
        "Y7F": "Boryspil Bus Factory (BAZ",
        "Y7S": "Korida-Tech (trailer",
        "Y7W": "Geely",
        "Y7X": "ChRZ - Ruta (minibus",
        "Y8A": "LAZ",
        "Y8H": "UNV Leader (trailer",
        "Y8S": "Alekseevka Ximmash",
        "Y8X": "GAZ Gazelle",
        "Y9A": "PAVAM (trailer",
        "Y9H": "LAZ",
        "Y9M": "AMS (trailer",
        "Y9T": "Dnipro (trailer",
        "Y9W": "Pragmatec (trailer",
        "Y9Z": "Lada, Renault made in Ukraine",
        "YA2": "Atlas Copco Group",
        "YA5": "Renders",
        "YAF": "Faymonville",
        "YAG": "Syma aanhangwagenbouw BV",
        "YAM": "MAX Trailer",
        "YB1": "Volvo Trucks Belgium",
        "YB2": "Volvo Trucks Belgium",
        "YB3": "Volvo Trucks Belgium",
        "YB4": "LAG Trailers N.V.",
        "YB6": "Jonckheere",
        "YBC": "Toyota Supra",
        "YBD": "Addax Motors",
        "YBW": "Volkswagen Belgium",
        "YC1": "Honda Belgium NV",
        "YC3": "Eduard Trailers",
        "YD3": "Chateau Caravans",
        "YE1": "Van Hool (trailers",
        "YE2": "Van Hool (buses",
        "YE6": "STAS",
        "YE7": "Turbo's Hoet",
        "YF1": "Närko (truck trailer",
        "YF3": "NTM (truck trailer",
        "YGU": "JJ-Trailer (trailer",
        "YH1": "Solifer",
        "YH2": "BRP Finland",
        "YH4": "Fisker Automotive (Fisker Karma) built by Valmet Automotive",
        "YK1": "Saab-Valmet Finland",
        "YS2": "Scania commercial vehicles",
        "YS3": "Saab cars",
        "YS4": "Scania buses and bus chassis until 2002",
        "YS5": "OmniNova",
        "YS7": "Solifer",
        "YSC": "Cadillac BLS",
        "YSM": "Polestar cars",
        "YSP": "Volta Trucks AB",
        "YSR": "Polestar SUV",
        "YT7": "Kabe",
        "YTN": "Saab",
        "YU1": "Fogelsta, Brenderup Group",
        "YU7": "Husaberg",
        "YV1": "Volvo cars",
        "YV2": "Volvo trucks",
        "YV3": "Volvo buses and bus chassis",
        "YV4": "Volvo SUV",
        "YV5": "Volvo Trucks incomplete vehicle",
        "YVV": "WiMa 442 EV",
        "YYB": "Tysse (trailer",
        "YYC": "Think Nordic",
        "Z07": "Volgabus",
        "Z6F": "Ford Sollers",
        "Z76": "SEMAZ",
        "Z7C": "Luidor (bus",
        "Z7N": "KAvZ (bus",
        "Z7T": "RoAZ (bus",
        "Z7X": "Isuzu Rus",
        "Z8M": "Marussia",
        "Z8N": "Nissan Manufacturing Rus",
        "Z8T": "PCMA Rus (Peugeot, Citroen, Mitsubishi",
        "Z8Y": "Nasteviya (bus",
        "Z9B": "KuzbassAvto (Hyundai bus",
        "Z9M": "Mercedes-Benz Trucks Vostok",
        "Z9N": "Samotlor-NN (Iveco",
        "ZA0": "Acerbi",
        "ZA4": "Omar",
        "ZAA": "Alfa Romeo Junior 2024-",
        "ZAC": "Jeep, Dodge Hornet",
        "ZAH": "Rolfo SpA",
        "ZAJ": "Trigano SpA; Roller Team recreational vehicles",
        "ZAM": "Maserati",
        "ZAP": "Piaggio/Vespa/Gilera",
        "ZAR": "Alfa Romeo car",
        "ZAS": "Alfa Romeo SUV 2018-",
        "ZAX": "Zorzi",
        "ZB3": "Cardi",
        "ZBA": "Piacenza",
        "ZBB": "Bertone",
        "ZBD": "InBus",
        "ZBN": "Benelli",
        "ZBW": "Rayton-Fissore Magnum",
        "ZC1": "AnsaldoBreda S.p.A.",
        "ZC2": "Chrysler TC by Maserati",
        "ZCB": "E. Bartoletti SpA",
        "ZCF": "Iveco / Irisbus",
        "ZCG": "Husqvarna Motorcycles Under MV Agusta ownership",
        "ZCM": "BredaMenarinibus / Menarinibus / IIA",
        "ZCN": "Astra Veicoli Industriali S.p.A.",
        "ZCV": "Vibreti",
        "ZCZ": "BredaBus",
        "ZD0": "Yamaha Motor Italia SpA & Belgarda SpA",
        "ZD3": "Beta Motor",
        "ZD4": "Aprilia",
        "ZD5": "Casalini",
        "ZDC": "Honda Italia Industriale SpA",
        "ZDF": "Ferrari Dino",
        "ZDJ": "ACM Biagini",
        "ZDM": "Ducati Motor Holdings SpA",
        "ZDT": "De Tomaso Modena SpA",
        "ZDY": "Cacciamali",
        "ZE5": "Carmosino",
        "ZEB": "Ellebi",
        "ZEH": "Trigano SpA (former SEA Group); McLouis & Mobilvetta recreational vehicles",
        "ZES": "Bimota",
        "ZEX": "TM Racing",
        "ZF4": "Qvale",
        "ZFA": "Fiat",
        "ZFB": "Fiat MPV/SUV & Ram Promaster City",
        "ZFC": "Fiat truck",
        "ZFE": "KL Motorcycle",
        "ZFF": "Ferrari",
        "ZFJ": "Carrozzeria Pezzaioli",
        "ZFM": "Fantic Motor",
        "ZFR": "Pininfarina",
        "ZG2": "FAAM",
        "ZGA": "Iveco Bus",
        "ZGP": "Merker",
        "ZGU": "Moto Guzzi",
        "ZH5": "FB Mondial",
        "ZHU": "Husqvarna Motorcycles Under Cagiva ownership",
        "ZHW": "Lamborghini",
        "ZHZ": "Menci SpA",
        "ZJM": "Malaguti",
        "ZJN": "Innocenti",
        "ZJT": "Italjet",
        "ZKC": "Ducati Energia Free Duck",
        "ZKH": "Husqvarna Motorcycles Srl Under BMW ownership",
        "ZLA": "Lancia",
        "ZLF": "Tazzari GL SpA",
        "ZLM": "Moto Morini srl",
        "ZLV": "Laverda",
        "ZN0": "SWM Motorcycles S.r.l.",
        "ZN3": "Iveco Defence",
        "ZN6": "Maserati SUV",
        "ZNN": "Energica",
        "ZP6": "XEV",
        "ZP8": "Regis Motors",
        "ZPB": "Lamborghini SUV",
        "ZPY": "DR Automobiles",
        "ZR1": "Microlino",
        "ZRG": "Tazzari GL Imola SpA",
        "ZSG": "Ferrari SUV",
        "ZX1": "TAM (Tovarna Avtomobilov Maribor) bus",
        "ZY1": "Adria (recreational vehicles",
        "ZZ1": "Tomos motorcycle",
    ]

    static func getMake(wmi: String) -> String? {
        entries[wmi.uppercased()]
    }
}